import type { EndToEndFlowSpec } from './schema';

export const endToEndFlows: EndToEndFlowSpec[] = [
  {
    id: 'flow-auth-identity',
    name: 'Auth and Identity',
    trigger: 'User attempts to sign in or create account on any client surface.',
    involvedProducts: ['Fit With Pulse iOS', 'Fit With Pulse Android', 'Pulse Check iOS', 'Fit With Pulse Web + Admin', 'Macra iOS'],
    backendPath: ['Client auth UI', 'Firebase Auth', 'users profile fetch', 'entitlement sync'],
    collectionsTouched: ['users', 'subscriptionRecords', 'users/{uid}/preferences'],
    integrations: ['Firebase Auth', 'Apple Sign In', 'Google Sign In'],
    failurePoints: [
      'Provider sign-in token mismatch',
      'Missing user profile document after auth success',
      'Entitlement not synchronized to client state',
    ],
    steps: [
      { id: 'a1', actor: 'User', action: 'Submits credentials/social login.', output: 'Authentication request initiated.' },
      { id: 'a2', actor: 'Firebase Auth', action: 'Validates identity provider payload.', output: 'Authenticated user token returned.' },
      { id: 'a3', actor: 'Client app', action: 'Loads profile from users document.', output: 'Role, preferences, and access context hydrated.' },
      { id: 'a4', actor: 'Subscription layer', action: 'Validates active entitlement.', output: 'Premium access state set for runtime.' },
    ],
  },
  {
    id: 'flow-subscription-billing',
    name: 'Subscription and Billing',
    trigger: 'User selects a paid plan on mobile or web paywall.',
    involvedProducts: ['Fit With Pulse iOS', 'Fit With Pulse Android', 'Pulse Check iOS', 'Fit With Pulse Web + Admin', 'Macra iOS'],
    backendPath: ['Paywall UI', 'Checkout session', 'Stripe/Store purchase', 'webhook reconciliation'],
    collectionsTouched: ['subscriptionRecords', 'users', 'billing events'],
    integrations: ['Stripe', 'RevenueCat', 'Netlify Functions'],
    failurePoints: [
      'Checkout session creation failure',
      'Webhook missed or delayed',
      'RevenueCat and Stripe state mismatch',
    ],
    steps: [
      { id: 'b1', actor: 'User', action: 'Selects subscription package.', output: 'Purchase intent captured.' },
      { id: 'b2', actor: 'Checkout API', action: 'Creates session or in-app purchase request.', output: 'Transaction window opened.' },
      { id: 'b3', actor: 'Billing provider', action: 'Processes payment and confirms purchase.', output: 'Successful transaction event generated.' },
      { id: 'b4', actor: 'Reconciliation function', action: 'Updates subscription state in Firestore.', output: 'Entitlement state available across products.' },
    ],
  },
  {
    id: 'flow-macra-nutrition-ai',
    name: 'Macra Nutrition AI Loop',
    trigger: 'Macra user logs food, scans a label, asks Nora, or asks Nora to create macros and a meal plan.',
    involvedProducts: ['Macra iOS', 'Fit With Pulse Web + Admin'],
    backendPath: [
      'Macra SwiftUI nutrition surface',
      'Firebase Auth ID token',
      'Netlify OpenAI bridge or Macra nutrition function',
      'OpenAI response normalization',
      'Macra-owned Firestore collection write',
    ],
    collectionsTouched: [
      'users/{uid}/macra/profile',
      'users/{uid}/mealLogs',
      'users/{uid}/labelScans',
      'users/{uid}/noraChat',
      'meal-plan',
      'macro-profile/{uid}/macro-recommendations',
    ],
    integrations: ['Firebase Auth', 'Cloud Firestore', 'Firebase Storage', 'OpenAI', 'Netlify Functions', 'RevenueCat'],
    failurePoints: [
      'Firebase ID token missing or expired before bridge call',
      'Bridge feature label exceeds the configured model or token limit',
      'AI response parses but misses required macro or label fields',
      'Root users/{uid} patch writes more than the Macra-owned field set',
      'Screenshot release assets drift from App Store Connect dimensions after product copy changes',
    ],
    steps: [
      { id: 'm1', actor: 'Macra user', action: 'Starts a nutrition action from Journal, Plan, Scan, Supps, or Ask Nora.', output: 'Typed Macra request payload is built.' },
      { id: 'm2', actor: 'Macra iOS', action: 'Adds Firebase auth and routes AI work through GPTService or a Macra function.', output: 'Authenticated server request reaches Fit With Pulse Web + Admin functions.' },
      { id: 'm3', actor: 'Netlify function', action: 'Verifies the user token, applies feature limits, and forwards the approved prompt to OpenAI.', output: 'Structured nutrition answer or chat response returns to Macra.' },
      { id: 'm4', actor: 'Macra persistence layer', action: 'Writes the resulting meal, label scan, Nora message, macro recommendation, or plan to Macra-owned collections.', output: 'Home, scanner, planning, and chat surfaces refresh from canonical data.' },
    ],
  },
  {
    id: 'flow-round-creation-participation',
    name: 'Round Creation and Participation',
    trigger: 'Creator launches round creation or athlete joins an invitation.',
    involvedProducts: ['Fit With Pulse iOS', 'Fit With Pulse Android', 'Fit With Pulse Web + Admin'],
    backendPath: ['Round builder UI', 'template/custom generation', 'round persistence', 'participant scoring'],
    collectionsTouched: ['sweatlistCollections', 'users/{uid}/workouts', 'sweatlistCollections/{id}/participants', 'sweatlistCollections/{id}/leaderboard-entries'],
    integrations: ['OpenAI'],
    failurePoints: [
      'Invalid generation output from AI layer',
      'Collection write succeeds but participant indexes stale',
      'Leaderboard rank recalculation lag',
    ],
    steps: [
      { id: 'r1', actor: 'Creator', action: 'Defines round config and goals.', output: 'Generation request payload built.' },
      { id: 'r2', actor: 'Generation service', action: 'Builds stacks and schedule.', output: 'Workouts and identifiers prepared.' },
      { id: 'r3', actor: 'Persistence layer', action: 'Writes sweatlist collection and schedule.', output: 'Round published and discoverable.' },
      { id: 'r4', actor: 'Athlete', action: 'Joins and completes assigned workouts.', output: 'Participant progress and leaderboard updates.' },
    ],
  },
  {
    id: 'flow-checkins-analytics',
    name: 'Check-ins and Analytics',
    trigger: 'Athlete submits check-in, workout summary, or nutrition log.',
    involvedProducts: ['Fit With Pulse iOS', 'Fit With Pulse Android', 'Fit With Pulse Web + Admin', 'Pulse Check iOS', 'Macra iOS'],
    backendPath: ['Client capture UI', 'Firestore write', 'aggregation services', 'admin metrics surfaces'],
    collectionsTouched: ['users/{uid}/check-ins', 'workout-summaries', 'users/{uid}/completed-workouts', 'users/{uid}/meals', 'users/{uid}/mealLogs'],
    integrations: ['HealthKit', 'Health Connect', 'OpenAI'],
    failurePoints: [
      'Client timestamp/schema mismatch',
      'Summary aggregation race conditions',
      'Admin metrics filtering on stale fields',
    ],
    steps: [
      { id: 'c1', actor: 'Athlete', action: 'Submits health/performance check-in.', output: 'Check-in document persisted.' },
      { id: 'c2', actor: 'Workout/Nutrition services', action: 'Append session and nutrition context.', output: 'Daily activity context enriched.' },
      { id: 'c3', actor: 'Aggregation jobs', action: 'Compute summary metrics and trends.', output: 'Operational metrics artifacts generated.' },
      { id: 'c4', actor: 'Ops team', action: 'Reviews dashboards and flags interventions.', output: 'Manual or automated follow-up initiated.' },
    ],
  },
  {
    id: 'flow-pulsecheck-organization-activation',
    name: 'Pulse Check Organization Provisioning and Admin Activation',
    trigger: 'An operator provisions a coach-led or institutional organization and sends the first admin activation handoff.',
    involvedProducts: ['Fit With Pulse Web + Admin', 'Fit With Pulse iOS', 'Fit With Pulse Android', 'Pulse Check iOS'],
    backendPath: ['Provisioning console', 'organization/team writes', 'admin activation invite', 'activation redemption API', 'team invite readiness'],
    collectionsTouched: [
      'pulsecheck-organizations',
      'pulsecheck-teams',
      'pulsecheck-organization-memberships',
      'pulsecheck-team-memberships',
      'pulsecheck-invite-links',
      'users',
    ],
    integrations: ['Firebase Auth', 'Next.js API routes'],
    failurePoints: [
      'Activation invite is missing organization or team context',
      'Admin redemption succeeds but org/team membership role is wrong',
      'Team container activates without the invite policy or permissions needed for downstream invites',
    ],
    steps: [
      { id: 'k1', actor: 'Operator', action: 'Creates the organization, initial team, and admin activation link in the provisioning console.', output: 'Pulse Check container and first admin handoff are ready.' },
      { id: 'k2', actor: 'External admin', action: 'Redeems the admin activation invite and signs in or creates an account.', output: 'Admin identity is attached to the organization and team.' },
      { id: 'k3', actor: 'Activation API', action: 'Writes organization membership, team membership, and activation status.', output: 'Org admin and team admin roles are active in source-of-truth collections.' },
      { id: 'k4', actor: 'PulseCheck workspace', action: 'Loads the post-activation container and prepares downstream invite creation.', output: 'The new org and team are ready for staff, coach, or athlete invites.' },
    ],
  },
  {
    id: 'flow-creator-engagement-economics',
    name: 'Creator Engagement, Score, and Payout Lifecycle',
    trigger: 'Athlete reaches, likes, bookmarks, or uses a creator video; creator later requests payout or monthly statement.',
    involvedProducts: ['Fit With Pulse iOS', 'Fit With Pulse Web + Admin'],
    backendPath: [
      'Exercise interaction hooks',
      'engagement-events write',
      'categoryPoints.creator accumulation',
      'leaderboards cache',
      'unified earnings and payout functions',
      'monthly statement retrieval',
    ],
    collectionsTouched: [
      'engagement-events',
      'exerciseVideos',
      'users',
      'leaderboards/topCreators',
      'payoutRecords',
      'prizeRecords',
    ],
    integrations: ['Stripe', 'Netlify Functions'],
    failurePoints: [
      'Engagement event dropped or duplicated causing score drift',
      'Creator score cache stale vs raw users/categoryPoints.creator values',
      'Connected account payout schedule differs from expected operating cadence',
      'Balance below payout threshold blocks withdrawal despite visible earnings',
    ],
    steps: [
      { id: 'e1', actor: 'Athlete', action: 'Interacts with creator video (reach/like/bookmark/use).', output: 'Engagement payload created.' },
      { id: 'e2', actor: 'Fit With Pulse iOS', action: 'Writes event into engagement-events and updates local like/bookmark state.', output: 'Event stream and user subcollections updated.' },
      { id: 'e3', actor: 'Scoring services', action: 'Increment or backfill users.categoryPoints.creator and refresh top creator cache.', output: 'Creator leaderboard score materialized.' },
      { id: 'e4', actor: 'Web earnings surfaces', action: 'Load unified balances from Stripe-backed earnings APIs.', output: 'Wallet/pending/earnings totals displayed.' },
      { id: 'e5', actor: 'Payout and statement tools', action: 'Initiate payout or fetch completed-month statement.', output: 'payoutRecords audit trail and monthly statement data available.' },
    ],
  },
  {
    id: 'flow-agent-workloop',
    name: 'Agent Workflow Loop',
    trigger: 'Telemetry check or mission kickoff creates/assigns agent work capsules.',
    involvedProducts: ['Fit With Pulse Web + Admin (Virtual Office)', 'Agent Runner Runtime'],
    backendPath: ['Mission/telemetry trigger', 'kanban assignment', 'agent execution', 'timeline and minutes publish'],
    collectionsTouched: ['company-config/north-star', 'company-config/mission-status', 'kanbanTasks', 'agent-presence', 'progress-timeline', 'meeting-minutes', 'agent-group-chats'],
    integrations: ['OpenClaw', 'OpenAI'],
    failurePoints: [
      'Runner heartbeat drops and task remains in-progress',
      'Validation failure creating corrective tasks repeatedly',
      'North Star stale objective causing low-value assignment loops',
    ],
    steps: [
      { id: 'g1', actor: 'Operator or scheduler', action: 'Triggers mission/telemetry cycle.', output: 'Assignment cycle begins.' },
      { id: 'g2', actor: 'Task manager', action: 'Writes capsules to kanbanTasks.', output: 'Agent-specific work queue populated.' },
      { id: 'g3', actor: 'Agent runners', action: 'Execute steps and post beats.', output: 'Realtime progress stream updated.' },
      { id: 'g4', actor: 'Coordination scripts', action: 'Publish minutes and reset presence state.', output: 'Session archived with next-loop readiness.' },
    ],
  },
];
