import type { EndToEndFlowSpec } from './schema';

export const endToEndFlows: EndToEndFlowSpec[] = [
  {
    id: 'flow-auth-identity',
    name: 'Auth and Identity',
    trigger: 'User attempts to sign in or create account on any client surface.',
    involvedProducts: ['QuickLifts iOS', 'Pulse Android', 'PulseCheck iOS', 'QuickLifts Web'],
    backendPath: ['Client auth UI', 'Firebase Auth', 'users profile fetch', 'entitlement sync'],
    collectionsTouched: ['users', 'subscriptionRecords', 'users/{uid}/preferences'],
    integrations: ['Firebase Auth', 'Apple Sign In', 'Google Sign In'],
    failurePoints: [
      'Provider sign-in token mismatch',
      'Missing user profile document after auth success',
      'Entitlement not synchronized to client state',
    ],
    steps: [
      { id: 'a1', actor: 'User', action: 'Submits credentials/social login.', output: 'Authentication request initiated.' },
      { id: 'a2', actor: 'Firebase Auth', action: 'Validates identity provider payload.', output: 'Authenticated user token returned.' },
      { id: 'a3', actor: 'Client app', action: 'Loads profile from users document.', output: 'Role, preferences, and access context hydrated.' },
      { id: 'a4', actor: 'Subscription layer', action: 'Validates active entitlement.', output: 'Premium access state set for runtime.' },
    ],
  },
  {
    id: 'flow-subscription-billing',
    name: 'Subscription and Billing',
    trigger: 'User selects a paid plan on mobile or web paywall.',
    involvedProducts: ['QuickLifts iOS', 'Pulse Android', 'PulseCheck iOS', 'QuickLifts Web'],
    backendPath: ['Paywall UI', 'Checkout session', 'Stripe/Store purchase', 'webhook reconciliation'],
    collectionsTouched: ['subscriptionRecords', 'users', 'billing events'],
    integrations: ['Stripe', 'RevenueCat', 'Netlify Functions'],
    failurePoints: [
      'Checkout session creation failure',
      'Webhook missed or delayed',
      'RevenueCat and Stripe state mismatch',
    ],
    steps: [
      { id: 'b1', actor: 'User', action: 'Selects subscription package.', output: 'Purchase intent captured.' },
      { id: 'b2', actor: 'Checkout API', action: 'Creates session or in-app purchase request.', output: 'Transaction window opened.' },
      { id: 'b3', actor: 'Billing provider', action: 'Processes payment and confirms purchase.', output: 'Successful transaction event generated.' },
      { id: 'b4', actor: 'Reconciliation function', action: 'Updates subscription state in Firestore.', output: 'Entitlement state available across products.' },
    ],
  },
  {
    id: 'flow-round-creation-participation',
    name: 'Round Creation and Participation',
    trigger: 'Creator launches round creation or athlete joins an invitation.',
    involvedProducts: ['QuickLifts iOS', 'Pulse Android', 'QuickLifts Web'],
    backendPath: ['Round builder UI', 'template/custom generation', 'round persistence', 'participant scoring'],
    collectionsTouched: ['sweatlistCollections', 'users/{uid}/workouts', 'sweatlistCollections/{id}/participants', 'sweatlistCollections/{id}/leaderboard-entries'],
    integrations: ['OpenAI'],
    failurePoints: [
      'Invalid generation output from AI layer',
      'Collection write succeeds but participant indexes stale',
      'Leaderboard rank recalculation lag',
    ],
    steps: [
      { id: 'r1', actor: 'Creator', action: 'Defines round config and goals.', output: 'Generation request payload built.' },
      { id: 'r2', actor: 'Generation service', action: 'Builds stacks and schedule.', output: 'Workouts and identifiers prepared.' },
      { id: 'r3', actor: 'Persistence layer', action: 'Writes sweatlist collection and schedule.', output: 'Round published and discoverable.' },
      { id: 'r4', actor: 'Athlete', action: 'Joins and completes assigned workouts.', output: 'Participant progress and leaderboard updates.' },
    ],
  },
  {
    id: 'flow-checkins-analytics',
    name: 'Check-ins and Analytics',
    trigger: 'Athlete submits check-in, workout summary, or nutrition log.',
    involvedProducts: ['QuickLifts iOS', 'Pulse Android', 'QuickLifts Web', 'PulseCheck iOS'],
    backendPath: ['Client capture UI', 'Firestore write', 'aggregation services', 'admin metrics surfaces'],
    collectionsTouched: ['users/{uid}/check-ins', 'workout-summaries', 'users/{uid}/completed-workouts', 'users/{uid}/meals'],
    integrations: ['HealthKit', 'Health Connect'],
    failurePoints: [
      'Client timestamp/schema mismatch',
      'Summary aggregation race conditions',
      'Admin metrics filtering on stale fields',
    ],
    steps: [
      { id: 'c1', actor: 'Athlete', action: 'Submits health/performance check-in.', output: 'Check-in document persisted.' },
      { id: 'c2', actor: 'Workout/Nutrition services', action: 'Append session and nutrition context.', output: 'Daily activity context enriched.' },
      { id: 'c3', actor: 'Aggregation jobs', action: 'Compute summary metrics and trends.', output: 'Operational metrics artifacts generated.' },
      { id: 'c4', actor: 'Ops team', action: 'Reviews dashboards and flags interventions.', output: 'Manual or automated follow-up initiated.' },
    ],
  },
  {
    id: 'flow-coach-workflow',
    name: 'Coach Partnership Workflow',
    trigger: 'Coach enters partnership funnel and links athletes/referrals.',
    involvedProducts: ['QuickLifts Web', 'QuickLifts iOS', 'Pulse Android', 'PulseCheck iOS'],
    backendPath: ['Coach signup', 'billing activation', 'athlete linking', 'revenue calculation'],
    collectionsTouched: ['coaches', 'coachAthletes', 'coachReferrals', 'revenue-calculations', 'users'],
    integrations: ['Stripe', 'Netlify Functions', 'Brevo'],
    failurePoints: [
      'Referral code attribution mismatch',
      'Coach subscription active but dashboard role missing',
      'Revenue calculation job delayed or partial',
    ],
    steps: [
      { id: 'k1', actor: 'Coach', action: 'Completes partnership signup and payment.', output: 'Coach profile and subscription state activated.' },
      { id: 'k2', actor: 'Coach funnel backend', action: 'Stores referral and scheduling metadata.', output: 'Attribution trail established.' },
      { id: 'k3', actor: 'Athlete', action: 'Joins via coach referral and subscribes.', output: 'Coach-athlete relationship linked.' },
      { id: 'k4', actor: 'Revenue jobs', action: 'Compute direct/referral payouts.', output: 'Monthly earnings state updated.' },
    ],
  },
  {
    id: 'flow-creator-engagement-economics',
    name: 'Creator Engagement, Score, and Payout Lifecycle',
    trigger: 'Athlete reaches, likes, bookmarks, or uses a creator video; creator later requests payout or monthly statement.',
    involvedProducts: ['QuickLifts iOS', 'QuickLifts Web'],
    backendPath: [
      'Exercise interaction hooks',
      'engagement-events write',
      'categoryPoints.creator accumulation',
      'leaderboards cache',
      'unified earnings and payout functions',
      'monthly statement retrieval',
    ],
    collectionsTouched: [
      'engagement-events',
      'exerciseVideos',
      'users',
      'leaderboards/topCreators',
      'payoutRecords',
      'prizeRecords',
    ],
    integrations: ['Stripe', 'Netlify Functions'],
    failurePoints: [
      'Engagement event dropped or duplicated causing score drift',
      'Creator score cache stale vs raw users/categoryPoints.creator values',
      'Connected account payout schedule differs from expected operating cadence',
      'Balance below payout threshold blocks withdrawal despite visible earnings',
    ],
    steps: [
      { id: 'e1', actor: 'Athlete', action: 'Interacts with creator video (reach/like/bookmark/use).', output: 'Engagement payload created.' },
      { id: 'e2', actor: 'QuickLifts iOS', action: 'Writes event into engagement-events and updates local like/bookmark state.', output: 'Event stream and user subcollections updated.' },
      { id: 'e3', actor: 'Scoring services', action: 'Increment or backfill users.categoryPoints.creator and refresh top creator cache.', output: 'Creator leaderboard score materialized.' },
      { id: 'e4', actor: 'Web earnings surfaces', action: 'Load unified balances from Stripe-backed earnings APIs.', output: 'Wallet/pending/earnings totals displayed.' },
      { id: 'e5', actor: 'Payout and statement tools', action: 'Initiate payout or fetch completed-month statement.', output: 'payoutRecords audit trail and monthly statement data available.' },
    ],
  },
  {
    id: 'flow-agent-workloop',
    name: 'Agent Workflow Loop',
    trigger: 'Telemetry check or mission kickoff creates/assigns agent work capsules.',
    involvedProducts: ['QuickLifts Web (Virtual Office)', 'Agent Runner Runtime'],
    backendPath: ['Mission/telemetry trigger', 'kanban assignment', 'agent execution', 'timeline and minutes publish'],
    collectionsTouched: ['company-config/north-star', 'company-config/mission-status', 'kanbanTasks', 'agent-presence', 'progress-timeline', 'meeting-minutes', 'agent-group-chats'],
    integrations: ['OpenClaw', 'OpenAI'],
    failurePoints: [
      'Runner heartbeat drops and task remains in-progress',
      'Validation failure creating corrective tasks repeatedly',
      'North Star stale objective causing low-value assignment loops',
    ],
    steps: [
      { id: 'g1', actor: 'Operator or scheduler', action: 'Triggers mission/telemetry cycle.', output: 'Assignment cycle begins.' },
      { id: 'g2', actor: 'Task manager', action: 'Writes capsules to kanbanTasks.', output: 'Agent-specific work queue populated.' },
      { id: 'g3', actor: 'Agent runners', action: 'Execute steps and post beats.', output: 'Realtime progress stream updated.' },
      { id: 'g4', actor: 'Coordination scripts', action: 'Publish minutes and reset presence state.', output: 'Session archived with next-loop readiness.' },
    ],
  },
];
