import type { SystemOverviewManifest } from './schema';
import { endToEndFlows } from './flows';
import { quickliftsIosHandbook } from './products/quicklifts-ios';
import { pulseAndroidHandbook } from './products/pulse-android';
import { pulseCheckIosHandbook } from './products/pulsecheck-ios';
import { quickliftsWebHandbook } from './products/quicklifts-web';

export const systemOverviewManifest: SystemOverviewManifest = {
  title: 'System Overview Handbook',
  subtitle:
    'Document-first source of truth for Pulse architecture, products, data flows, ownership, and operational dependencies.',
  lastUpdated: '2026-03-10',
  sections: [
    { id: 'executive-summary', label: 'Executive Summary', description: 'Scope, mission, and latest changes.' },
    { id: 'ecosystem-map', label: 'Ecosystem Map', description: 'Layered map of products, backend, integrations, and agents.' },
    { id: 'product-handbooks', label: 'Product Handbooks', description: 'Feature-by-feature inventory for each product surface.' },
    { id: 'pulse-club-activation-architecture', label: 'Club Activation Architecture', description: 'Generic creator-club operating model for onboarding, introductions, and member pairing.' },
    { id: 'backend-data', label: 'Backend and Data', description: 'Core services and canonical data collections.' },
    { id: 'integrations', label: 'Integrations', description: 'External systems, ownership, and credential sources.' },
    { id: 'end-to-end-flows', label: 'End-to-End Flows', description: 'Cross-product flows from trigger to failure points.' },
    { id: 'ownership-release-matrix', label: 'Ownership Matrix', description: 'Operational ownership and release cadence.' },
    { id: 'agent-infrastructure-handbook', label: 'Agent Infrastructure Handbook', description: 'Heartbeat protocol and operator playbook.' },
    { id: 'hunter-world-handbook', label: 'Hunter World Handbook', description: 'Leveling, class mechanics, and creator ecosystem chapter.' },
    { id: 'risks-gaps', label: 'Risks and Gaps', description: 'Current known risk posture and mitigations.' },
    { id: 'glossary', label: 'Glossary', description: 'Shared language for cross-functional alignment.' },
    { id: 'simulation-taxonomy', label: 'Simulation Taxonomy', description: 'PulseCheck mental performance pillars, skills, sims, and scoring.' },
    { id: 'sim-family-tree', label: 'Sim Family Tree', description: 'Locked families, candidates, variants, and hybrid modules.' },
    { id: 'promotion-protocol', label: 'Promotion Protocol', description: 'How new sim families are proposed, evaluated, and promoted.' },
    { id: 'sim-spec-standards', label: 'Spec Standards', description: 'Shared measurement precision, fail conditions, trial rules, and validation roadmap.' },
    { id: 'variant-registry', label: 'Variant Registry', description: 'Exhaustive inventory of all named variants with spec status tracking.' },
    { id: 'sim-family-specs', label: 'Sim FamilySpecs', description: 'Complete specifications for each simulation family.' },
    { id: 'athlete-journey', label: 'Athlete Journey', description: 'Recommended entry, progression, and system flow for athlete adoption.' },
    { id: 'coach-journey', label: 'Coach Journey', description: 'Recommended entry, setup, and daily operating flow for coaches using Pulse Check.' },
    { id: 'pulsecheck-runtime-architecture', label: 'Runtime Architecture', description: 'Top-level operating model for the perception-to-action runtime stack.' },
    { id: 'pulsecheck-state-signal-layer', label: 'State Signal Layer', description: 'Operational state inference, confidence bands, freshness rules, and routing outputs for Nora.' },
    { id: 'pulsecheck-state-snapshot-freshness-policy', label: 'Snapshot Freshness Policy', description: 'Shared recency, validity, and decay rules for state snapshots used across runtime consumers.' },
    { id: 'pulsecheck-performance-state-flag-definitions', label: 'Performance-State Flags', description: 'Family-level definitions for translating acute sim behavior into state evidence.' },
    { id: 'pulsecheck-nora-assignment-rules', label: 'Nora Assignment Rules', description: 'Decision rules for Protocol, Sim, Trial, defer, and safety-aware assignment behavior.' },
    { id: 'pulsecheck-nora-qa-edge-case-matrix', label: 'Nora QA Matrix', description: 'Conflict, override, and edge-case scenarios for testing runtime behavior before pilot.' },
    { id: 'pulsecheck-state-escalation-orchestration', label: 'State & Escalation Orchestration', description: 'Shared upstream state perception with separate performance, support, and safety lanes.' },
    { id: 'pulsecheck-escalation-integration-spec', label: 'Escalation Integration Spec', description: 'Execution-layer bridge between state snapshots and the escalation workflow.' },
    { id: 'pulsecheck-team-pilot-cohort-onboarding-architecture', label: 'Team & Pilot Onboarding', description: 'How organizations, teams, pilots, cohorts, clinicians, and enrollments enter the system.' },
    { id: 'pulsecheck-permissions-visibility-model', label: 'Permissions & Visibility', description: 'Role-based access, invite-linked permissions, and minimum-necessary visibility rules.' },
    { id: 'pulsecheck-coach-dashboard-information-architecture', label: 'Coach Dashboard IA', description: 'Coach-facing information hierarchy, workflows, and privacy boundaries for roster visibility.' },
  ],
  executiveSummary: {
    mission:
      'Maintain a complete, implementation-grounded map of the Pulse ecosystem so product, engineering, and operations can execute from one shared system truth.',
    audience:
      'Exec + Internal Mixed: quick strategic readability with deep technical drill-down for builders.',
    whatChangedRecently: [
      'Added Pulse Community Club Activation Architecture artifact for generic creator-club onboarding, introductions, and pairing.',
      'Replaced tab-driven architecture page with a full handbook structure and anchored navigation.',
      'Added complete feature inventories for QuickLifts iOS, Pulse Android, PulseCheck iOS, and QuickLifts Web.',
      'Normalized backend/data/integration ownership into explicit matrix rows and release cadences.',
      'Mapped seven cross-product end-to-end flows with concrete failure points and collection touch paths.',
      'Added explicit creator engagement, creator score, wallet, payout, and statement lifecycle documentation.',
      'Maintained agent and Hunter World chapters directly inside the handbook information architecture.',
    ],
    highlights: [
      'Single-page handbook spanning consumer products, ops tooling, and autonomous agent infrastructure.',
      'Static typed content model in repo; no Firebase persistence required for handbook content updates.',
      'Dual-layer security model: admin role guard + page-level passcode gate.',
    ],
  },
  ecosystemMap: {
    nodes: [
      {
        id: 'quicklifts-ios',
        name: 'QuickLifts iOS',
        layer: 'surface',
        status: 'active',
        description: 'Flagship mobile product for workouts, rounds, and nutrition.',
        owner: 'iOS Squad',
        x: 14,
        y: 16,
      },
      {
        id: 'pulse-android',
        name: 'Pulse Android',
        layer: 'surface',
        status: 'active',
        description: 'Android native product for parity across workout and round flows.',
        owner: 'Android Squad',
        x: 32,
        y: 20,
      },
      {
        id: 'pulsecheck-ios',
        name: 'PulseCheck iOS',
        layer: 'surface',
        status: 'active',
        description: 'Mental-performance companion product and coach readiness surface.',
        owner: 'PulseCheck Team',
        x: 52,
        y: 16,
      },
      {
        id: 'quicklifts-web',
        name: 'QuickLifts Web',
        layer: 'surface',
        status: 'active',
        description: 'Growth, admin, creator, coach, and agent command surfaces.',
        owner: 'Web Platform',
        x: 74,
        y: 22,
      },
      {
        id: 'firebase-auth',
        name: 'Firebase Auth',
        layer: 'backend',
        status: 'active',
        description: 'Identity foundation across all clients.',
        owner: 'Platform',
        x: 18,
        y: 50,
      },
      {
        id: 'cloud-firestore',
        name: 'Cloud Firestore',
        layer: 'backend',
        status: 'active',
        description: 'Primary operational and product data store.',
        owner: 'Platform',
        x: 39,
        y: 56,
      },
      {
        id: 'firebase-storage',
        name: 'Firebase Storage',
        layer: 'backend',
        status: 'active',
        description: 'Media and document storage for app and operations.',
        owner: 'Platform',
        x: 59,
        y: 55,
      },
      {
        id: 'netlify-functions',
        name: 'Netlify Functions',
        layer: 'backend',
        status: 'active',
        description: 'Server-side jobs for billing, messaging, and automation.',
        owner: 'Web Platform',
        x: 80,
        y: 60,
      },
      {
        id: 'stripe',
        name: 'Stripe',
        layer: 'integration',
        status: 'active',
        description: 'Web billing, coach payouts, and connected account workflows.',
        owner: 'Monetization',
        x: 20,
        y: 82,
      },
      {
        id: 'revenuecat',
        name: 'RevenueCat',
        layer: 'integration',
        status: 'active',
        description: 'Mobile entitlement synchronization.',
        owner: 'Monetization',
        x: 38,
        y: 84,
      },
      {
        id: 'brevo',
        name: 'Brevo',
        layer: 'integration',
        status: 'active',
        description: 'Lifecycle email and waitlist automations.',
        owner: 'Growth Ops',
        x: 58,
        y: 83,
      },
      {
        id: 'instantly',
        name: 'Instantly',
        layer: 'integration',
        status: 'active',
        description: 'Outbound sequencing and prospecting flows.',
        owner: 'Growth Ops',
        x: 78,
        y: 82,
      },
      {
        id: 'agent-runner',
        name: 'Agent Runner',
        layer: 'agent',
        status: 'active',
        description: 'Long-running execution loop for autonomous capsule work.',
        owner: 'Agent Infra',
        x: 30,
        y: 34,
      },
      {
        id: 'virtual-office',
        name: 'Virtual Office',
        layer: 'agent',
        status: 'active',
        description: 'Operator surface for presence, timeline, and intervention.',
        owner: 'Agent Infra',
        x: 50,
        y: 33,
      },
      {
        id: 'telemetry-check',
        name: 'Telemetry Check',
        layer: 'agent',
        status: 'active',
        description: 'Hourly standup protocol creating capsules and meeting records.',
        owner: 'Agent Infra',
        x: 70,
        y: 35,
      },
    ],
    connections: [
      { from: 'quicklifts-ios', to: 'firebase-auth', type: 'auth' },
      { from: 'quicklifts-ios', to: 'cloud-firestore', type: 'data' },
      { from: 'pulse-android', to: 'firebase-auth', type: 'auth' },
      { from: 'pulse-android', to: 'cloud-firestore', type: 'data' },
      { from: 'pulsecheck-ios', to: 'firebase-auth', type: 'auth' },
      { from: 'pulsecheck-ios', to: 'cloud-firestore', type: 'data' },
      { from: 'quicklifts-web', to: 'firebase-auth', type: 'auth' },
      { from: 'quicklifts-web', to: 'cloud-firestore', type: 'data' },
      { from: 'quicklifts-web', to: 'netlify-functions', type: 'events' },
      { from: 'cloud-firestore', to: 'netlify-functions', type: 'events' },
      { from: 'cloud-firestore', to: 'virtual-office', type: 'data' },
      { from: 'cloud-firestore', to: 'agent-runner', type: 'data' },
      { from: 'virtual-office', to: 'telemetry-check', type: 'events' },
      { from: 'netlify-functions', to: 'stripe', type: 'data' },
      { from: 'quicklifts-ios', to: 'revenuecat', type: 'events' },
      { from: 'pulse-android', to: 'revenuecat', type: 'events' },
      { from: 'netlify-functions', to: 'brevo', type: 'events' },
      { from: 'netlify-functions', to: 'instantly', type: 'events' },
    ],
  },
  products: [quickliftsIosHandbook, pulseAndroidHandbook, pulseCheckIosHandbook, quickliftsWebHandbook],
  backendServices: [
    {
      id: 'svc-firebase-auth',
      name: 'Firebase Auth',
      purpose: 'Cross-platform authentication, provider sign-in, and session identity state.',
      owner: 'Platform',
      status: 'active',
      environments: ['Development', 'Production'],
      keyDependencies: ['Client auth UIs', 'users profile bootstrap'],
      sourceRefs: [
        { label: 'Auth Wrapper', path: 'src/components/AuthWrapper.tsx' },
        { label: 'Android README', path: '../Pulse-Android/README.md' },
      ],
    },
    {
      id: 'svc-firestore',
      name: 'Cloud Firestore',
      purpose: 'Primary datastore for app entities, operational controls, and agent runtime state.',
      owner: 'Platform',
      status: 'active',
      environments: ['Development', 'Production'],
      keyDependencies: ['All product repositories', 'Agent runtime', 'Admin dashboards'],
      sourceRefs: [
        { label: 'Firestore Contract', path: '../Pulse-Android/docs/FIRESTORE_CONTRACT.md' },
        { label: 'Presence Service', path: 'src/api/firebase/presence/service.ts' },
      ],
    },
    {
      id: 'svc-storage',
      name: 'Firebase Storage',
      purpose: 'Media and artifacts for profile images, exercise videos, and legal documents.',
      owner: 'Platform',
      status: 'active',
      environments: ['Development', 'Production'],
      keyDependencies: ['Creator uploads', 'press assets', 'exercise media'],
      sourceRefs: [
        { label: 'Storage Service', path: 'src/api/firebase/storage/service.ts' },
        { label: 'Press Upload', path: 'src/pages/press/upload.tsx' },
      ],
    },
    {
      id: 'svc-netlify-functions',
      name: 'Netlify Functions',
      purpose: 'Server-side actions for checkout, messaging, automations, and scheduled jobs.',
      owner: 'Web Platform',
      status: 'active',
      environments: ['Development', 'Production'],
      keyDependencies: ['Stripe workflows', 'admin APIs', 'automation jobs'],
      sourceRefs: [
        { label: 'Netlify Functions Structure', path: 'docs/netlify-functions-structure.md' },
        { label: 'Functions Directory', path: 'netlify/functions' },
      ],
    },
    {
      id: 'svc-creator-economics',
      name: 'Creator Engagement and Earnings Runtime',
      purpose:
        'Tracks creator engagement events, materializes creator score surfaces, and orchestrates earnings/payout flows.',
      owner: 'Creator Platform + Monetization Team',
      status: 'active',
      environments: ['Development', 'Production'],
      keyDependencies: ['engagement-events', 'users/categoryPoints.creator', 'leaderboards cache', 'Stripe Connect'],
      sourceRefs: [
        { label: 'iOS Engagement Service', path: '../iOS/QuickLifts/QuickLifts/Services/EngagementService.swift' },
        { label: 'Unified Earnings Function', path: 'netlify/functions/get-unified-earnings.js' },
        { label: 'Unified Payout Function', path: 'netlify/functions/initiate-unified-payout.js' },
        { label: 'Leaderboard Cache Script', path: 'scripts/cacheLeaderboardsOnce.js' },
      ],
    },
    {
      id: 'svc-agent-runner',
      name: 'Agent Runner Runtime',
      purpose: 'Autonomous task polling, execution, validation, and heartbeat emissions.',
      owner: 'Agent Infra',
      status: 'active',
      environments: ['Mac Mini runner environment'],
      keyDependencies: ['kanbanTasks', 'progress-timeline', 'agent-presence'],
      sourceRefs: [
        { label: 'Agent Runner', path: 'scripts/agentRunner.js' },
        { label: 'Heartbeat Protocol', path: 'src/components/admin/HeartbeatProtocolTab.tsx' },
      ],
    },
    {
      id: 'svc-telemetry-check',
      name: 'Telemetry Check Coordination',
      purpose: 'Group standup orchestration, capsule assignment, and meeting minutes publication.',
      owner: 'Agent Infra',
      status: 'active',
      environments: ['Runner environment'],
      keyDependencies: ['company-config', 'standup-config', 'agent-group-chats'],
      sourceRefs: [
        { label: 'Daily Standup Script', path: 'scripts/dailyStandup.js' },
        { label: 'Trigger API', path: 'src/pages/api/agent/trigger-standup.ts' },
      ],
    },
  ],
  dataCollections: [
    {
      id: 'coll-users',
      name: 'users',
      purpose: 'Canonical user profile and role records across products.',
      writtenBy: 'All clients, onboarding flows, admin tools',
      readBy: 'All clients and admin pages',
      criticalFields: [
        'id',
        'email',
        'subscriptionType',
        'role',
        'categoryPoints.creator',
        'creator.stripeAccountId',
        'creator.walletBalance',
        'creator.historicEarnings',
        'createdAt',
        'updatedAt',
      ],
      sourceRefs: [
        { label: 'Android Firestore Contract', path: '../Pulse-Android/docs/FIRESTORE_CONTRACT.md' },
        { label: 'User Service', path: 'src/api/firebase/user/service.ts' },
      ],
    },
    {
      id: 'coll-sweatlist',
      name: 'sweatlistCollections',
      purpose: 'Rounds/challenges including schedule windows and configuration.',
      writtenBy: 'Round creation flows',
      readBy: 'Round detail screens and leaderboards',
      criticalFields: ['title', 'creatorId', 'startDate', 'endDate', 'participantCount', 'status'],
      sourceRefs: [
        { label: 'Round Contract', path: '../Pulse-Android/docs/FIRESTORE_CONTRACT.md' },
        { label: 'Round Creation Page', path: 'src/pages/create-round.tsx' },
      ],
    },
    {
      id: 'coll-workout-summaries',
      name: 'workout-summaries',
      purpose: 'Aggregated workout session summaries for analytics and admin audits.',
      writtenBy: 'Workout completion pipelines',
      readBy: 'Admin metrics dashboards',
      criticalFields: ['userId', 'title', 'duration', 'exercises', 'startTime'],
      sourceRefs: [
        { label: 'Metrics Page', path: 'src/pages/admin/metrics.tsx' },
        { label: 'Workout Summaries Page', path: 'src/pages/admin/workoutSummaries.tsx' },
      ],
    },
    {
      id: 'coll-engagement-events',
      name: 'engagement-events',
      purpose: 'Event log for creator content engagement including reach, likes, bookmarks, and workout usage.',
      writtenBy: 'QuickLifts iOS engagement instrumentation',
      readBy: 'Creator analytics, score pipelines, and payout computation surfaces',
      criticalFields: ['type', 'videoId', 'creatorId', 'engagerId', 'engagerSubscription', 'workoutId', 'timestamp'],
      sourceRefs: [
        { label: 'Engagement Service', path: '../iOS/QuickLifts/QuickLifts/Services/EngagementService.swift' },
        { label: 'Exercise Logging Hooks', path: '../iOS/QuickLifts/QuickLifts/Models/Exercise.swift' },
      ],
    },
    {
      id: 'coll-exercise-videos',
      name: 'exerciseVideos',
      purpose: 'Canonical creator video records with aggregate engagement counters used by creator dashboards.',
      writtenBy: 'Creator upload and moderation pipelines',
      readBy: 'Discover/feed clients, creator dashboards, user service hydration',
      criticalFields: ['userId', 'exerciseId', 'totalAccountLikes', 'totalAccountBookmarked', 'totalAccountUsage', 'createdAt'],
      sourceRefs: [
        { label: 'Exercise Video Types', path: 'src/api/firebase/exercise/types.ts' },
        { label: 'User Video Fetch', path: 'src/api/firebase/user/service.ts' },
        { label: 'Professional Dashboard', path: '../iOS/QuickLifts/QuickLifts/View/Screens/LibraryView/ProfessionalDashboardCard/ProfessionalDashboadView.swift' },
      ],
    },
    {
      id: 'coll-leaderboards',
      name: 'leaderboards',
      purpose: 'Cached leaderboard documents for global users and top creators, including creator score ordering.',
      writtenBy: 'Leaderboard cache and score backfill scripts',
      readBy: 'Global leaderboard surfaces and creator discovery views',
      criticalFields: ['global100.users[]', 'topCreators.users[].creatorScore', 'updatedAt'],
      sourceRefs: [
        { label: 'Leaderboard Cache Script', path: 'scripts/cacheLeaderboardsOnce.js' },
        { label: 'Creator Score Backfill', path: 'scripts/backfillCreatorScore.js' },
        { label: 'Top Creators ViewModel', path: '../iOS/QuickLifts/QuickLifts/View/Screens/Leaderboard/GlobalLeaderboardViewModel.swift' },
      ],
    },
    {
      id: 'coll-payout-records',
      name: 'payoutRecords',
      purpose: 'Unified payout audit records for creator and winner transfers executed through Stripe.',
      writtenBy: 'initiate-unified-payout function',
      readBy: 'Admin payout dashboard and support operations',
      criticalFields: ['userId', 'amount', 'currency', 'strategy', 'results', 'createdAt', 'type'],
      sourceRefs: [
        { label: 'Initiate Unified Payout', path: 'netlify/functions/initiate-unified-payout.js' },
        { label: 'Admin Payout Dashboard', path: 'src/pages/admin/adminPayouts.tsx' },
      ],
    },
    {
      id: 'coll-agent-presence',
      name: 'agent-presence',
      purpose: 'Live runner status, task progress, and heartbeat timestamps per agent.',
      writtenBy: 'Agent Runner',
      readBy: 'Virtual Office and mission surfaces',
      criticalFields: ['status', 'currentTask', 'taskProgress', 'lastUpdate'],
      sourceRefs: [
        { label: 'Presence Service', path: 'src/api/firebase/presence/service.ts' },
        { label: 'Virtual Office', path: 'src/components/virtualOffice/VirtualOfficeContent.tsx' },
      ],
    },
    {
      id: 'coll-kanban',
      name: 'kanbanTasks',
      purpose: 'Agent capsule queue and task lifecycle state machine.',
      writtenBy: 'Operators, telemetry check, automation scripts',
      readBy: 'Agent Runner and Kanban UI',
      criticalFields: ['name', 'assignee', 'status', 'priority', 'source', 'northStarAligned'],
      sourceRefs: [
        { label: 'Kanban Service', path: 'src/api/firebase/kanban/service.ts' },
        { label: 'Kanban Seeder', path: 'scripts/manageKanban.js' },
      ],
    },
    {
      id: 'coll-progress-timeline',
      name: 'progress-timeline',
      purpose: 'Heartbeat feed of agent events and execution milestones.',
      writtenBy: 'Agent Runner and telemetry scripts',
      readBy: 'Virtual Office timeline panels',
      criticalFields: ['agentId', 'beat', 'headline', 'confidenceColor', 'createdAt'],
      sourceRefs: [
        { label: 'Progress Timeline Service', path: 'src/api/firebase/progressTimeline/service.ts' },
        { label: 'Timeline Panel', path: 'src/components/virtualOffice/ProgressTimelinePanel.tsx' },
      ],
    },
    {
      id: 'coll-meeting-minutes',
      name: 'meeting-minutes',
      purpose: 'Archived telemetry summaries and context for operator review.',
      writtenBy: 'Telemetry check scripts',
      readBy: 'Filing cabinet UI',
      criticalFields: ['sessionId', 'summary', 'durationMinutes', 'createdAt'],
      sourceRefs: [
        { label: 'Meeting Minutes Service', path: 'src/api/firebase/meetingMinutes/service.ts' },
        { label: 'Filing Cabinet', path: 'src/components/virtualOffice/FilingCabinet.tsx' },
      ],
    },
    {
      id: 'coll-company-config',
      name: 'company-config',
      purpose: 'Mission, north star, and system-level control documents.',
      writtenBy: 'Mission control and admin panels',
      readBy: 'Mission kickoff and agent assignment systems',
      criticalFields: ['north-star', 'mission-status'],
      sourceRefs: [
        { label: 'Mission Control', path: 'src/pages/admin/missionControl.tsx' },
        { label: 'North Star Panel', path: 'src/components/virtualOffice/NorthStarPanel.tsx' },
      ],
    },
    {
      id: 'coll-standup-config',
      name: 'standup-config',
      purpose: 'Telemetry schedule configuration and participant controls.',
      writtenBy: 'Standup config panel',
      readBy: 'Telemetry scripts',
      criticalFields: ['enabled', 'intervalMinutes', 'agents', 'protocol'],
      sourceRefs: [
        { label: 'Standup Config Panel', path: 'src/components/virtualOffice/StandupConfigPanel.tsx' },
        { label: 'Heartbeat Tab', path: 'src/components/admin/HeartbeatProtocolTab.tsx' },
      ],
    },
    {
      id: 'coll-mental-notes',
      name: 'mental-notes',
      purpose: 'PulseCheck concern tracking with severity and status evolution.',
      writtenBy: 'PulseCheck conversation analysis and user edits',
      readBy: 'PulseCheck profile and coach views',
      criticalFields: ['category', 'severity', 'status', 'lastDiscussed'],
      sourceRefs: [
        { label: 'PulseCheck Guide', path: '../iOS/docs/pulsecheck-development-guide.md' },
        { label: 'Mental Notes UI', path: '../iOS/PulseCheck/PulseCheck/Views/Chat/MentalNotesBar.swift' },
      ],
    },
  ],
  integrations: [
    {
      id: 'int-stripe',
      name: 'Stripe',
      purpose: 'Web checkout, connected accounts, unified payouts, and monthly statement generation.',
      owner: 'Monetization Team',
      credentialSource: 'Netlify environment variables',
      products: ['QuickLifts Web', 'Coach Platform'],
      status: 'active',
      sourceRefs: [
        { label: 'Stripe Connect System', path: 'docs/stripe-connect-system.md' },
        { label: 'Subscription System Doc', path: 'docs/subscription-system.md' },
        { label: 'Create Connected Account', path: 'netlify/functions/create-connected-account.js' },
        { label: 'Get Monthly Statement', path: 'netlify/functions/get-monthly-statement.js' },
      ],
    },
    {
      id: 'int-revenuecat',
      name: 'RevenueCat',
      purpose: 'Mobile entitlement lifecycle synchronization across iOS and Android.',
      owner: 'Monetization Team',
      credentialSource: 'Mobile app config + backend sync credentials',
      products: ['QuickLifts iOS', 'Pulse Android', 'PulseCheck iOS'],
      status: 'active',
      sourceRefs: [
        { label: 'Subscription System Doc', path: 'docs/subscription-system.md' },
        { label: 'Pulse Android README', path: '../Pulse-Android/README.md' },
      ],
    },
    {
      id: 'int-brevo',
      name: 'Brevo',
      purpose: 'Email lifecycle sequences, waitlists, and growth communications.',
      owner: 'Growth Ops',
      credentialSource: 'Netlify environment variables',
      products: ['QuickLifts Web'],
      status: 'active',
      sourceRefs: [
        { label: 'Brevo Notes', path: 'docs/Brevo implementation do.md' },
        { label: 'Email Sequences Admin', path: 'src/pages/admin/emailSequences.tsx' },
      ],
    },
    {
      id: 'int-instantly',
      name: 'Instantly',
      purpose: 'Outbound prospecting automation and sequence execution.',
      owner: 'Growth Ops',
      credentialSource: 'Ops-managed API credentials',
      products: ['QuickLifts Web'],
      status: 'active',
      sourceRefs: [
        { label: 'Creator Prospects', path: 'src/pages/admin/creatorProspects.tsx' },
        { label: 'University Prospects', path: 'src/pages/admin/universityProspects.tsx' },
      ],
    },
    {
      id: 'int-openai',
      name: 'OpenAI',
      purpose: 'Generation and analysis across round building, prospect extraction, and agent workflows.',
      owner: 'AI Systems',
      credentialSource: 'Server-side env vars and runner environment',
      products: ['QuickLifts iOS', 'QuickLifts Web', 'PulseCheck iOS', 'Agent Runner'],
      status: 'active',
      sourceRefs: [
        { label: 'Extract Creator Prospects API', path: 'src/pages/api/admin/extract-creator-prospects.ts' },
        { label: 'Agent Runner', path: 'scripts/agentRunner.js' },
      ],
    },
    {
      id: 'int-healthkit',
      name: 'HealthKit',
      purpose: 'Apple ecosystem health and activity context ingestion.',
      owner: 'iOS Squad',
      credentialSource: 'App entitlements and runtime permissions',
      products: ['QuickLifts iOS', 'PulseCheck iOS'],
      status: 'active',
      sourceRefs: [
        { label: 'Shared Services Guide', path: '../iOS/docs/shared-services-and-integration.md' },
        { label: 'HealthKit Permissions Modal', path: '../iOS/QuickLifts/QuickLifts/View/Components/HealthKitPermissionsModalView.swift' },
      ],
    },
    {
      id: 'int-health-connect',
      name: 'Health Connect',
      purpose: 'Android health data integration for readiness and context.',
      owner: 'Android Squad',
      credentialSource: 'Android runtime permissions and app config',
      products: ['Pulse Android'],
      status: 'beta',
      sourceRefs: [
        { label: 'Health Connect Capture', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/health/HealthConnectCaptureScreen.kt' },
        { label: 'Android README', path: '../Pulse-Android/README.md' },
      ],
    },
  ],
  flows: endToEndFlows,
  ownershipMatrix: [
    {
      domain: 'QuickLifts iOS Core Product',
      primaryOwner: 'iOS Squad',
      backupOwner: 'Platform',
      releaseCadence: 'Weekly TestFlight / staged prod releases',
      runbookPath: '../iOS/docs/pulse-app-guide.md',
    },
    {
      domain: 'Pulse Android Core Product',
      primaryOwner: 'Android Squad',
      backupOwner: 'Platform',
      releaseCadence: 'Internal QA cycles + staged prod release',
      runbookPath: '../Pulse-Android/docs/RELEASE_CHECKLIST.md',
    },
    {
      domain: 'PulseCheck iOS',
      primaryOwner: 'PulseCheck Team',
      backupOwner: 'Mental Performance Systems',
      releaseCadence: 'Beta iteration cadence',
      runbookPath: '../iOS/docs/pulsecheck-development-guide.md',
    },
    {
      domain: 'QuickLifts Web Public + Admin',
      primaryOwner: 'Web Platform',
      backupOwner: 'Platform Ops',
      releaseCadence: 'Continuous deploy from main',
      runbookPath: 'docs/CODEBASE_MAP.md',
    },
    {
      domain: 'Agent Infrastructure',
      primaryOwner: 'Agent Infra Team',
      backupOwner: 'Platform Ops',
      releaseCadence: 'Continuous script/runtime updates',
      runbookPath: 'docs/AGENT_ONBOARDING.md',
    },
    {
      domain: 'Monetization Stack',
      primaryOwner: 'Monetization Team',
      backupOwner: 'Platform Ops',
      releaseCadence: 'Event-driven with scheduled reconciliation jobs',
      runbookPath: 'docs/subscription-system.md',
    },
  ],
  risksAndGaps: [
    {
      id: 'risk-schema-drift',
      title: 'Cross-client schema drift risk',
      severity: 'high',
      impact: 'Breaking behavior across iOS/Android/web when field semantics diverge.',
      mitigation: 'Enforce Firestore contract updates and cross-platform release checklists before launches.',
      owner: 'Platform',
    },
    {
      id: 'risk-agent-observability',
      title: 'Agent runtime observability fragmentation',
      severity: 'medium',
      impact: 'Operators can miss root causes when failures split across runner logs and timeline entries.',
      mitigation: 'Standardize incident annotations and link beats to source task IDs in every failure path.',
      owner: 'Agent Infra',
    },
    {
      id: 'risk-subscription-reconciliation',
      title: 'Entitlement reconciliation lag',
      severity: 'medium',
      impact: 'Paid users may see temporary access inconsistencies across web/mobile surfaces.',
      mitigation: 'Tighten webhook retry visibility and expose reconciliation status in admin subscription tools.',
      owner: 'Monetization Team',
    },
    {
      id: 'risk-payout-cadence-assumption',
      title: 'Payout cadence assumption drift',
      severity: 'medium',
      impact:
        'Teams can assume a fixed first-of-month creator payout automation while account-level Stripe payout schedules may differ.',
      mitigation:
        'Document payout schedule source of truth in Stripe account settings and keep handbook payout notes aligned with connected-account configuration.',
      owner: 'Monetization Team',
    },
    {
      id: 'risk-doc-staleness',
      title: 'Handbook staleness after rapid releases',
      severity: 'medium',
      impact: 'Exec and builder decisions made on stale ownership or flow assumptions.',
      mitigation: 'Run validation script in release checklist and update handbook manifest in same PR as major changes.',
      owner: 'Platform Ops',
    },
  ],
  glossary: [
    {
      term: 'Round',
      definition: 'Structured challenge window with assigned workouts, participant scoring, and leaderboard progression.',
    },
    {
      term: 'Capsule',
      definition: 'Atomic unit of agent work represented as a Kanban task with explicit north-star alignment.',
    },
    {
      term: 'Telemetry Check',
      definition: 'Automated group coordination cycle where agents report status and receive new assignments.',
    },
    {
      term: 'Heartbeat Feed',
      definition: 'Realtime progress event stream stored in progress-timeline and surfaced in Virtual Office.',
    },
    {
      term: 'North Star',
      definition: 'Current strategic objective set in company-config used to prioritize agent and operations work.',
    },
    {
      term: 'Architect (Hunter World)',
      definition: 'Creator role framing in Hunter World where creators build challenge experiences for users.',
    },
    {
      term: 'Feature Inventory',
      definition: 'Per-product table of capabilities including dependencies, data paths, ownership, and status.',
    },
  ],
};
