import type { SystemOverviewManifest } from './schema';
import { endToEndFlows } from './flows';
import { quickliftsIosHandbook } from './products/quicklifts-ios';
import { pulseAndroidHandbook } from './products/pulse-android';
import { pulseCheckIosHandbook } from './products/pulsecheck-ios';
import { quickliftsWebHandbook } from './products/quicklifts-web';

export const systemOverviewManifest: SystemOverviewManifest = {
  title: 'System Overview Handbook',
  subtitle:
    'Document-first source of truth for Pulse architecture, products, data flows, ownership, and operational dependencies.',
  lastUpdated: '2026-04-08',
  sections: [
    { id: 'executive-summary', label: 'Executive Summary', description: 'Scope, mission, and latest changes.' },
    { id: 'ecosystem-map', label: 'Ecosystem Map', description: 'Layered map of products, backend, integrations, and agents.' },
    { id: 'product-handbooks', label: 'Product Handbooks', description: 'Feature-by-feature inventory for each product surface.' },
    { id: 'quicklifts-profile-health-system', label: 'QuickLifts Profile Health', description: 'Parent artifact for the story-led QuickLifts profile health surface and the shared snapshot contract underneath it.' },
    { id: 'quicklifts-profile-health-story-spec', label: 'Profile Health Story Spec', description: 'Product and UX contract for integrating Health Data Stories into the QuickLifts profile.', parentSectionId: 'quicklifts-profile-health-system' },
    { id: 'quicklifts-profile-health-snapshot-contract', label: 'Profile Health Snapshot Contract', description: 'Runtime contract for the versioned ProfileHealthSnapshot read model, freshness rules, invalidation, and modal alignment.', parentSectionId: 'quicklifts-profile-health-system' },
    { id: 'quicklifts-profile-health-energy-merge-spec', label: 'Enhanced Energy Merge Spec', description: 'Canonical calories-out resolution contract for Apple Health, QuickLifts-native workouts, manual corrections, estimators, and Oura validation.', parentSectionId: 'quicklifts-profile-health-system' },
    { id: 'pulse-club-activation-architecture', label: 'Club Activation Architecture', description: 'Generic creator-club operating model for onboarding, introductions, and member pairing.' },
    { id: 'smart-routes-v1-architecture', label: 'Smart Routes v1 Architecture', description: 'First-pass routing recommendation stack, ownership boundaries, API contract, and AI role for Pulse Community.' },
    { id: 'shared-link-preview-strategy', label: 'Shared Link Preview Strategy', description: 'Fallback metadata, branded default image, and crawler-safe preview rules for shared Pulse pages.' },
    { id: 'notification-systems-architecture', label: 'Notification Systems', description: 'Cross-product notification architecture covering Fit With Pulse, Pulse Check, token ownership, senders, sequences, and operational debugging.' },
    { id: 'backend-data', label: 'Backend and Data', description: 'Core services and canonical data collections.' },
    { id: 'infrastructure-secrets-stack', label: 'Infrastructure & Secrets Stack', description: 'Operational relationship between Netlify, Firebase, Google Cloud, Workspace, and secret storage policy.' },
    { id: 'firebase-admin-credential-architecture', label: 'Firebase Admin Credential Architecture', description: 'Unified server credential model for Next API routes and Netlify functions, including the canonical env contract, runtime adapters, and phased implementation plan.', parentSectionId: 'infrastructure-secrets-stack' },
    { id: 'firestore-index-registry', label: 'Firestore Index Registry', description: 'Shared source-of-truth registry and operating discipline for Firestore indexes across development and production.' },
    { id: 'integrations', label: 'Integrations', description: 'External systems, ownership, and credential sources.' },
    { id: 'end-to-end-flows', label: 'End-to-End Flows', description: 'Cross-product flows from trigger to failure points.' },
    { id: 'ownership-release-matrix', label: 'Ownership Matrix', description: 'Operational ownership and release cadence.' },
    { id: 'agent-infrastructure-handbook', label: 'Agent Infrastructure Handbook', description: 'Heartbeat protocol and operator playbook.' },
    { id: 'agent-outcome-rubric-spec', label: 'Outcome Rubric v1', description: 'Frozen outcome-first runtime contract for proof, scoring, lifecycle, and business movement.' },
    { id: 'hunter-world-handbook', label: 'Hunter World Handbook', description: 'Leveling, class mechanics, and creator ecosystem chapter.' },
    { id: 'risks-gaps', label: 'Risks and Gaps', description: 'Current known risk posture and mitigations.' },
    { id: 'glossary', label: 'Glossary', description: 'Shared language for cross-functional alignment.' },
    { id: 'simulation-taxonomy', label: 'Simulation Taxonomy', description: 'PulseCheck mental performance pillars, skills, sims, and scoring.' },
    { id: 'sim-family-tree', label: 'Sim Family Tree', description: 'Locked families, candidates, variants, and hybrid modules.' },
    { id: 'promotion-protocol', label: 'Promotion Protocol', description: 'How new sim families are proposed, evaluated, and promoted.' },
    { id: 'sim-spec-standards', label: 'Spec Standards', description: 'Shared measurement precision, fail conditions, trial rules, and validation roadmap.' },
    { id: 'variant-registry', label: 'Variant Registry', description: 'Exhaustive inventory of all named variants with spec status tracking.' },
    { id: 'protocol-registry', label: 'Protocol Registry', description: 'Sibling registry for bounded Nora protocol inventory, publish posture, and planning eligibility.' },
    { id: 'pulsecheck-protocol-governance-spec', label: 'Protocol System', description: 'Parent artifact for PulseCheck protocol governance, authoring, responsiveness, launch controls, evidence, and live operations.' },
    { id: 'pulsecheck-protocol-authoring-workflow', label: 'Protocol Authoring Workflow', description: 'Design brief for the protocol workspace, publish controls, change classes, and revision model.', parentSectionId: 'pulsecheck-protocol-governance-spec' },
    { id: 'pulsecheck-protocol-responsiveness-profile-spec', label: 'Protocol Responsiveness Profile Spec', description: 'Athlete-level protocol response memory, confidence interaction rules, decay logic, and planner weighting guidance.', parentSectionId: 'pulsecheck-protocol-governance-spec' },
    { id: 'pulsecheck-protocol-responsiveness-inspector', label: 'Protocol Responsiveness Inspector', description: 'Read-only operator surface for browsing athlete protocol responsiveness profiles without entering coach assignment review.', parentSectionId: 'pulsecheck-protocol-governance-spec' },
    { id: 'pulsecheck-protocol-launch-readiness', label: 'Protocol Launch Readiness', description: 'Go / no-go launch gates for registry integrity, planner enforcement, evidence health, ops control, and QA sign-off.', parentSectionId: 'pulsecheck-protocol-governance-spec' },
    { id: 'pulsecheck-protocol-planner-policy-enforcement', label: 'Planner Policy Enforcement', description: 'Protocol-specific planner eligibility, filtering order, validator rules, and failure-handling requirements.', parentSectionId: 'pulsecheck-protocol-governance-spec' },
    { id: 'pulsecheck-protocol-practice-conversation-spec', label: 'Protocol Practice Conversation Spec', description: 'Teach -> practice -> evaluate runtime contract for Nora-guided protocol application, response capture, and end-of-session scoring.', parentSectionId: 'pulsecheck-protocol-governance-spec' },
    { id: 'pulsecheck-protocol-evidence-dashboard', label: 'Protocol Evidence Dashboard', description: 'Monitoring and review dashboard spec for protocol effectiveness, negative-response posture, and governance alerts.', parentSectionId: 'pulsecheck-protocol-governance-spec' },
    { id: 'pulsecheck-protocol-revision-audit-trace', label: 'Protocol Revision & Audit Trace', description: 'Traceability spec for published protocol lineage, planner decisions, assignment provenance, and evidence linkage.', parentSectionId: 'pulsecheck-protocol-governance-spec' },
    { id: 'pulsecheck-protocol-ops-runbook', label: 'Protocol Ops Runbook', description: 'Operational containment, triage, ownership, and recovery playbook for live protocol issues.', parentSectionId: 'pulsecheck-protocol-governance-spec' },
    { id: 'pulsecheck-protocol-launch-qa-matrix', label: 'Protocol Launch QA Matrix', description: 'Launch-blocking scenario matrix for registry integrity, policy filtering, responsiveness, evidence refresh, and coach audit visibility.', parentSectionId: 'pulsecheck-protocol-governance-spec' },
    { id: 'sim-family-specs', label: 'Sim FamilySpecs', description: 'Complete specifications for each simulation family.' },
    { id: 'athlete-journey', label: 'Athlete Journey', description: 'Recommended entry, progression, and system flow for athlete adoption.' },
    { id: 'coach-journey', label: 'Coach Journey', description: 'Recommended entry, setup, and daily operating flow for coaches using Pulse Check.' },
    { id: 'pulsecheck-runtime-architecture', label: 'Runtime Stack', description: 'Parent artifact for the PulseCheck runtime operating model, state logic, assignment rules, escalation bridges, and QA posture.' },
    { id: 'pulsecheck-state-signal-layer', label: 'State Signal Layer', description: 'Operational state inference, confidence bands, freshness rules, and routing outputs for Nora.', parentSectionId: 'pulsecheck-runtime-architecture' },
    { id: 'pulsecheck-checkin-signal-layer-integration-spec', label: 'Check-In Integration Spec', description: 'AI-native contract between readiness check-in, enriched state snapshots, bounded assignment candidate sets, Nora chat context, and daily task materialization.', parentSectionId: 'pulsecheck-runtime-architecture' },
    { id: 'pulsecheck-daily-task-training-plan-alignment-spec', label: 'Daily Task + Training Plan Alignment', description: 'Runtime surface-coherence contract for DailyTask, TrainingPlan, PlanStep, date-bound execution truth, and athlete-facing consistency across Home, Mental Training, and Nora chat.', parentSectionId: 'pulsecheck-runtime-architecture' },
    { id: 'pulsecheck-training-plan-authoring-spec', label: 'Training Plan Authoring Spec', description: 'Runtime contract for how Nora authors longer-horizon mental-training blocks, chooses plan types, persists provenance, and feeds daily materialization.', parentSectionId: 'pulsecheck-runtime-architecture' },
    { id: 'pulsecheck-health-chat-architecture', label: 'Health Context Pipeline', description: 'Parent artifact for how PulseCheck should ingest, normalize, and use shared QuickLifts, HealthKit, Apple Watch, Oura, and self-reported athlete context.' },
    { id: 'pulsecheck-athlete-health-context-snapshot-spec', label: 'Athlete Context Snapshot Spec', description: 'Canonical contract for the normalized AthleteHealthContextSnapshot that all ingestion lanes should target before native HealthKit or Oura pipes are built.', parentSectionId: 'pulsecheck-health-chat-architecture' },
    { id: 'pulsecheck-health-context-source-record-spec', label: 'Health Context Source Record Spec', description: 'Canonical adapter-target contract for the normalized source-record layer that feeds athlete-context snapshot assembly.', parentSectionId: 'pulsecheck-health-chat-architecture' },
    { id: 'pulsecheck-health-context-snapshot-assembler-spec', label: 'Health Context Snapshot Assembler Spec', description: 'Canonical merge-engine contract for how normalized health-context source records become daily and rolling athlete-context snapshots.', parentSectionId: 'pulsecheck-health-chat-architecture' },
    { id: 'pulsecheck-health-context-persistence-storage-spec', label: 'Health Context Persistence & Storage Spec', description: 'Canonical storage-model spec for where source records, snapshots, traces, source status, and migration bridge data should live.', parentSectionId: 'pulsecheck-health-chat-architecture' },
    { id: 'pulsecheck-health-context-operational-orchestration-spec', label: 'Health Context Operational Orchestration Spec', description: 'Canonical runtime and job-orchestration spec for connector lifecycle, sync scheduling, backfill, retry posture, and stale/error handling.', parentSectionId: 'pulsecheck-health-chat-architecture' },
    { id: 'pulsecheck-health-context-implementation-rollout-plan', label: 'Health Context Implementation Rollout Plan', description: 'Execution-layer milestone plan for MVP, migration, ownership, cutover, and native-source expansion across the health-context system.', parentSectionId: 'pulsecheck-health-chat-architecture' },
    { id: 'pulsecheck-health-context-operator-runbook', label: 'Health Context Operator Runbook', description: 'Internal validation and migration runbook for canonical collection population, parity checks, backfill, harness verification, and rollout readiness.', parentSectionId: 'pulsecheck-health-chat-architecture' },
    { id: 'pulsecheck-health-context-definition-of-done', label: 'Health Context Definition Of Done', description: 'Close-out artifact defining what is truly required versus optional before the health-context feature can be considered complete.', parentSectionId: 'pulsecheck-health-chat-architecture' },
    { id: 'pulsecheck-health-context-engineering-task-breakdown', label: 'Health Context Engineering Task Breakdown', description: 'Execution-facing milestone task breakdown for platform, QuickLifts, PulseCheck, integrations, ops, and QA workstreams.', parentSectionId: 'pulsecheck-health-chat-architecture' },
    { id: 'pulsecheck-health-context-firestore-schema-index-spec', label: 'Health Context Firestore Schema & Index Spec', description: 'Implementation-facing Firestore collection, document, query, and composite-index spec for the health-context system.', parentSectionId: 'pulsecheck-health-chat-architecture' },
    { id: 'pulsecheck-physiology-cognition-correlation-engine', label: 'Physiology-Cognition Correlation Engine', description: 'Parent artifact for learning athlete-specific mind-body patterns from normalized physiology plus PulseCheck simulation evidence.', parentSectionId: 'pulsecheck-health-chat-architecture' },
    { id: 'pulsecheck-correlation-engine-contract-lock', label: 'Contract Lock & Exit Criteria', description: 'Milestone 0 contract freeze for baseline artifacts, naming, confidence tiers, messaging boundaries, and implementation exit criteria.', parentSectionId: 'pulsecheck-physiology-cognition-correlation-engine' },
    { id: 'pulsecheck-correlation-data-model-spec', label: 'Correlation Data Model Spec', description: 'Implementation-facing schema for Correlation Evidence Record, Athlete Pattern Model, Recommendation Projection, and Assessment Context Flag.', parentSectionId: 'pulsecheck-physiology-cognition-correlation-engine' },
    { id: 'pulsecheck-correlation-engine-engineering-task-breakdown', label: 'Correlation Engine Engineering Task Breakdown', description: 'End-to-end engineering workstream and milestone breakdown from schema lock through production-ready launch for the correlation engine.', parentSectionId: 'pulsecheck-physiology-cognition-correlation-engine' },
    { id: 'pulsecheck-correlation-engine-pilot-dashboard', label: 'Correlation Engine Pilot Dashboard', description: 'Pilot-native monitoring surface for active pilots, rooted in Pilot and PilotEnrollment rather than whole-system analytics.', parentSectionId: 'pulsecheck-physiology-cognition-correlation-engine' },
    { id: 'pulsecheck-correlation-engine-pilot-dashboard-addendum', label: 'Pilot Dashboard Addendum', description: 'Pilot KPI glossary and reporting-separation rules for the pilot dashboard.', parentSectionId: 'pulsecheck-physiology-cognition-correlation-engine' },
    { id: 'pulsecheck-pilot-outcome-metrics-contract', label: 'Pilot Outcome Metrics Contract', description: 'Canonical contract for enrollment, adherence, mental performance improvement, escalations, speed to care, trust, and NPS across PulseCheck pilots.' },
    { id: 'pulsecheck-correlation-engine-pilot-ops-runbook', label: 'Pilot Ops Runbook', description: 'Operational ownership, cadence, escalation, and queue guidance for active pilot monitoring.', parentSectionId: 'pulsecheck-physiology-cognition-correlation-engine' },
    { id: 'pulsecheck-correlation-engine-pilot-research-readout', label: 'Pilot Research Readout Implementation Spec', description: 'AI-assisted, evidence-bounded interpretation-layer spec for one pilot’s governed dashboard data, including gating, output schema, and review workflow.', parentSectionId: 'pulsecheck-physiology-cognition-correlation-engine' },
    { id: 'pulsecheck-oura-integration-strategy', label: 'Oura Integration Strategy', description: 'Direct Oura OAuth/API lane, HealthKit-derived fallback lane, source-record mapping, merge precedence, and rollout recommendation for PulseCheck.', parentSectionId: 'pulsecheck-device-integration-strategy' },
    { id: 'pulsecheck-oura-cognitive-correlation-spec', label: 'Oura Cognitive Correlation Spec', description: 'First source-specific child spec for feeding Oura physiology into the broader Physiology-Cognition Correlation Engine.', parentSectionId: 'pulsecheck-physiology-cognition-correlation-engine' },
    { id: 'pulsecheck-device-integration-strategy', label: 'Device & Wearable Integrations', description: 'Parent artifact for wearable strategy, partnership prioritization, and source-lane recommendations across device ecosystems.' },
    { id: 'pulsecheck-device-integration-partnership-matrix', label: 'Device Integration Partnership Matrix', description: 'Partnership shape matrix for wearables, platforms, and enterprise systems with scale upside and rollout sequencing.', parentSectionId: 'pulsecheck-device-integration-strategy' },
    { id: 'pulsecheck-school-wearable-bundle-plan', label: 'School Wearable Bundle Plan', description: 'School contract bundle plan for a Pulse-branded screenless band, including OEM research, pilot posture, and current FDA, Bluetooth, and FCC guidance.', parentSectionId: 'pulsecheck-device-integration-strategy' },
    { id: 'pulsecheck-patent-eligibility-audit', label: 'Patent Eligibility Audit', description: 'Internal screening pass for utility-patent, design-patent, and non-patent candidates across the Pulse system.' },
    { id: 'pulsecheck-state-snapshot-freshness-policy', label: 'Snapshot Freshness Policy', description: 'Shared recency, validity, and decay rules for state snapshots used across runtime consumers.', parentSectionId: 'pulsecheck-runtime-architecture' },
    { id: 'pulsecheck-performance-state-flag-definitions', label: 'Performance-State Flags', description: 'Family-level definitions for translating acute sim behavior into state evidence.', parentSectionId: 'pulsecheck-runtime-architecture' },
    { id: 'pulsecheck-nora-assignment-rules', label: 'Nora Assignment Rules', description: 'Decision rules for Protocol, Sim, Trial, defer, and safety-aware assignment behavior.', parentSectionId: 'pulsecheck-runtime-architecture' },
    { id: 'pulsecheck-nora-qa-edge-case-matrix', label: 'Nora QA Matrix', description: 'Conflict, override, and edge-case scenarios for testing runtime behavior before pilot.', parentSectionId: 'pulsecheck-runtime-architecture' },
    { id: 'pulsecheck-state-escalation-orchestration', label: 'State & Escalation Orchestration', description: 'Shared upstream state perception with separate performance, support, and safety lanes.', parentSectionId: 'pulsecheck-runtime-architecture' },
    { id: 'pulsecheck-escalation-integration-spec', label: 'Escalation Integration Spec', description: 'Execution-layer bridge between state snapshots and the escalation workflow.', parentSectionId: 'pulsecheck-runtime-architecture' },
    { id: 'pulsecheck-member-onboarding-guide', label: 'Onboarding & Access', description: 'Parent artifact for member onboarding, team/pilot entry architecture, and PulseCheck permissions posture.' },
    { id: 'pulsecheck-team-pilot-cohort-onboarding-architecture', label: 'Team & Pilot Onboarding', description: 'How organizations, teams, pilots, cohorts, clinicians, and enrollments enter the system.', parentSectionId: 'pulsecheck-member-onboarding-guide' },
    { id: 'pulsecheck-permissions-visibility-model', label: 'Permissions & Visibility', description: 'Role-based access, invite-linked permissions, and minimum-necessary visibility rules.' },
    { id: 'pulsecheck-coach-dashboard-information-architecture', label: 'Coach Dashboard IA', description: 'Coach-facing information hierarchy, workflows, and privacy boundaries for roster visibility.' },
    { id: 'pulsecheck-profile-architecture', label: 'Profile System', description: 'Parent artifact for PulseCheck profile information architecture, milestone snapshots, and export contract rules.' },
    { id: 'pulsecheck-profile-snapshot-export-spec', label: 'Profile Snapshot & Export Spec', description: 'Canonical snapshot storage, idempotent write protocol, revision history, and canonical-first research export contract.', parentSectionId: 'pulsecheck-profile-architecture' },
    { id: 'pulsecheck-vision-pro-immersive-tests', label: 'Vision Pro - Immersive Tests', description: 'Spec stack for the football Vision Pro package, including immersive trial positioning, environment design, event schema, protocol rules, and pilot operations.' },
    { id: 'system-design-language', label: 'System Design & Language', description: 'Voice, copy posture, and human-centered UI rules for how Pulse speaks to users across products.' },
    { id: 'auntedna-integration-strategy', label: 'Integration Strategy', description: 'API layer, webhook contract, profile mirror model, and MCP positioning for the AuntEdna clinical bridge.' },
    { id: 'auntedna-pilot-authorization-memo', label: 'Pilot Authorization Memo', description: 'Pre-contract, department-level memo template for a voluntary athletics pilot run by PulseCheck in partnership with AuntEdna.' },
    { id: 'auntedna-exhibit-a-data-architecture', label: 'Exhibit A - Data Architecture', description: 'Agreement-facing system-of-record boundary, minimum-necessary payload, limited reverse operational-status flow, and PHI handling rules for the AuntEdna bridge.' },
    { id: 'auntedna-exhibit-b-performance-standards', label: 'Exhibit B - Performance Standards', description: 'Agreement-facing Tier-based response standards, PulseCheck uptime and handoff obligations, reporting cadence, and remediation mechanics for the AuntEdna partnership.' },
    { id: 'system-test-coverage', label: 'System Test Coverage', description: 'Handbook audit of full-system harness completeness across web, backend, mobile, and operational surfaces. This is a system-confidence estimate, not line coverage.' },
    { id: 'playwright-testing-strategy', label: 'Testing Strategy', description: 'Playwright harness model, suite inventory, run commands, and PulseCheck UI regression coverage.' },
    { id: 'android-testing-strategy', label: 'Android Testing Strategy', description: 'Native Android instrumentation baseline, dev-Firebase E2E contract, and namespaced cleanup policy.' },
    { id: 'xcuitest-testing-strategy', label: 'XCUITest Strategy', description: 'Deterministic iOS launch model, native club activation suite inventory, and accessibility-id contract.' },
    { id: 'workout-share-cards', label: 'Workout Share Cards', description: 'Transparent PNG share card system for Run, Bike, Lift, Stretch, and Fat Burn categories — PHPhotoLibrary save path, story card layouts, and color-coded category branding.' },
  ],
  executiveSummary: {
    mission:
      'Maintain a complete, implementation-grounded map of the Pulse ecosystem so product, engineering, and operations can execute from one shared system truth.',
    audience:
      'Exec + Internal Mixed: quick strategic readability with deep technical drill-down for builders.',
    whatChangedRecently: [
      'Froze the Outcome Rubric v1 spec and added it to the Agent Swarm handbook so the autonomous mission system now has a locked runtime contract for outcome-first execution.',
      'Added the Enhanced Energy Merge Spec artifact to the QuickLifts profile-health handbook stack, locking `ResolvedEnergySnapshot`, source precedence, segment provenance, coverage, acceptance gates, and Home/Profile migration rules for calories out.',
      'Added the QuickLifts Profile Health handbook artifact, pairing the story-led profile product spec with the ProfileHealthSnapshot runtime contract so profile hero, proof cards, and Health Data Story drill-down share one documented system truth.',
      'Added the Daily Task + Training Plan Alignment Spec to the PulseCheck runtime stack, locking the canonical DailyTask / TrainingPlan / PlanStep model, lifecycle rules, date-boundary behavior, event contract, and surface-coherence requirements across Home, Mental Training, and Nora chat.',
      'Added the Training Plan Authoring Spec to the PulseCheck runtime stack, defining how Nora authors longer-horizon mental-training blocks, chooses plan types and archetypes, persists provenance, and advances plan pointers over time.',
      'Added a pilot-scoped Correlation Engine dashboard stack, including the pilot dashboard, KPI addendum, and pilot ops runbook, and clarified that active-pilot monitoring is rooted in Pilot and PilotEnrollment rather than whole-team analytics.',
      'Added the Pilot Outcome Metrics Contract artifact to the Correlation Engine pilot stack, locking the implementation-grounded definitions for enrollment, adherence, mental performance improvement, escalations, speed to care, trust, and NPS plus the default ownership rules needed to build the outcome system cleanly.',
      'Added a Pilot Research Readout Implementation Spec to the Correlation Engine pilot stack, defining the AI-assisted interpretation tab, readiness gates, claim-discipline rules, frozen evidence frame, and human-review workflow for pilot-level research summaries.',
      'Reorganized the PulseCheck handbook around artifact-level libraries so Health Context Pipeline, Protocol System, Runtime Stack, Profile System, Onboarding & Access, and Device & Wearable Integrations now hold their related docs internally instead of exposing long sibling runs in the sidebar.',
      'Added a Protocol Practice Conversation Spec artifact to the Protocol System chapter so protocol execution now has an explicit teach -> practice -> evaluate runtime target instead of ending at narrated instruction.',
      'Extended PulseCheck assignment events so started/completed/deferred/overridden now refresh the athlete protocol responsiveness profile, and persisted planner-audit traces on Nora daily assignments so pilot review can see why a bounded candidate won.',
      'Added a protocol launch-spec stack to the handbook, including launch readiness, planner policy enforcement, evidence dashboard, revision/audit trace, ops runbook, and launch QA matrix artifacts so the protocol system now has an explicit path from v1 implementation to launch sign-off.',
      'Fed athlete-level protocol responsiveness into the shared Nora planner, so bounded protocol candidates are now ranked by current state plus learned family/variant response posture instead of responsiveness living only in coach review.',
      'Added a first-pass athlete-level protocol responsiveness service and coach-visible explanation traces, so Mental Training review now shows family and variant response posture, confidence/freshness, and runtime-derived evidence instead of treating responsiveness as spec-only.',
      'Connected protocol evidence panels to live runtime behavior so the registry now derives first-pass family, variant, and runtime evidence from protocol assignments and assignment events instead of relying on manual admin-entered counters.',
      'Hardened the Protocol Registry workspace with explicit family review gates, variant approval posture, runtime publish gating, and first-pass evidence/responsiveness panels so governance is starting to live in the product instead of only in docs.',
      'Upgraded the Protocol Registry into a true three-layer workspace, with separate protocol family, protocol variant, and published runtime objects plus linked history so protocols now follow the same upstream object discipline as the sim system.',
      'Added a Protocol Responsiveness Profile Spec artifact to define athlete-level protocol response memory, confidence interaction with the current state snapshot, and why sequencing/bundles are explicitly deferred to v2.',
      'Added Protocol Governance Spec and Protocol Authoring Workflow artifacts to the PulseCheck handbook, defining how protocols should be discovered, structured, reviewed, published, versioned, and eventually managed through a true authoring workspace.',
      'Added a sibling Protocol Registry handbook tab beside the Variant Registry so the Firestore-backed Nora protocol inventory is now visible as a first-class admin/runtime artifact instead of living only in service code.',
      'Moved PulseCheck protocols onto a sibling Firestore-backed protocol registry with a broader published inventory, so Nora now plans from published protocol records instead of an inline breathing-only list.',
      'Added an explicit temporary implementation-planning layer to the Vision Pro handbook and locked the Operator Companion Implementation Plan into that section so active build-order artifacts are visible before they are mature enough for permanent system-design status.',
      'Added same-day Nora assignment revision lineage so material re-plans now advance the live assignment revision, archive the prior mutable version into immutable history, and expose that lineage in the coach review surface.',
      'Added a Vision Pro Operator Companion Spec artifact to the handbook, defining the staff-led phone/control posture for first-time headset users and the narrow set of remote actions that improve comfort, clarity, and session integrity without creating a second gameplay surface.',
      'Expanded the coach-facing Nora assignment review surface in Mental Training so staff can inspect the current snapshot posture, latest chat-derived correction delta, planner notes, assignment-event timeline, and explicit before/after execution-truth diffs for coach overrides or deferrals.',
      'Extended Nora chat so pre-start state corrections can now re-run the shared bounded candidate-set planner and policy gate, allowing the mutable same-day assignment artifact to catch up to the refreshed snapshot instead of leaving chat and execution truth out of sync.',
      'Extended Nora chat so meaningful athlete messages now run through an AI-assisted chat-signal interpreter, persist structured `conversation-derived-signal-events`, refresh the shared current-day state snapshot, and give Nora that refreshed state before she answers.',
      'Extended the shared PulseCheck assignment-event contract so started, completed, deferred, and overridden events now refresh the current-day state snapshot automatically, closing the execution-to-signal half of the bidirectional runtime loop before the chat-derived correction path was added.',
      'Upgraded the PulseCheck Check-In Integration Spec, State Signal Layer, and Nora Assignment Rules artifacts to an AI-native planning model: raw signals feed AI enrichment, Nora plans from a bounded sim/protocol candidate set, and the handbook now reflects the initial live breathing-protocol registry plus the remaining protocol-expansion backlog.',
      'Added a Firestore Index Registry artifact that turns `firestore.indexes.json` into a visible handbook source of truth and locks the operating rule that every new index must update the shared registry and be brought to both dev and prod.',
      'Added the Infrastructure & Secrets Stack artifact documenting how Netlify, Firebase, Google Cloud Secret Manager, and Google Workspace divide responsibilities, including the Group Meet Google Calendar secret setup.',
      'Documented a separate guest Google Calendar OAuth import contract for Group Meet so invitees can import free/busy suggestions without reusing the admin final-event scheduling setup.',
      'Added the PulseCheck Device Integration Strategy artifact to the system overview, turning the device wishlist into a documented taxonomy with integration lanes, priorities, and rollout guidance.',
      'Added the PulseCheck Device Integration Partnership Matrix artifact to the system overview, showing which vendors are best suited to data access, platform compatibility, enterprise alliances, or brand-only partnerships.',
      'Added the PulseCheck School Wearable Bundle Plan artifact, locking the school-bundle recommendation for a Pulse-branded screenless band and recording the current OEM, FDA, Bluetooth, and FCC research needed before launch.',
      'Added the PulseCheck Patent Eligibility Audit artifact to the system overview, screening which parts of the system may be worth utility-patent, design-patent, or trade-secret treatment.',
      'Added a Reset Chamber scientific pruning contract to the Vision Pro handbook and Reset family page, clarifying that immersive motion should only stay when it supports pressure, urgency, consequence, or outcome readability.',
      'Added a Reset Chamber Polish Sprint 3 audit lens to the Vision Pro handbook and Reset family page so immersive polish is judged by manipulation strength, task readability, and measurement trust instead of spectacle alone.',
      'Added a current Reset Chamber keep / trim / cut audit to the Vision Pro handbook and Reset family page so Sprint 3 tuning stays anchored to experimental purpose rather than pure visual activity.',
      'Added the PulseCheck Check-In Integration Spec artifact covering how athlete readiness taps, shared state snapshots, Nora chat launch context, and daily assignment lifecycle events should connect into one bidirectional runtime contract.',
      'Added a read-only Protocol Responsiveness Inspector tab so operators can inspect athlete protocol memory directly from the handbook without going through coach assignment review.',
      'Added Attentional Lock as a new Tier 3 Exploratory concept in the Sim Family Tree, originating from the Vision Pro Reset trial design review. Logged Active Lock-In Reset as a named variant in the Reset family variant library with an exploratory candidate note.',
      'Added a Noise Gate Milestone 1 Plan artifact to the Vision Pro - Immersive Tests chapter, translating the Crowd Tunnel design brief into a concrete build contract for one complete playable loop with score and closeout.',
      'Added a Noise Gate Design Brief artifact inside the Vision Pro - Immersive Tests chapter, locking the design-first north star for Crowd Tunnel before more runtime work proceeds.',
      'Expanded the Vision Pro - Immersive Tests artifact with a dedicated RealityKit Implementation Guide explaining the exact gap between the current runtime and the football immersive spec, plus the build sequence required to make the headset experience truly immersive.',
      'Added Workout Share Cards artifact documenting the transparent PNG share card system (PHPhotoLibrary save path) and branded story card layouts for Run, Bike, Lift, Stretch, and Fat Burn categories with per-category color coding.',
      'Added the Vision Pro - Immersive Tests artifact under PulseCheck, grouping the five football pilot documents into one structured spec stack with internal doc toggles and implementation alignment notes.',
      'Logged the Vision UI Design Language artifact into the Vision Pro - Immersive Tests chapter so prompts and implementation work can reference the in-repo chromatic-glass, authority-level, and Level C HUD rules directly.',
      'Added the System Design & Language artifact establishing the cross-product voice, copy posture, and the anchor question “What is happening to me right now?” for human-centered UI reviews.',
      'Added the PulseCheck Profile Snapshot & Export Spec artifact covering canonical snapshot storage, deterministic write rules, Nora template validation, revision audit handling, and canonical-default export behavior.',
      'Added the PulseCheck Profile Architecture artifact covering the new profile information architecture, data model, milestone snapshots, research export defaults, and template-bound Nora explanation rules.',
      'Added the Android Testing Strategy artifact covering the current instrumentation baseline, the recommended dev-Firebase E2E harness, and the shared `e2e-android-*` cleanup model.',
      'Added the PulseCheck Member Onboarding Guide artifact covering the live athlete onboarding path from account creation through automatic baseline completion.',
      'Added the XCUITest Strategy artifact covering the deterministic mock-club launch path, current native club activation suite, and identifier contract for iOS automation.',
      'Refreshed the Club Activation Architecture artifact to reflect current web + iOS implementation, including native host config, intro composer modal, and bottom-clearance layout rules.',
      'Added the Shared Link Preview Strategy artifact covering crawler metadata fallbacks, protected-share guardrails, and the branded default-image recommendation.',
      'Added the Smart Routes v1 Architecture artifact covering provider boundaries, route scoring, Firestore objects, API contracts, and AI limits.',
      'Added the AuntEdna Integration Strategy artifact covering APIs, webhooks, MCP role, and the local clinician-profile mirror model.',
      'Added an AuntEdna Pilot Authorization Memo artifact to the handbook so athletics teams can export a polished pre-contract pilot memo with default PulseCheck and AuntEdna contacts and signature blocks.',
      'Added AuntEdna Exhibit A and Exhibit B artifacts to the handbook, locking the agreement-facing data boundary, limited operational mirror rules, Tier-based response standards, and post-receipt accountability model into the System Overview.',
      'Added the Playwright Testing Strategy artifact covering the harness, auth capture flow, commands, environment controls, and PulseCheck suite coverage.',
      'Added Pulse Community Club Activation Architecture artifact for generic creator-club onboarding, introductions, and pairing.',
      'Replaced tab-driven architecture page with a full handbook structure and anchored navigation.',
      'Added complete feature inventories for QuickLifts iOS, Pulse Android, PulseCheck iOS, and QuickLifts Web.',
      'Normalized backend/data/integration ownership into explicit matrix rows and release cadences.',
      'Mapped seven cross-product end-to-end flows with concrete failure points and collection touch paths.',
      'Added explicit creator engagement, creator score, wallet, payout, and statement lifecycle documentation.',
      'Maintained agent and Hunter World chapters directly inside the handbook information architecture.',
    ],
    highlights: [
      'Single-page handbook spanning consumer products, ops tooling, and autonomous agent infrastructure.',
      'Static typed content model in repo; no Firebase persistence required for handbook content updates.',
      'Dual-layer security model: admin role guard + page-level passcode gate.',
    ],
  },
  ecosystemMap: {
    nodes: [
      {
        id: 'quicklifts-ios',
        name: 'QuickLifts iOS',
        layer: 'surface',
        status: 'active',
        description: 'Flagship mobile product for workouts, rounds, and nutrition.',
        owner: 'iOS Squad',
        x: 14,
        y: 16,
      },
      {
        id: 'pulse-android',
        name: 'Pulse Android',
        layer: 'surface',
        status: 'active',
        description: 'Android native product for parity across workout and round flows.',
        owner: 'Android Squad',
        x: 32,
        y: 20,
      },
      {
        id: 'pulsecheck-ios',
        name: 'PulseCheck iOS',
        layer: 'surface',
        status: 'active',
        description: 'Mental-performance companion product and coach readiness surface.',
        owner: 'PulseCheck Team',
        x: 52,
        y: 16,
      },
      {
        id: 'quicklifts-web',
        name: 'QuickLifts Web',
        layer: 'surface',
        status: 'active',
        description: 'Growth, admin, creator, coach, and agent command surfaces.',
        owner: 'Web Platform',
        x: 74,
        y: 22,
      },
      {
        id: 'firebase-auth',
        name: 'Firebase Auth',
        layer: 'backend',
        status: 'active',
        description: 'Identity foundation across all clients.',
        owner: 'Platform',
        x: 18,
        y: 50,
      },
      {
        id: 'cloud-firestore',
        name: 'Cloud Firestore',
        layer: 'backend',
        status: 'active',
        description: 'Primary operational and product data store.',
        owner: 'Platform',
        x: 39,
        y: 56,
      },
      {
        id: 'firebase-storage',
        name: 'Firebase Storage',
        layer: 'backend',
        status: 'active',
        description: 'Media and document storage for app and operations.',
        owner: 'Platform',
        x: 59,
        y: 55,
      },
      {
        id: 'netlify-functions',
        name: 'Netlify Functions',
        layer: 'backend',
        status: 'active',
        description: 'Server-side jobs for billing, messaging, and automation.',
        owner: 'Web Platform',
        x: 80,
        y: 60,
      },
      {
        id: 'stripe',
        name: 'Stripe',
        layer: 'integration',
        status: 'active',
        description: 'Web billing, coach payouts, and connected account workflows.',
        owner: 'Monetization',
        x: 20,
        y: 82,
      },
      {
        id: 'revenuecat',
        name: 'RevenueCat',
        layer: 'integration',
        status: 'active',
        description: 'Mobile entitlement synchronization.',
        owner: 'Monetization',
        x: 38,
        y: 84,
      },
      {
        id: 'brevo',
        name: 'Brevo',
        layer: 'integration',
        status: 'active',
        description: 'Lifecycle email and waitlist automations.',
        owner: 'Growth Ops',
        x: 58,
        y: 83,
      },
      {
        id: 'instantly',
        name: 'Instantly',
        layer: 'integration',
        status: 'active',
        description: 'Outbound sequencing and prospecting flows.',
        owner: 'Growth Ops',
        x: 78,
        y: 82,
      },
      {
        id: 'agent-runner',
        name: 'Agent Runner',
        layer: 'agent',
        status: 'active',
        description: 'Long-running execution loop for autonomous capsule work.',
        owner: 'Agent Infra',
        x: 30,
        y: 34,
      },
      {
        id: 'virtual-office',
        name: 'Virtual Office',
        layer: 'agent',
        status: 'active',
        description: 'Operator surface for presence, timeline, and intervention.',
        owner: 'Agent Infra',
        x: 50,
        y: 33,
      },
      {
        id: 'telemetry-check',
        name: 'Telemetry Check',
        layer: 'agent',
        status: 'active',
        description: 'Hourly standup protocol creating capsules and meeting records.',
        owner: 'Agent Infra',
        x: 70,
        y: 35,
      },
    ],
    connections: [
      { from: 'quicklifts-ios', to: 'firebase-auth', type: 'auth' },
      { from: 'quicklifts-ios', to: 'cloud-firestore', type: 'data' },
      { from: 'pulse-android', to: 'firebase-auth', type: 'auth' },
      { from: 'pulse-android', to: 'cloud-firestore', type: 'data' },
      { from: 'pulsecheck-ios', to: 'firebase-auth', type: 'auth' },
      { from: 'pulsecheck-ios', to: 'cloud-firestore', type: 'data' },
      { from: 'quicklifts-web', to: 'firebase-auth', type: 'auth' },
      { from: 'quicklifts-web', to: 'cloud-firestore', type: 'data' },
      { from: 'quicklifts-web', to: 'netlify-functions', type: 'events' },
      { from: 'cloud-firestore', to: 'netlify-functions', type: 'events' },
      { from: 'cloud-firestore', to: 'virtual-office', type: 'data' },
      { from: 'cloud-firestore', to: 'agent-runner', type: 'data' },
      { from: 'virtual-office', to: 'telemetry-check', type: 'events' },
      { from: 'netlify-functions', to: 'stripe', type: 'data' },
      { from: 'quicklifts-ios', to: 'revenuecat', type: 'events' },
      { from: 'pulse-android', to: 'revenuecat', type: 'events' },
      { from: 'netlify-functions', to: 'brevo', type: 'events' },
      { from: 'netlify-functions', to: 'instantly', type: 'events' },
    ],
  },
  products: [quickliftsIosHandbook, pulseAndroidHandbook, pulseCheckIosHandbook, quickliftsWebHandbook],
  backendServices: [
    {
      id: 'svc-firebase-auth',
      name: 'Firebase Auth',
      purpose: 'Cross-platform authentication, provider sign-in, and session identity state.',
      owner: 'Platform',
      status: 'active',
      environments: ['Development', 'Production'],
      keyDependencies: ['Client auth UIs', 'users profile bootstrap'],
      sourceRefs: [
        { label: 'Auth Wrapper', path: 'src/components/AuthWrapper.tsx' },
        { label: 'Android README', path: '../Pulse-Android/README.md' },
      ],
    },
    {
      id: 'svc-firestore',
      name: 'Cloud Firestore',
      purpose: 'Primary datastore for app entities, operational controls, and agent runtime state.',
      owner: 'Platform',
      status: 'active',
      environments: ['Development', 'Production'],
      keyDependencies: ['All product repositories', 'Agent runtime', 'Admin dashboards'],
      sourceRefs: [
        { label: 'Firestore Contract', path: '../Pulse-Android/docs/FIRESTORE_CONTRACT.md' },
        { label: 'Presence Service', path: 'src/api/firebase/presence/service.ts' },
      ],
    },
    {
      id: 'svc-storage',
      name: 'Firebase Storage',
      purpose: 'Media and artifacts for profile images, exercise videos, and legal documents.',
      owner: 'Platform',
      status: 'active',
      environments: ['Development', 'Production'],
      keyDependencies: ['Creator uploads', 'press assets', 'exercise media'],
      sourceRefs: [
        { label: 'Storage Service', path: 'src/api/firebase/storage/service.ts' },
        { label: 'Press Upload', path: 'src/pages/press/upload.tsx' },
      ],
    },
    {
      id: 'svc-netlify-functions',
      name: 'Netlify Functions',
      purpose: 'Server-side actions for checkout, messaging, automations, and scheduled jobs.',
      owner: 'Web Platform',
      status: 'active',
      environments: ['Development', 'Production'],
      keyDependencies: ['Stripe workflows', 'admin APIs', 'automation jobs'],
      sourceRefs: [
        { label: 'Netlify Functions Structure', path: 'docs/netlify-functions-structure.md' },
        { label: 'Functions Directory', path: 'netlify/functions' },
      ],
    },
    {
      id: 'svc-creator-economics',
      name: 'Creator Engagement and Earnings Runtime',
      purpose:
        'Tracks creator engagement events, materializes creator score surfaces, and orchestrates earnings/payout flows.',
      owner: 'Creator Platform + Monetization Team',
      status: 'active',
      environments: ['Development', 'Production'],
      keyDependencies: ['engagement-events', 'users/categoryPoints.creator', 'leaderboards cache', 'Stripe Connect'],
      sourceRefs: [
        { label: 'iOS Engagement Service', path: '../QuickLifts/QuickLifts/Services/EngagementService.swift' },
        { label: 'Unified Earnings Function', path: 'netlify/functions/get-unified-earnings.js' },
        { label: 'Unified Payout Function', path: 'netlify/functions/initiate-unified-payout.js' },
        { label: 'Leaderboard Cache Script', path: 'scripts/cacheLeaderboardsOnce.js' },
      ],
    },
    {
      id: 'svc-agent-runner',
      name: 'Agent Runner Runtime',
      purpose: 'Autonomous task polling, execution, validation, and heartbeat emissions.',
      owner: 'Agent Infra',
      status: 'active',
      environments: ['Mac Mini runner environment'],
      keyDependencies: ['kanbanTasks', 'progress-timeline', 'agent-presence'],
      sourceRefs: [
        { label: 'Agent Runner', path: 'scripts/agentRunner.js' },
        { label: 'Heartbeat Protocol', path: 'src/components/admin/HeartbeatProtocolTab.tsx' },
      ],
    },
    {
      id: 'svc-telemetry-check',
      name: 'Telemetry Check Coordination',
      purpose: 'Group standup orchestration, capsule assignment, and meeting minutes publication.',
      owner: 'Agent Infra',
      status: 'active',
      environments: ['Runner environment'],
      keyDependencies: ['company-config', 'standup-config', 'agent-group-chats'],
      sourceRefs: [
        { label: 'Daily Standup Script', path: 'scripts/dailyStandup.js' },
        { label: 'Trigger API', path: 'src/pages/api/agent/trigger-standup.ts' },
      ],
    },
  ],
  dataCollections: [
    {
      id: 'coll-users',
      name: 'users',
      purpose: 'Canonical user profile and role records across products.',
      writtenBy: 'All clients, onboarding flows, admin tools',
      readBy: 'All clients and admin pages',
      criticalFields: [
        'id',
        'email',
        'subscriptionType',
        'role',
        'categoryPoints.creator',
        'creator.stripeAccountId',
        'creator.walletBalance',
        'creator.historicEarnings',
        'createdAt',
        'updatedAt',
      ],
      sourceRefs: [
        { label: 'Android Firestore Contract', path: '../Pulse-Android/docs/FIRESTORE_CONTRACT.md' },
        { label: 'User Service', path: 'src/api/firebase/user/service.ts' },
      ],
    },
    {
      id: 'coll-sweatlist',
      name: 'sweatlistCollections',
      purpose: 'Rounds/challenges including schedule windows and configuration.',
      writtenBy: 'Round creation flows',
      readBy: 'Round detail screens and leaderboards',
      criticalFields: ['title', 'creatorId', 'startDate', 'endDate', 'participantCount', 'status'],
      sourceRefs: [
        { label: 'Round Contract', path: '../Pulse-Android/docs/FIRESTORE_CONTRACT.md' },
        { label: 'Round Creation Page', path: 'src/pages/create-round.tsx' },
      ],
    },
    {
      id: 'coll-workout-summaries',
      name: 'workout-summaries',
      purpose: 'Aggregated workout session summaries for analytics and admin audits.',
      writtenBy: 'Workout completion pipelines',
      readBy: 'Admin metrics dashboards',
      criticalFields: ['userId', 'title', 'duration', 'exercises', 'startTime'],
      sourceRefs: [
        { label: 'Metrics Page', path: 'src/pages/admin/metrics.tsx' },
        { label: 'Workout Summaries Page', path: 'src/pages/admin/workoutSummaries.tsx' },
      ],
    },
    {
      id: 'coll-engagement-events',
      name: 'engagement-events',
      purpose: 'Event log for creator content engagement including reach, likes, bookmarks, and workout usage.',
      writtenBy: 'QuickLifts iOS engagement instrumentation',
      readBy: 'Creator analytics, score pipelines, and payout computation surfaces',
      criticalFields: ['type', 'videoId', 'creatorId', 'engagerId', 'engagerSubscription', 'workoutId', 'timestamp'],
      sourceRefs: [
        { label: 'Engagement Service', path: '../QuickLifts/QuickLifts/Services/EngagementService.swift' },
        { label: 'Exercise Logging Hooks', path: '../QuickLifts/QuickLifts/Models/Exercise.swift' },
      ],
    },
    {
      id: 'coll-exercise-videos',
      name: 'exerciseVideos',
      purpose: 'Canonical creator video records with aggregate engagement counters used by creator dashboards.',
      writtenBy: 'Creator upload and moderation pipelines',
      readBy: 'Discover/feed clients, creator dashboards, user service hydration',
      criticalFields: ['userId', 'exerciseId', 'totalAccountLikes', 'totalAccountBookmarked', 'totalAccountUsage', 'createdAt'],
      sourceRefs: [
        { label: 'Exercise Video Types', path: 'src/api/firebase/exercise/types.ts' },
        { label: 'User Video Fetch', path: 'src/api/firebase/user/service.ts' },
        { label: 'Professional Dashboard', path: '../QuickLifts/QuickLifts/View/Screens/LibraryView/ProfessionalDashboardCard/ProfessionalDashboadView.swift' },
      ],
    },
    {
      id: 'coll-leaderboards',
      name: 'leaderboards',
      purpose: 'Cached leaderboard documents for global users and top creators, including creator score ordering.',
      writtenBy: 'Leaderboard cache and score backfill scripts',
      readBy: 'Global leaderboard surfaces and creator discovery views',
      criticalFields: ['global100.users[]', 'topCreators.users[].creatorScore', 'updatedAt'],
      sourceRefs: [
        { label: 'Leaderboard Cache Script', path: 'scripts/cacheLeaderboardsOnce.js' },
        { label: 'Creator Score Backfill', path: 'scripts/backfillCreatorScore.js' },
        { label: 'Top Creators ViewModel', path: '../QuickLifts/QuickLifts/View/Screens/Leaderboard/GlobalLeaderboardViewModel.swift' },
      ],
    },
    {
      id: 'coll-payout-records',
      name: 'payoutRecords',
      purpose: 'Unified payout audit records for creator and winner transfers executed through Stripe.',
      writtenBy: 'initiate-unified-payout function',
      readBy: 'Admin payout dashboard and support operations',
      criticalFields: ['userId', 'amount', 'currency', 'strategy', 'results', 'createdAt', 'type'],
      sourceRefs: [
        { label: 'Initiate Unified Payout', path: 'netlify/functions/initiate-unified-payout.js' },
        { label: 'Admin Payout Dashboard', path: 'src/pages/admin/adminPayouts.tsx' },
      ],
    },
    {
      id: 'coll-agent-presence',
      name: 'agent-presence',
      purpose: 'Live runner status, task progress, and heartbeat timestamps per agent.',
      writtenBy: 'Agent Runner',
      readBy: 'Virtual Office and mission surfaces',
      criticalFields: ['status', 'currentTask', 'taskProgress', 'lastUpdate'],
      sourceRefs: [
        { label: 'Presence Service', path: 'src/api/firebase/presence/service.ts' },
        { label: 'Virtual Office', path: 'src/components/virtualOffice/VirtualOfficeContent.tsx' },
      ],
    },
    {
      id: 'coll-kanban',
      name: 'kanbanTasks',
      purpose: 'Agent capsule queue and task lifecycle state machine.',
      writtenBy: 'Operators, telemetry check, automation scripts',
      readBy: 'Agent Runner and Kanban UI',
      criticalFields: ['name', 'assignee', 'status', 'priority', 'source', 'northStarAligned'],
      sourceRefs: [
        { label: 'Kanban Service', path: 'src/api/firebase/kanban/service.ts' },
        { label: 'Kanban Seeder', path: 'scripts/manageKanban.js' },
      ],
    },
    {
      id: 'coll-progress-timeline',
      name: 'progress-timeline',
      purpose: 'Heartbeat feed of agent events and execution milestones.',
      writtenBy: 'Agent Runner and telemetry scripts',
      readBy: 'Virtual Office timeline panels',
      criticalFields: ['agentId', 'beat', 'headline', 'confidenceColor', 'createdAt'],
      sourceRefs: [
        { label: 'Progress Timeline Service', path: 'src/api/firebase/progressTimeline/service.ts' },
        { label: 'Timeline Panel', path: 'src/components/virtualOffice/ProgressTimelinePanel.tsx' },
      ],
    },
    {
      id: 'coll-meeting-minutes',
      name: 'meeting-minutes',
      purpose: 'Archived telemetry summaries and context for operator review.',
      writtenBy: 'Telemetry check scripts',
      readBy: 'Filing cabinet UI',
      criticalFields: ['sessionId', 'summary', 'durationMinutes', 'createdAt'],
      sourceRefs: [
        { label: 'Meeting Minutes Service', path: 'src/api/firebase/meetingMinutes/service.ts' },
        { label: 'Filing Cabinet', path: 'src/components/virtualOffice/FilingCabinet.tsx' },
      ],
    },
    {
      id: 'coll-company-config',
      name: 'company-config',
      purpose: 'Mission, north star, and system-level control documents.',
      writtenBy: 'Mission control and admin panels',
      readBy: 'Mission kickoff and agent assignment systems',
      criticalFields: ['north-star', 'mission-status'],
      sourceRefs: [
        { label: 'Mission Control', path: 'src/pages/admin/missionControl.tsx' },
        { label: 'North Star Panel', path: 'src/components/virtualOffice/NorthStarPanel.tsx' },
      ],
    },
    {
      id: 'coll-standup-config',
      name: 'standup-config',
      purpose: 'Telemetry schedule configuration and participant controls.',
      writtenBy: 'Standup config panel',
      readBy: 'Telemetry scripts',
      criticalFields: ['enabled', 'intervalMinutes', 'agents', 'protocol'],
      sourceRefs: [
        { label: 'Standup Config Panel', path: 'src/components/virtualOffice/StandupConfigPanel.tsx' },
        { label: 'Heartbeat Tab', path: 'src/components/admin/HeartbeatProtocolTab.tsx' },
      ],
    },
    {
      id: 'coll-mental-notes',
      name: 'mental-notes',
      purpose: 'PulseCheck concern tracking with severity and status evolution.',
      writtenBy: 'PulseCheck conversation analysis and user edits',
      readBy: 'PulseCheck profile and coach views',
      criticalFields: ['category', 'severity', 'status', 'lastDiscussed'],
      sourceRefs: [
        { label: 'PulseCheck App', path: '../PulseCheck/PulseCheck/PulseCheckApp.swift' },
        { label: 'Mental Notes UI', path: '../PulseCheck/PulseCheck/Views/Chat/MentalNotesBar.swift' },
      ],
    },
  ],
  integrations: [
    {
      id: 'int-stripe',
      name: 'Stripe',
      purpose: 'Web checkout, connected accounts, unified payouts, and monthly statement generation.',
      owner: 'Monetization Team',
      credentialSource: 'Netlify environment variables',
      products: ['QuickLifts Web', 'Coach Platform'],
      status: 'active',
      sourceRefs: [
        { label: 'Stripe Connect System', path: 'docs/stripe-connect-system.md' },
        { label: 'Subscription System Doc', path: 'docs/subscription-system.md' },
        { label: 'Create Connected Account', path: 'netlify/functions/create-connected-account.js' },
        { label: 'Get Monthly Statement', path: 'netlify/functions/get-monthly-statement.js' },
      ],
    },
    {
      id: 'int-revenuecat',
      name: 'RevenueCat',
      purpose: 'Mobile entitlement lifecycle synchronization across iOS and Android.',
      owner: 'Monetization Team',
      credentialSource: 'Mobile app config + backend sync credentials',
      products: ['QuickLifts iOS', 'Pulse Android', 'PulseCheck iOS'],
      status: 'active',
      sourceRefs: [
        { label: 'Subscription System Doc', path: 'docs/subscription-system.md' },
        { label: 'Pulse Android README', path: '../Pulse-Android/README.md' },
      ],
    },
    {
      id: 'int-brevo',
      name: 'Brevo',
      purpose: 'Email lifecycle sequences, waitlists, and growth communications.',
      owner: 'Growth Ops',
      credentialSource: 'Runtime env vars (`BREVO_MARKETING_KEY` / `BREVO_API_KEY`) with local-machine bundle parity; not currently mirrored in documented Secret Manager projects',
      products: ['QuickLifts Web'],
      status: 'active',
      sourceRefs: [
        { label: 'Brevo Notes', path: 'docs/Brevo implementation do.md' },
        { label: 'Local Machine Setup', path: 'docs/testing/local-machine-setup.md' },
        { label: 'Email Sequences Admin', path: 'src/pages/admin/emailSequences.tsx' },
      ],
    },
    {
      id: 'int-group-meet-guest-google-calendar',
      name: 'Group Meet Guest Google Calendar Import',
      purpose: 'Guest-consent Google OAuth flow that imports free/busy suggestions from a guest calendar into Group Meet.',
      owner: 'Web Platform',
      credentialSource:
        'Dedicated guest OAuth envs (`GOOGLE_GUEST_CALENDAR_CLIENT_ID`, `GOOGLE_GUEST_CALENDAR_CLIENT_SECRET`, `GOOGLE_GUEST_CALENDAR_REDIRECT_URI`) or Secret Manager-backed guest OAuth JSON (`GOOGLE_GUEST_CALENDAR_OAUTH_SECRET_NAME`), plus invite-scoped secure token storage (`GOOGLE_GUEST_CALENDAR_ENCRYPTION_KEY`, `GOOGLE_GUEST_CALENDAR_ENCRYPTION_SECRET_NAME`, or equivalent)',
      products: ['QuickLifts Web'],
      status: 'planned',
      sourceRefs: [
        { label: 'Guest Google Calendar Import Spec', path: 'docs/ops/group-meet-guest-google-calendar-import-spec-2026-04-05.md' },
        { label: 'Local Machine Setup', path: 'docs/testing/local-machine-setup.md' },
        { label: 'Infrastructure & Secrets Stack', path: 'src/components/admin/system-overview/InfrastructureSecretsStackTab.tsx' },
      ],
    },
    {
      id: 'int-instantly',
      name: 'Instantly',
      purpose: 'Outbound prospecting automation and sequence execution.',
      owner: 'Growth Ops',
      credentialSource: 'Ops-managed API credentials',
      products: ['QuickLifts Web'],
      status: 'active',
      sourceRefs: [
        { label: 'Creator Prospects', path: 'src/pages/admin/creatorProspects.tsx' },
        { label: 'University Prospects', path: 'src/pages/admin/universityProspects.tsx' },
      ],
    },
    {
      id: 'int-openai',
      name: 'OpenAI',
      purpose: 'Generation and analysis across round building, prospect extraction, and agent workflows.',
      owner: 'AI Systems',
      credentialSource: 'Server-side env vars and runner environment',
      products: ['QuickLifts iOS', 'QuickLifts Web', 'PulseCheck iOS', 'Agent Runner'],
      status: 'active',
      sourceRefs: [
        { label: 'Extract Creator Prospects API', path: 'src/pages/api/admin/extract-creator-prospects.ts' },
        { label: 'Agent Runner', path: 'scripts/agentRunner.js' },
      ],
    },
    {
      id: 'int-healthkit',
      name: 'HealthKit',
      purpose: 'Apple ecosystem health and activity context ingestion.',
      owner: 'iOS Squad',
      credentialSource: 'App entitlements and runtime permissions',
      products: ['QuickLifts iOS', 'PulseCheck iOS'],
      status: 'active',
      sourceRefs: [
        { label: 'HealthKit Manager', path: '../QuickLifts/QuickLifts/Services/HealthKitManager.swift' },
        { label: 'HealthKit Permissions Modal', path: '../QuickLifts/QuickLifts/View/Components/HealthKitPermissionsModalView.swift' },
      ],
    },
    {
      id: 'int-health-connect',
      name: 'Health Connect',
      purpose: 'Android health data integration for readiness and context.',
      owner: 'Android Squad',
      credentialSource: 'Android runtime permissions and app config',
      products: ['Pulse Android'],
      status: 'beta',
      sourceRefs: [
        { label: 'Health Connect Capture', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/health/HealthConnectCaptureScreen.kt' },
        { label: 'Android README', path: '../Pulse-Android/README.md' },
      ],
    },
  ],
  flows: endToEndFlows,
  ownershipMatrix: [
    {
      domain: 'QuickLifts iOS Core Product',
      primaryOwner: 'iOS Squad',
      backupOwner: 'Platform',
      releaseCadence: 'Weekly TestFlight / staged prod releases',
      runbookPath: '../iOS/docs/pulse-app-guide.md',
    },
    {
      domain: 'Pulse Android Core Product',
      primaryOwner: 'Android Squad',
      backupOwner: 'Platform',
      releaseCadence: 'Internal QA cycles + staged prod release',
      runbookPath: '../Pulse-Android/docs/RELEASE_CHECKLIST.md',
    },
    {
      domain: 'PulseCheck iOS',
      primaryOwner: 'PulseCheck Team',
      backupOwner: 'Mental Performance Systems',
      releaseCadence: 'Beta iteration cadence',
      runbookPath: '../iOS/docs/pulsecheck-development-guide.md',
    },
    {
      domain: 'QuickLifts Web Public + Admin',
      primaryOwner: 'Web Platform',
      backupOwner: 'Platform Ops',
      releaseCadence: 'Continuous deploy from main',
      runbookPath: 'docs/CODEBASE_MAP.md',
    },
    {
      domain: 'Agent Infrastructure',
      primaryOwner: 'Agent Infra Team',
      backupOwner: 'Platform Ops',
      releaseCadence: 'Continuous script/runtime updates',
      runbookPath: 'docs/AGENT_ONBOARDING.md',
    },
    {
      domain: 'Monetization Stack',
      primaryOwner: 'Monetization Team',
      backupOwner: 'Platform Ops',
      releaseCadence: 'Event-driven with scheduled reconciliation jobs',
      runbookPath: 'docs/subscription-system.md',
    },
  ],
  risksAndGaps: [
    {
      id: 'risk-schema-drift',
      title: 'Cross-client schema drift risk',
      severity: 'high',
      impact: 'Breaking behavior across iOS/Android/web when field semantics diverge.',
      mitigation: 'Enforce Firestore contract updates and cross-platform release checklists before launches.',
      owner: 'Platform',
    },
    {
      id: 'risk-agent-observability',
      title: 'Agent runtime observability fragmentation',
      severity: 'medium',
      impact: 'Operators can miss root causes when failures split across runner logs and timeline entries.',
      mitigation: 'Standardize incident annotations and link beats to source task IDs in every failure path.',
      owner: 'Agent Infra',
    },
    {
      id: 'risk-subscription-reconciliation',
      title: 'Entitlement reconciliation lag',
      severity: 'medium',
      impact: 'Paid users may see temporary access inconsistencies across web/mobile surfaces.',
      mitigation: 'Tighten webhook retry visibility and expose reconciliation status in admin subscription tools.',
      owner: 'Monetization Team',
    },
    {
      id: 'risk-payout-cadence-assumption',
      title: 'Payout cadence assumption drift',
      severity: 'medium',
      impact:
        'Teams can assume a fixed first-of-month creator payout automation while account-level Stripe payout schedules may differ.',
      mitigation:
        'Document payout schedule source of truth in Stripe account settings and keep handbook payout notes aligned with connected-account configuration.',
      owner: 'Monetization Team',
    },
    {
      id: 'risk-doc-staleness',
      title: 'Handbook staleness after rapid releases',
      severity: 'medium',
      impact: 'Exec and builder decisions made on stale ownership or flow assumptions.',
      mitigation: 'Run validation script in release checklist and update handbook manifest in same PR as major changes.',
      owner: 'Platform Ops',
    },
  ],
  glossary: [
    {
      term: 'Round',
      definition: 'Structured challenge window with assigned workouts, participant scoring, and leaderboard progression.',
    },
    {
      term: 'Capsule',
      definition: 'Atomic unit of agent work represented as a Kanban task with explicit north-star alignment.',
    },
    {
      term: 'Telemetry Check',
      definition: 'Automated group coordination cycle where agents report status and receive new assignments.',
    },
    {
      term: 'Heartbeat Feed',
      definition: 'Realtime progress event stream stored in progress-timeline and surfaced in Virtual Office.',
    },
    {
      term: 'North Star',
      definition: 'Current strategic objective set in company-config used to prioritize agent and operations work.',
    },
    {
      term: 'Architect (Hunter World)',
      definition: 'Creator role framing in Hunter World where creators build challenge experiences for users.',
    },
    {
      term: 'Feature Inventory',
      definition: 'Per-product table of capabilities including dependencies, data paths, ownership, and status.',
    },
  ],
};
