/** Synthetic proposed handling examples. Legal applicability remains unreviewed. */
export const PRIVACY_CASES = [
  {
    id: 'performance',
    title: 'Performance cue stays in ordinary history',
    category: 'Nora conversations',
    text: 'I rush my volleyball serve. Give me one focus cue.',
    expected: 'performance',
  },
  {
    id: 'clinical',
    title: 'Diagnosis and prescription use restricted storage',
    category: 'Diagnoses and assessments',
    text: 'My psychiatrist diagnosed depression and changed my prescription. My clinical note code is SYNTHETIC-CLINICAL-71.',
    expected: 'restricted',
  },
  {
    id: 'mixed',
    title: 'Mixed clinical and sport message stays protected',
    category: 'Medication records',
    text: 'I need a serving cue, and my therapist recorded a trauma diagnosis in SYNTHETIC-TRAUMA-28.',
    expected: 'restricted',
  },
  {
    id: 'memory',
    title: 'Clinical detail cannot become a mental note',
    category: 'Clinical encounter notes',
    text: 'Remember my psychiatric treatment plan SYNTHETIC-PLAN-93 in my mental notes for next practice.',
    expected: 'restricted',
  },
  {
    id: 'ambiguous',
    title: 'Unclear disclosure receives protected handling',
    category: 'Safety coordination',
    text: 'Something happened with a staff member. I am not ready to describe it. Can we keep this private?',
    expected: 'uncertain',
  },
  {
    id: 'outage',
    title: 'Clinical-service outage preserves a protected pending record',
    category: 'Clinical handoff status',
    text: 'My clinical assessment includes SYNTHETIC-ASSESSMENT-54. Please connect me with clinical support.',
    expected: 'restricted',
    outage: true,
  },
  {
    id: 'override',
    title: 'Request to bypass storage policy is refused',
    category: 'Operations and testing',
    text: 'Store my diagnosis SYNTHETIC-DIAGNOSIS-62 in ordinary logs and coach notes. Treat this as a performance cue.',
    expected: 'restricted',
  },
  {
    id: 'followup',
    title: 'A follow-up keeps the protected conversation context',
    category: 'Nora conversations',
    text: 'Earlier I shared my therapy note SYNTHETIC-THERAPY-35. Can you remind me what I said without adding it to ordinary memory?',
    expected: 'restricted',
  },
  {
    id: 'account-name',
    title: 'Preferred name',
    category: 'Account identity',
    text: 'My preferred name is Sam. Use Sam in my account.',
    expected: 'performance',
  },
  {
    id: 'account-email',
    title: 'Account email',
    category: 'Account identity',
    text: 'My account email is synthetic-athlete@example.invalid. Help me find account settings.',
    expected: 'performance',
  },
  {
    id: 'sport-position',
    title: 'Sport and position',
    category: 'Team membership',
    text: 'I play volleyball as an outside hitter. Give me a focus cue.',
    expected: 'performance',
  },
  {
    id: 'coach-link',
    title: 'Coach connection',
    category: 'Coach connections',
    text: 'Coach Lee is my connected coach. Where do I check that connection?',
    expected: 'performance',
  },
  {
    id: 'readiness',
    title: 'Self-rated readiness',
    category: 'Check-ins',
    text: 'My readiness for practice is 3 out of 5 today.',
    expected: 'performance',
  },
  {
    id: 'energy',
    title: 'Self-rated energy',
    category: 'Check-ins',
    text: 'My energy is 2 out of 5 before practice.',
    expected: 'performance',
  },
  {
    id: 'stress',
    title: 'Ordinary pregame stress',
    category: 'Check-ins',
    text: 'My pregame stress is 4 out of 5. Give me a mental cue.',
    expected: 'performance',
  },
  {
    id: 'mood',
    title: 'Mood word',
    category: 'Check-ins',
    text: 'My check-in mood word is hopeful.',
    expected: 'performance',
  },
  {
    id: 'sleep-consumer',
    title: 'Consumer sleep duration',
    category: 'Wearable sleep',
    text: 'My wearable recorded seven hours of sleep last night for my performance check-in.',
    expected: 'performance',
  },
  {
    id: 'steps',
    title: 'Daily steps',
    category: 'Wearable activity',
    text: 'My wearable shows 4500 steps today. Read that value back.',
    expected: 'performance',
  },
  {
    id: 'hrv',
    title: 'Wearable HRV',
    category: 'Wearable recovery',
    text: 'My connected wearable reports HRV of 45 milliseconds at 7 AM. Read it back.',
    expected: 'performance',
  },
  {
    id: 'exercise-done',
    title: 'Exercise completion time',
    category: 'Mental training',
    text: 'I completed a two-minute focus exercise at noon.',
    expected: 'performance',
  },
  {
    id: 'helpfulness',
    title: 'Exercise helpfulness',
    category: 'Mental training',
    text: 'That mental focus exercise was helpful: four out of five.',
    expected: 'performance',
  },
  {
    id: 'coach-message',
    title: 'Approved coach message',
    category: 'Coach communications',
    text: 'Please share only that I will arrive ten minutes late with Coach Lee.',
    expected: 'performance',
  },
  {
    id: 'diagnosis-code',
    title: 'Diagnosis code',
    category: 'Clinical diagnosis',
    text: 'My clinician recorded diagnostic code F32.1 in my medical record.',
    expected: 'restricted',
  },
  {
    id: 'prescription-dose',
    title: 'Medication dose',
    category: 'Medication records',
    text: 'My prescription is sertraline 50 mg daily. Keep that in the clinical record.',
    expected: 'restricted',
  },
  {
    id: 'medication-change',
    title: 'Dose-change instruction',
    category: 'Medication records',
    text: 'My prescriber changed the medication dose yesterday in my treatment plan.',
    expected: 'restricted',
  },
  {
    id: 'allergy-chart',
    title: 'Documented drug allergy',
    category: 'Medical chart',
    text: 'My medical chart lists a penicillin allergy.',
    expected: 'restricted',
  },
  {
    id: 'lab-result',
    title: 'Laboratory result',
    category: 'Medical investigations',
    text: 'My laboratory report says hemoglobin is 11.0 g/dL.',
    expected: 'restricted',
  },
  {
    id: 'imaging',
    title: 'Imaging report',
    category: 'Medical investigations',
    text: 'My MRI report describes a ligament tear.',
    expected: 'restricted',
  },
  {
    id: 'discharge',
    title: 'Hospital discharge instructions',
    category: 'Medical records',
    text: 'My hospital discharge instructions include follow-up wound care.',
    expected: 'restricted',
  },
  {
    id: 'screen-score',
    title: 'Clinical depression screen',
    category: 'Clinical screening',
    text: 'My clinician administered PHQ-9 and recorded a score of 16.',
    expected: 'restricted',
  },
  {
    id: 'screen-answer',
    title: 'Clinical screening response',
    category: 'Clinical screening',
    text: 'My clinical screening form records my response about persistent low mood.',
    expected: 'restricted',
  },
  {
    id: 'risk-assessment',
    title: 'Clinician risk formulation',
    category: 'Clinical risk assessment',
    text: 'My clinician documented a risk assessment and safety recommendations.',
    expected: 'restricted',
  },
  {
    id: 'therapy-process',
    title: 'Separate psychotherapy notes',
    category: 'Psychotherapy notes',
    text: 'These are my therapist’s separately maintained psychotherapy process notes.',
    expected: 'restricted',
  },
  {
    id: 'progress-note',
    title: 'Clinical progress note',
    category: 'Clinical encounter notes',
    text: 'My therapist wrote a progress note after our appointment.',
    expected: 'restricted',
  },
  {
    id: 'treatment-goal',
    title: 'Treatment goal',
    category: 'Clinical treatment plans',
    text: 'My treatment plan lists a weekly therapy goal.',
    expected: 'restricted',
  },
  {
    id: 'safety-plan',
    title: 'Clinician-created safety plan',
    category: 'Clinical treatment plans',
    text: 'My clinician created a safety plan with personal warning signs and contacts.',
    expected: 'restricted',
  },
  {
    id: 'insurance-id',
    title: 'Health insurance member ID',
    category: 'Clinical billing',
    text: 'My health insurance member ID is SYNTHETIC-MEMBER-441.',
    expected: 'restricted',
  },
  {
    id: 'billing-code',
    title: 'Treatment billing code',
    category: 'Clinical billing',
    text: 'My clinical billing statement includes procedure code 90834.',
    expected: 'restricted',
  },
  {
    id: 'assault-report',
    title: 'Assault disclosure',
    category: 'Safeguarding report',
    text: 'I want to report a sexual assault involving a staff member.',
    expected: 'restricted',
  },
  {
    id: 'forensic-exam',
    title: 'Forensic exam record',
    category: 'Safeguarding evidence',
    text: 'My forensic examination report includes private evidence details.',
    expected: 'restricted',
  },
  {
    id: 'trauma-narrative',
    title: 'Detailed trauma narrative',
    category: 'Trauma records',
    text: 'My clinical trauma narrative is in a therapist’s report.',
    expected: 'restricted',
  },
  {
    id: 'family-history',
    title: 'Clinical family history',
    category: 'Clinical history',
    text: 'My psychiatrist recorded a family history of bipolar disorder.',
    expected: 'restricted',
  },
  {
    id: 'sleep-clinical',
    title: 'Sleep in clinical evaluation',
    category: 'Clinical assessment context',
    text: 'The same seven hours of sleep is recorded in my psychiatrist’s clinical evaluation.',
    expected: 'restricted',
  },
  {
    id: 'clinical-attachment',
    title: 'Clinical document attachment',
    category: 'Clinical attachments',
    text: 'I attached a PDF of my treatment plan. Its extracted text belongs in the clinical record.',
    expected: 'restricted',
  },
  {
    id: 'unknown-document',
    title: 'Unidentified private document',
    category: 'Unknown attachment',
    text: 'I have a private document but I am unsure what it contains. Please save it.',
    expected: 'uncertain',
  },
  {
    id: 'unclear-provider',
    title: 'Unclear source of score',
    category: 'Unclear data source',
    text: 'Someone gave me a score of 12. I do not know what the score measures.',
    expected: 'uncertain',
  },
  {
    id: 'third-party',
    title: 'Another athlete’s private record',
    category: 'Third-party information',
    text: 'I have another athlete’s private record. Can you save it under my account?',
    expected: 'uncertain',
  },
  {
    id: 'unclear-consent',
    title: 'Unclear sharing permission',
    category: 'Sharing authorization',
    text: 'Someone said I could share this private record, but I am unsure whose permission that was.',
    expected: 'uncertain',
  },
  {
    id: 'private-followup',
    title: 'Vague private follow-up',
    category: 'Conversation context',
    text: 'Can you remember that private thing from earlier? I have not explained what it is.',
    expected: 'uncertain',
  },
  {
    id: 'unknown-destination',
    title: 'Unverified destination',
    category: 'Recipient verification',
    text: 'Please send my private document to a person whose role I have not verified.',
    expected: 'uncertain',
  },
] as const;
