'use strict';

const MISSION_SYSTEM_VERSION = 2;
const DEFAULT_MISSION_MODE = 'execute';
const DEFAULT_PLANNER_MODE = 'single';
const DEFAULT_STALL_WINDOW_MINUTES = 30;
const DEFAULT_MAX_ACTIVE_TASKS_PER_AGENT = 1;
const DEFAULT_MAX_QUEUED_EXECUTE_TASKS_PER_AGENT = 1;
const DEFAULT_MAX_QUEUED_EXPLORE_TASKS_PER_AGENT = 1;
const DEFAULT_SPOT_CHECK_SAMPLE_RATE = 0.2;
const DEFAULT_TASK_EXPIRY_HOURS = 72;

const AUTO_GENERATED_SOURCES = new Set([
  'self-assigned-idle',
  'self-assigned-mission',
  'nora-task-manager',
  'telemetry-auto-assign',
]);

const EXEC_EXCLUDED_STATUSES = new Set([
  'quarantined',
  'needs-spec',
  'needs-review',
  'canceled',
  'blocked',
]);

const ACTIVE_TASK_STATUSES = new Set(['todo', 'in-progress']);
const CORRECTION_SOURCES = new Set(['validation-gate', 'human-spot-check', 'system-correction']);
const HIGH_IMPACT_TASK_CLASSES = new Set(['execute-unit', 'delivery', 'correction']);

function toMillis(value) {
  if (!value) return 0;
  if (typeof value?.toDate === 'function') {
    try { return value.toDate().getTime(); } catch (_) { return 0; }
  }
  if (value instanceof Date) return value.getTime();
  const parsed = new Date(value).getTime();
  return Number.isFinite(parsed) ? parsed : 0;
}

function normalizeText(value) {
  return String(value || '').trim();
}

function normalizeMissionPolicy(rawMission = {}, overrides = {}) {
  const systemVersion = Number(
    overrides.systemVersion ??
    rawMission.systemVersion ??
    1
  ) || 1;
  const mode = String(overrides.mode || rawMission.mode || (systemVersion >= MISSION_SYSTEM_VERSION ? DEFAULT_MISSION_MODE : 'explore')).toLowerCase();
  return {
    ...rawMission,
    ...overrides,
    systemVersion,
    mode: mode === 'explore' ? 'explore' : 'execute',
    plannerMode: String(overrides.plannerMode || rawMission.plannerMode || DEFAULT_PLANNER_MODE).toLowerCase() || DEFAULT_PLANNER_MODE,
    stallWindowMinutes: Number(overrides.stallWindowMinutes || rawMission.stallWindowMinutes || DEFAULT_STALL_WINDOW_MINUTES) || DEFAULT_STALL_WINDOW_MINUTES,
    maxActiveTasksPerAgent: Number(overrides.maxActiveTasksPerAgent || rawMission.maxActiveTasksPerAgent || DEFAULT_MAX_ACTIVE_TASKS_PER_AGENT) || DEFAULT_MAX_ACTIVE_TASKS_PER_AGENT,
    maxQueuedExecuteTasksPerAgent: Number(overrides.maxQueuedExecuteTasksPerAgent || rawMission.maxQueuedExecuteTasksPerAgent || DEFAULT_MAX_QUEUED_EXECUTE_TASKS_PER_AGENT) || DEFAULT_MAX_QUEUED_EXECUTE_TASKS_PER_AGENT,
    maxQueuedExploreTasksPerAgent: Number(overrides.maxQueuedExploreTasksPerAgent || rawMission.maxQueuedExploreTasksPerAgent || DEFAULT_MAX_QUEUED_EXPLORE_TASKS_PER_AGENT) || DEFAULT_MAX_QUEUED_EXPLORE_TASKS_PER_AGENT,
    canary: Boolean(overrides.canary ?? rawMission.canary),
  };
}

function isMissionSystemV2(mission) {
  return Number(mission?.systemVersion || 0) >= MISSION_SYSTEM_VERSION;
}

function isExecuteMissionActive(mission) {
  const policy = normalizeMissionPolicy(mission || {});
  return isMissionSystemV2(policy) && String(policy.status || '').toLowerCase() === 'active' && policy.mode === 'execute';
}

function isExploreMissionActive(mission) {
  const policy = normalizeMissionPolicy(mission || {});
  return isMissionSystemV2(policy) && String(policy.status || '').toLowerCase() === 'active' && policy.mode === 'explore';
}

function isAutoGeneratedTask(task) {
  return AUTO_GENERATED_SOURCES.has(String(task?.source || '').toLowerCase());
}

function isCorrectionTask(task) {
  const source = String(task?.source || '').toLowerCase();
  const taskClass = String(task?.taskClass || '').toLowerCase();
  const name = String(task?.name || '');
  return CORRECTION_SOURCES.has(source) || taskClass === 'correction' || /^\s*\[correction\]/i.test(name);
}

function isDependencyTask(task) {
  const taskClass = String(task?.taskClass || '').toLowerCase();
  return taskClass === 'dependency-unblocker' || taskClass === 'dependency';
}

function isExpiredTask(task, now = Date.now()) {
  const expiresAtMs = toMillis(task?.expiresAt);
  return expiresAtMs > 0 && expiresAtMs <= now;
}

function isLegacyExecuteTask(task) {
  return String(task?.mode || '').toLowerCase() === 'execute' && Number(task?.specVersion || 0) < MISSION_SYSTEM_VERSION;
}

function normalizePriority(priority) {
  const value = String(priority || '').toLowerCase();
  if (value === 'high' || value === 'urgent') return 3;
  if (value === 'low') return 1;
  return 2;
}

function normalizeArtifactKind(kind) {
  const value = String(kind || '').trim().toLowerCase();
  if (['repo_file', 'runtime_change', 'firestore_change', 'api_behavior', 'external_action', 'content_asset'].includes(value)) {
    return value;
  }
  return '';
}

function normalizeCheckKind(kind) {
  const value = String(kind || '').trim().toLowerCase();
  if (['shell', 'file', 'firestore', 'http', 'manual-spot-check'].includes(value)) {
    return value;
  }
  return '';
}

function buildObjectiveId(raw, fallback = 'OBJECTIVE') {
  const normalized = String(raw || '')
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 48);
  return normalized || fallback;
}

function extractTargets(text) {
  const source = String(text || '');
  const matches = new Set();
  const fileRx = /\b(?:src|docs|scripts|functions|PulseCommand|QuickLifts-Web|public|pages|components)\/[A-Za-z0-9_./-]+\.[A-Za-z0-9]+/g;
  const apiRx = /\b\/api\/[A-Za-z0-9/_-]+\b/g;
  const firestoreRx = /\b(?:agent-tasks|agent-deliverables|agent-presence|company-config\/mission-status|company-config\/north-star|mission-runs\/[A-Za-z0-9_-]+)\b/g;
  const uiRx = /\b[A-Z][A-Za-z0-9]+(?:View|Panel|Card|Service|Controller|Page|Screen|Component)\b/g;

  for (const rx of [fileRx, apiRx, firestoreRx, uiRx]) {
    const found = source.match(rx) || [];
    for (const item of found) matches.add(item);
  }

  return Array.from(matches).slice(0, 6);
}

function inferArtifactSpec(task) {
  const text = [task?.name, task?.description].filter(Boolean).join('\n');
  const targets = extractTargets(text);
  const firstTarget = targets[0] || '';

  let kind = '';
  if (firstTarget.startsWith('/api/')) {
    kind = 'api_behavior';
  } else if (firstTarget.includes('/') && /\.[A-Za-z0-9]+$/.test(firstTarget)) {
    kind = 'repo_file';
  } else if (/agent-tasks|agent-deliverables|agent-presence|company-config/.test(firstTarget)) {
    kind = 'firestore_change';
  } else if (/landing page|ui|component|screen|panel|dashboard/i.test(text)) {
    kind = 'runtime_change';
  } else if (/doc|brief|memo|copy|content|narrative|messaging/i.test(text)) {
    kind = 'content_asset';
  } else {
    kind = 'runtime_change';
  }

  const successDefinition = firstTarget
    ? `Deliver the planned change touching ${firstTarget} and satisfy the acceptance checks.`
    : `Deliver the planned change and satisfy the acceptance checks.`;

  return {
    kind,
    targets: targets.length > 0 ? targets : [String(task?.name || 'deliverable').slice(0, 80)],
    successDefinition,
    mustTouchRepo: kind !== 'firestore_change' && kind !== 'external_action',
    impactScope: kind === 'content_asset' ? 'supporting' : 'user-facing',
  };
}

function inferAcceptanceChecks(task, artifactSpec) {
  const targets = Array.isArray(artifactSpec?.targets) ? artifactSpec.targets : [];
  const firstTarget = String(targets[0] || '').trim();
  const checks = [];

  if (artifactSpec?.kind === 'repo_file' && firstTarget) {
    checks.push({
      kind: 'file',
      label: `Artifact exists: ${firstTarget}`,
      commandOrPath: firstTarget,
      expectedSignal: 'File exists and is readable.',
    });
    checks.push({
      kind: 'manual-spot-check',
      label: `Review behavior linked to ${firstTarget}`,
      commandOrPath: firstTarget,
      expectedSignal: 'Human spot-check confirms the change delivers the intended behavior.',
    });
    return checks;
  }

  if (artifactSpec?.kind === 'api_behavior' && firstTarget) {
    checks.push({
      kind: 'http',
      label: `Endpoint responds: ${firstTarget}`,
      commandOrPath: firstTarget,
      expectedSignal: 'Endpoint returns a successful response for the intended scenario.',
    });
    checks.push({
      kind: 'manual-spot-check',
      label: `Confirm API outcome for ${firstTarget}`,
      commandOrPath: firstTarget,
      expectedSignal: 'Response payload shows the expected new behavior.',
    });
    return checks;
  }

  if (artifactSpec?.kind === 'firestore_change' && firstTarget) {
    checks.push({
      kind: 'firestore',
      label: `Firestore target updated: ${firstTarget}`,
      commandOrPath: firstTarget,
      expectedSignal: 'Document or collection reflects the intended change.',
    });
    checks.push({
      kind: 'manual-spot-check',
      label: `Confirm downstream effect of ${firstTarget}`,
      commandOrPath: firstTarget,
      expectedSignal: 'Human spot-check confirms the change drives the intended system outcome.',
    });
    return checks;
  }

  checks.push({
    kind: 'shell',
    label: 'Repo changed during execution',
    commandOrPath: 'git status --short',
    expectedSignal: 'Relevant task artifacts appear in the working tree or commit output.',
  });
  checks.push({
    kind: 'manual-spot-check',
    label: 'Confirm intended impact',
    commandOrPath: firstTarget || String(task?.name || '').slice(0, 120),
    expectedSignal: 'Human spot-check confirms the change is real and aligned to the objective.',
  });
  return checks;
}

function hasValidTaskContract(task) {
  const artifactSpec = task?.artifactSpec || {};
  const acceptanceChecks = Array.isArray(task?.acceptanceChecks) ? task.acceptanceChecks : [];
  if (!normalizeArtifactKind(artifactSpec.kind)) return false;
  if (acceptanceChecks.length < 2) return false;

  const normalizedChecks = acceptanceChecks
    .map((check) => ({
      kind: normalizeCheckKind(check?.kind),
      label: normalizeText(check?.label),
      commandOrPath: normalizeText(check?.commandOrPath),
      expectedSignal: normalizeText(check?.expectedSignal),
    }))
    .filter((check) => check.kind && check.label && check.commandOrPath);

  if (normalizedChecks.length < 2) return false;

  const automated = normalizedChecks.filter((check) => check.kind !== 'manual-spot-check');
  return automated.length >= 1;
}

function buildExecuteTaskContract(task, options = {}) {
  const objectiveId = buildObjectiveId(options.objectiveId || task?.objectiveId || task?.northStarObjectiveLink || task?.northStarObjective || task?.name, options.fallbackObjectiveId || 'OBJECTIVE');
  const artifactSpec = normalizeArtifactKind(task?.artifactSpec?.kind)
    ? {
        kind: normalizeArtifactKind(task.artifactSpec.kind),
        targets: Array.isArray(task.artifactSpec.targets) ? task.artifactSpec.targets.filter(Boolean) : [],
        successDefinition: normalizeText(task.artifactSpec.successDefinition) || `Deliver the planned artifact for ${task?.name || 'task'}.`,
        mustTouchRepo: Boolean(task.artifactSpec.mustTouchRepo),
        impactScope: normalizeText(task.artifactSpec.impactScope) || 'user-facing',
      }
    : inferArtifactSpec(task);

  const acceptanceChecks = (Array.isArray(task?.acceptanceChecks) ? task.acceptanceChecks : inferAcceptanceChecks(task, artifactSpec))
    .map((check) => ({
      kind: normalizeCheckKind(check?.kind),
      label: normalizeText(check?.label),
      commandOrPath: normalizeText(check?.commandOrPath),
      expectedSignal: normalizeText(check?.expectedSignal),
    }))
    .filter((check) => check.kind && check.label && check.commandOrPath);

  const base = {
    specVersion: MISSION_SYSTEM_VERSION,
    mode: 'execute',
    plannerSource: options.plannerSource || task?.plannerSource || 'mission-supervisor',
    taskClass: options.taskClass || task?.taskClass || 'execute-unit',
    objectiveId,
    artifactSpec,
    acceptanceChecks,
    dependencyIds: Array.isArray(task?.dependencyIds) ? task.dependencyIds.filter(Boolean) : [],
    verificationPolicy: task?.verificationPolicy || {
      automatedAuthority: true,
      humanSpotCheck: 'exceptions-and-sample',
      sampleRate: DEFAULT_SPOT_CHECK_SAMPLE_RATE,
    },
    priorityScore: Number(task?.priorityScore || options.priorityScore || (normalizePriority(task?.priority) * 10)) || 20,
    expiresAt: task?.expiresAt || new Date(Date.now() + (options.expiresInHours || DEFAULT_TASK_EXPIRY_HOURS) * 60 * 60 * 1000),
    quarantineReason: task?.quarantineReason || '',
    quarantinedAt: task?.quarantinedAt || null,
    verificationResult: task?.verificationResult || null,
  };

  return {
    ...base,
    hasContract: hasValidTaskContract({ artifactSpec: base.artifactSpec, acceptanceChecks: base.acceptanceChecks }),
  };
}

function buildExploreTaskMetadata(task, options = {}) {
  return {
    specVersion: MISSION_SYSTEM_VERSION,
    mode: 'explore',
    plannerSource: options.plannerSource || task?.plannerSource || 'worker-self',
    taskClass: options.taskClass || task?.taskClass || 'explore-brief',
    objectiveId: buildObjectiveId(options.objectiveId || task?.objectiveId || task?.focusObjective || task?.northStarObjective || task?.name, 'EXPLORE'),
    artifactSpec: task?.artifactSpec || null,
    acceptanceChecks: Array.isArray(task?.acceptanceChecks) ? task.acceptanceChecks : [],
    dependencyIds: Array.isArray(task?.dependencyIds) ? task.dependencyIds.filter(Boolean) : [],
    verificationPolicy: task?.verificationPolicy || {
      automatedAuthority: false,
      humanSpotCheck: 'manual',
      sampleRate: 0,
    },
    priorityScore: Number(task?.priorityScore || options.priorityScore || (normalizePriority(task?.priority) * 10)) || 10,
    expiresAt: task?.expiresAt || new Date(Date.now() + (options.expiresInHours || DEFAULT_TASK_EXPIRY_HOURS) * 60 * 60 * 1000),
    quarantineReason: task?.quarantineReason || '',
    quarantinedAt: task?.quarantinedAt || null,
    verificationResult: task?.verificationResult || null,
  };
}

function shouldQuarantineTask(task, presenceByAgent = {}, now = Date.now()) {
  if (!isAutoGeneratedTask(task)) return false;
  const status = String(task?.status || '').toLowerCase();
  if (status !== 'todo' && status !== 'needs-review') return false;
  const updatedAtMs = toMillis(task?.updatedAt || task?.createdAt);
  if (updatedAtMs && (now - updatedAtMs) < 2 * 60 * 60 * 1000) return false;

  const assignee = String(task?.assignee || '').trim().toLowerCase();
  const matchingPresence = Object.values(presenceByAgent).find((presence) => {
    const taskId = String(presence?.currentTaskId || '').trim();
    const taskName = String(presence?.currentTask || '').trim();
    if (taskId && taskId === String(task?.id || '')) return true;
    if (taskName && taskName === String(task?.name || '')) return true;
    return String(presence?.displayName || '').trim().toLowerCase() === assignee && String(presence?.status || '').toLowerCase() === 'working';
  });

  return !matchingPresence;
}

function getTaskQueueRank(task, mission) {
  if (isCorrectionTask(task)) return 0;
  if (isExecuteMissionActive(mission) && String(task?.mode || '').toLowerCase() === 'execute' && Number(task?.specVersion || 0) >= MISSION_SYSTEM_VERSION) {
    return 1;
  }
  if (isDependencyTask(task)) return 2;
  if (String(task?.mode || '').toLowerCase() === 'explore' || !task?.mode) return 3;
  return 4;
}

function compareTaskCandidates(a, b, mission) {
  const rankDiff = getTaskQueueRank(a, mission) - getTaskQueueRank(b, mission);
  if (rankDiff !== 0) return rankDiff;

  const priorityDiff = Number(b?.priorityScore || normalizePriority(b?.priority) * 10) - Number(a?.priorityScore || normalizePriority(a?.priority) * 10);
  if (priorityDiff !== 0) return priorityDiff;

  const aUpdated = toMillis(a?.updatedAt || a?.createdAt);
  const bUpdated = toMillis(b?.updatedAt || b?.createdAt);
  if (aUpdated !== bUpdated) return bUpdated - aUpdated;

  return toMillis(b?.createdAt) - toMillis(a?.createdAt);
}

function isTaskRunnable(task, mission, now = Date.now()) {
  const status = String(task?.status || '').toLowerCase();
  if (!ACTIVE_TASK_STATUSES.has(status)) return false;
  if (EXEC_EXCLUDED_STATUSES.has(status)) return false;
  if (task?.runnerBlocked) return false;
  if (isExpiredTask(task, now)) return false;

  if (!isExecuteMissionActive(mission)) {
    return status === 'todo' || status === 'in-progress';
  }

  if (isCorrectionTask(task)) return true;
  if (String(task?.mode || '').toLowerCase() !== 'execute') return false;
  if (Number(task?.specVersion || 0) < MISSION_SYSTEM_VERSION) return false;
  return hasValidTaskContract(task);
}

async function recordMissionRunEvent(db, FieldValue, missionId, eventType, payload = {}) {
  if (!missionId || !db) return null;

  const counters = {};
  switch (String(eventType || '').toLowerCase()) {
    case 'created-task':
      counters.createdTaskCount = FieldValue.increment(1);
      break;
    case 'quarantined-task':
      counters.quarantinedTaskCount = FieldValue.increment(1);
      break;
    case 'verified-auto':
      counters.verifiedAutoCount = FieldValue.increment(1);
      break;
    case 'verified-human':
      counters.verifiedHumanCount = FieldValue.increment(1);
      break;
    case 'rejected':
      counters.rejectedCount = FieldValue.increment(1);
      break;
    case 'stall-pause':
      counters.stallPauseCount = FieldValue.increment(1);
      break;
    case 'corrective-loop':
      counters.correctiveLoopCount = FieldValue.increment(1);
      break;
    default:
      break;
  }

  const runRef = db.collection('mission-runs').doc(missionId);
  await runRef.set({
    missionId,
    updatedAt: FieldValue.serverTimestamp(),
    startedAt: payload.startedAt || FieldValue.serverTimestamp(),
    ...counters,
  }, { merge: true });

  const eventRef = runRef.collection('events').doc();
  await eventRef.set({
    type: eventType,
    missionId,
    ...payload,
    createdAt: FieldValue.serverTimestamp(),
  });

  return eventRef.id;
}

module.exports = {
  ACTIVE_TASK_STATUSES,
  AUTO_GENERATED_SOURCES,
  CORRECTION_SOURCES,
  DEFAULT_MAX_ACTIVE_TASKS_PER_AGENT,
  DEFAULT_MAX_QUEUED_EXECUTE_TASKS_PER_AGENT,
  DEFAULT_MAX_QUEUED_EXPLORE_TASKS_PER_AGENT,
  DEFAULT_MISSION_MODE,
  DEFAULT_PLANNER_MODE,
  DEFAULT_SPOT_CHECK_SAMPLE_RATE,
  DEFAULT_STALL_WINDOW_MINUTES,
  EXEC_EXCLUDED_STATUSES,
  HIGH_IMPACT_TASK_CLASSES,
  MISSION_SYSTEM_VERSION,
  buildExecuteTaskContract,
  buildExploreTaskMetadata,
  buildObjectiveId,
  compareTaskCandidates,
  extractTargets,
  getTaskQueueRank,
  hasValidTaskContract,
  inferAcceptanceChecks,
  inferArtifactSpec,
  isAutoGeneratedTask,
  isCorrectionTask,
  isDependencyTask,
  isExecuteMissionActive,
  isExploreMissionActive,
  isExpiredTask,
  isLegacyExecuteTask,
  isMissionSystemV2,
  isTaskRunnable,
  normalizeMissionPolicy,
  recordMissionRunEvent,
  shouldQuarantineTask,
  toMillis,
};
