'use strict';

const {
  normalizeString,
  normalizeMissionPlaybook,
} = require('./missionAdmissionTypes');

const EXTERNAL_ACCOUNT_ACTIVATION_PLAYBOOK_ID = 'external-account-activation-v1';

function buildExternalAccountActivationPlaybook() {
  return normalizeMissionPlaybook({
    id: EXTERNAL_ACCOUNT_ACTIVATION_PLAYBOOK_ID,
    family: 'external-account-activation',
    version: 1,
    versionTag: 'v1.1',
    description: 'Stage-gated playbook for coach-led external account activation and downstream invite readiness.',
    primaryDomain: 'activation',
    stageGraph: [
      {
        id: 'target-selected',
        label: 'Target selected',
        ordinal: 1,
        entrySignalIds: ['target-identity-locked'],
        regressionSignalIds: [],
        unlockActionTypes: ['target-research'],
      },
      {
        id: 'contact-path-confirmed',
        label: 'Contact path confirmed',
        ordinal: 2,
        entrySignalIds: ['contact-route-confirmed'],
        regressionSignalIds: ['target-identity-locked-revoked'],
        unlockActionTypes: ['contact-path-confirmation'],
      },
      {
        id: 'outreach-ready',
        label: 'Outreach ready',
        ordinal: 3,
        entrySignalIds: ['outreach-asset-ready'],
        regressionSignalIds: ['contact-route-confirmed-revoked'],
        unlockActionTypes: ['outreach-asset-creation'],
      },
      {
        id: 'outreach-sent',
        label: 'Outreach sent',
        ordinal: 4,
        entrySignalIds: ['outreach-sent'],
        regressionSignalIds: ['outreach-asset-ready-revoked'],
        unlockActionTypes: ['send-outreach', 'confirm-interest'],
      },
      {
        id: 'interest-confirmed',
        label: 'Interest confirmed',
        ordinal: 5,
        entrySignalIds: ['interest-confirmed'],
        regressionSignalIds: ['outreach-sent-revoked'],
        unlockActionTypes: ['confirm-owner-email', 'preprovision-org-team-shell'],
      },
      {
        id: 'provisioning-ready',
        label: 'Provisioning ready',
        ordinal: 6,
        entrySignalIds: ['owner-email-confirmed'],
        regressionSignalIds: ['interest-confirmed-revoked'],
        unlockActionTypes: ['reserve-admin-membership', 'create-activation-link'],
      },
      {
        id: 'activation-link-created',
        label: 'Activation link created',
        ordinal: 7,
        entrySignalIds: ['activation-link-created'],
        regressionSignalIds: ['owner-email-confirmed-revoked'],
        unlockActionTypes: ['send-activation-link'],
      },
      {
        id: 'activation-sent',
        label: 'Activation sent',
        ordinal: 8,
        entrySignalIds: ['activation-link-sent'],
        regressionSignalIds: ['activation-link-created-revoked'],
        unlockActionTypes: ['confirm-redemption'],
      },
      {
        id: 'admin-activated',
        label: 'Admin activated',
        ordinal: 9,
        entrySignalIds: ['activation-link-redeemed'],
        regressionSignalIds: ['activation-link-redeemed-revoked'],
        unlockActionTypes: ['verify-downstream-invite-readiness'],
      },
      {
        id: 'container-ready',
        label: 'Container ready',
        ordinal: 10,
        entrySignalIds: ['downstream-invite-ready'],
        regressionSignalIds: ['activation-link-redeemed-revoked'],
        unlockActionTypes: [],
      },
    ],
    readinessSignalTemplates: [
      {
        id: 'target-identity-locked',
        label: 'Target identity locked',
        proofTemplateId: 'proof-target-identity-locked-v1',
        evaluationMode: 'instant',
        freshnessMinutes: 1440,
        expiresAfterMinutes: 10080,
        requiredForActionTypes: ['target-research'],
        sourceOfTruth: 'crm',
        successEvent: 'target identity confirmed and locked for mission use',
      },
      {
        id: 'contact-route-confirmed',
        label: 'Contact route confirmed',
        proofTemplateId: 'proof-contact-route-confirmed-v1',
        evaluationMode: 'instant',
        freshnessMinutes: 1440,
        expiresAfterMinutes: 10080,
        requiredForActionTypes: ['contact-path-confirmation'],
        sourceOfTruth: 'crm',
        successEvent: 'valid contact route and owner path confirmed',
      },
      {
        id: 'outreach-asset-ready',
        label: 'Outreach asset ready',
        proofTemplateId: 'proof-outreach-asset-ready-v1',
        evaluationMode: 'instant',
        freshnessMinutes: 720,
        expiresAfterMinutes: 1440,
        requiredForActionTypes: ['outreach-asset-creation'],
        sourceOfTruth: 'repo',
        successEvent: 'send-ready outreach asset exists',
      },
      {
        id: 'outreach-sent',
        label: 'Outreach sent',
        proofTemplateId: 'proof-outreach-sent-v1',
        evaluationMode: 'instant',
        freshnessMinutes: 240,
        expiresAfterMinutes: 1440,
        requiredForActionTypes: ['send-outreach'],
        sourceOfTruth: 'crm',
        successEvent: 'outreach was delivered to the target',
      },
      {
        id: 'interest-confirmed',
        label: 'Interest confirmed',
        proofTemplateId: 'proof-interest-confirmed-v1',
        evaluationMode: 'windowed',
        freshnessMinutes: 240,
        expiresAfterMinutes: 10080,
        requiredForActionTypes: ['preprovision-org-team-shell'],
        sourceOfTruth: 'crm',
        successEvent: 'target explicitly confirms interest or acceptance',
      },
      {
        id: 'owner-email-confirmed',
        label: 'Owner email confirmed',
        proofTemplateId: 'proof-owner-email-confirmed-v1',
        evaluationMode: 'instant',
        freshnessMinutes: 240,
        expiresAfterMinutes: 2880,
        requiredForActionTypes: ['create-activation-link'],
        sourceOfTruth: 'crm',
        successEvent: 'verified owner email bound to the target container',
      },
      {
        id: 'activation-link-created',
        label: 'Activation link created',
        proofTemplateId: 'proof-activation-link-created-v1',
        evaluationMode: 'instant',
        freshnessMinutes: 240,
        expiresAfterMinutes: 2880,
        requiredForActionTypes: ['send-activation-link'],
        sourceOfTruth: 'firestore',
        successEvent: 'admin activation link exists and is addressable',
      },
      {
        id: 'activation-link-sent',
        label: 'Activation link sent',
        proofTemplateId: 'proof-activation-link-sent-v1',
        evaluationMode: 'instant',
        freshnessMinutes: 240,
        expiresAfterMinutes: 2880,
        requiredForActionTypes: ['confirm-redemption'],
        sourceOfTruth: 'firestore',
        successEvent: 'activation link was delivered to the target',
      },
      {
        id: 'activation-link-redeemed',
        label: 'Activation link redeemed',
        proofTemplateId: 'proof-activation-link-redeemed-v1',
        evaluationMode: 'windowed',
        freshnessMinutes: 240,
        expiresAfterMinutes: 2880,
        requiredForActionTypes: ['confirm-redemption', 'verify-downstream-invite-readiness'],
        sourceOfTruth: 'firestore',
        successEvent: 'external admin redeems activation and becomes controlling admin',
      },
      {
        id: 'downstream-invite-ready',
        label: 'Downstream invite ready',
        proofTemplateId: 'proof-downstream-invite-ready-v1',
        evaluationMode: 'instant',
        freshnessMinutes: 240,
        expiresAfterMinutes: 2880,
        requiredForActionTypes: ['verify-downstream-invite-readiness'],
        sourceOfTruth: 'firestore',
        successEvent: 'container can accept downstream team or staff invites',
      },
    ],
    actionPolicies: [
      {
        id: 'target-research',
        actionType: 'target-research',
        label: 'Target research',
        sideEffectClass: 'reversible-prepare',
        requiredStageId: 'target-selected',
        requiredReadinessSignalIds: ['target-identity-locked'],
        requiredApprovalTypes: [],
        allowSpeculative: true,
        defaultCreditMode: 'none',
        cleanupTTLHours: 72,
      },
      {
        id: 'contact-path-confirmation',
        actionType: 'contact-path-confirmation',
        label: 'Contact path confirmation',
        sideEffectClass: 'reversible-prepare',
        requiredStageId: 'contact-path-confirmed',
        requiredReadinessSignalIds: ['contact-route-confirmed'],
        requiredApprovalTypes: [],
        allowSpeculative: true,
        defaultCreditMode: 'none',
        cleanupTTLHours: 72,
      },
      {
        id: 'outreach-asset-creation',
        actionType: 'outreach-asset-creation',
        label: 'Outreach asset creation',
        sideEffectClass: 'reversible-prepare',
        requiredStageId: 'outreach-ready',
        requiredReadinessSignalIds: ['outreach-asset-ready'],
        requiredApprovalTypes: [],
        allowSpeculative: true,
        defaultCreditMode: 'execution',
        cleanupTTLHours: 72,
      },
      {
        id: 'send-outreach',
        actionType: 'send-outreach',
        label: 'Send outreach',
        sideEffectClass: 'external-durable',
        requiredStageId: 'outreach-sent',
        requiredReadinessSignalIds: ['outreach-asset-ready'],
        requiredApprovalTypes: ['outreach-owner'],
        allowSpeculative: false,
        defaultCreditMode: 'commercial',
        cleanupTTLHours: 48,
      },
      {
        id: 'confirm-interest',
        actionType: 'confirm-interest',
        label: 'Confirm interest',
        sideEffectClass: 'reversible-prepare',
        requiredStageId: 'outreach-sent',
        requiredReadinessSignalIds: ['outreach-sent'],
        requiredApprovalTypes: [],
        allowSpeculative: false,
        defaultCreditMode: 'commercial',
        cleanupTTLHours: 168,
      },
      {
        id: 'confirm-owner-email',
        actionType: 'confirm-owner-email',
        label: 'Confirm owner email',
        sideEffectClass: 'reversible-prepare',
        requiredStageId: 'interest-confirmed',
        requiredReadinessSignalIds: ['interest-confirmed'],
        requiredApprovalTypes: [],
        allowSpeculative: false,
        defaultCreditMode: 'execution',
        cleanupTTLHours: 168,
      },
      {
        id: 'preprovision-org-team-shell',
        actionType: 'preprovision-org-team-shell',
        label: 'Preprovision org/team shell',
        sideEffectClass: 'internal-durable',
        requiredStageId: 'interest-confirmed',
        requiredReadinessSignalIds: ['interest-confirmed'],
        requiredApprovalTypes: ['mission-owner'],
        allowSpeculative: true,
        defaultCreditMode: 'execution',
        cleanupTTLHours: 336,
      },
      {
        id: 'reserve-admin-membership',
        actionType: 'reserve-admin-membership',
        label: 'Reserve admin membership',
        sideEffectClass: 'internal-durable',
        requiredStageId: 'provisioning-ready',
        requiredReadinessSignalIds: ['owner-email-confirmed'],
        requiredApprovalTypes: ['mission-owner'],
        allowSpeculative: true,
        defaultCreditMode: 'execution',
        cleanupTTLHours: 336,
      },
      {
        id: 'create-activation-link',
        actionType: 'create-activation-link',
        label: 'Create activation link',
        sideEffectClass: 'internal-durable',
        requiredStageId: 'provisioning-ready',
        requiredReadinessSignalIds: ['owner-email-confirmed'],
        requiredApprovalTypes: ['mission-owner'],
        allowSpeculative: false,
        defaultCreditMode: 'execution',
        cleanupTTLHours: 168,
      },
      {
        id: 'send-activation-link',
        actionType: 'send-activation-link',
        label: 'Send activation link',
        sideEffectClass: 'external-durable',
        requiredStageId: 'activation-link-created',
        requiredReadinessSignalIds: ['activation-link-created', 'owner-email-confirmed'],
        requiredApprovalTypes: ['mission-owner'],
        allowSpeculative: false,
        defaultCreditMode: 'commercial',
        cleanupTTLHours: 168,
      },
      {
        id: 'confirm-redemption',
        actionType: 'confirm-redemption',
        label: 'Confirm redemption',
        sideEffectClass: 'reversible-prepare',
        requiredStageId: 'activation-sent',
        requiredReadinessSignalIds: ['activation-link-redeemed'],
        requiredApprovalTypes: [],
        allowSpeculative: false,
        defaultCreditMode: 'execution',
        cleanupTTLHours: 72,
      },
      {
        id: 'verify-downstream-invite-readiness',
        actionType: 'verify-downstream-invite-readiness',
        label: 'Verify downstream invite readiness',
        sideEffectClass: 'reversible-prepare',
        requiredStageId: 'admin-activated',
        requiredReadinessSignalIds: ['activation-link-redeemed'],
        requiredApprovalTypes: [],
        allowSpeculative: false,
        defaultCreditMode: 'execution',
        cleanupTTLHours: 72,
      },
    ],
    defaultOutcomeTemplateIds: [
      'target-qualification-v1',
      'org-shell-provisioning-v1',
      'admin-activation-v1',
      'downstream-invite-readiness-v1',
    ],
    defaultProofTemplateIds: [
      'proof-target-identity-locked-v1',
      'proof-contact-route-confirmed-v1',
      'proof-outreach-sent-v1',
      'proof-interest-confirmed-v1',
      'proof-owner-email-confirmed-v1',
      'proof-activation-link-redeemed-v1',
    ],
    cleanupRules: [
      {
        id: 'cleanup-speculative-shells',
        actionType: 'preprovision-org-team-shell',
        lifecycleState: 'retire-required',
        cleanupTTLHours: 336,
        notes: 'Speculative org/team shells must be retired or converted when readiness regresses or the TTL expires.',
      },
      {
        id: 'cleanup-reserved-admin-memberships',
        actionType: 'reserve-admin-membership',
        lifecycleState: 'retire-required',
        cleanupTTLHours: 336,
        notes: 'Reserved admin memberships must be reconciled once the activation path is either redeemed or abandoned.',
      },
    ],
  });
}

const MISSION_PLAYBOOK_REGISTRY = Object.freeze({
  [EXTERNAL_ACCOUNT_ACTIVATION_PLAYBOOK_ID]: buildExternalAccountActivationPlaybook(),
});

function getMissionPlaybook(playbookId = EXTERNAL_ACCOUNT_ACTIVATION_PLAYBOOK_ID) {
  return MISSION_PLAYBOOK_REGISTRY[normalizeString(playbookId)] || null;
}

function listMissionPlaybooks() {
  return Object.values(MISSION_PLAYBOOK_REGISTRY);
}

function resolveMissionPlaybook(input = {}, fallbackPlaybookId = EXTERNAL_ACCOUNT_ACTIVATION_PLAYBOOK_ID) {
  if (typeof input === 'string') return getMissionPlaybook(input) || getMissionPlaybook(fallbackPlaybookId);
  const playbookId = normalizeString(input.playbookId || input.playbook || input.playbookRef || (input.canary ? fallbackPlaybookId : ''));
  return getMissionPlaybook(playbookId) || (playbookId ? null : getMissionPlaybook(fallbackPlaybookId));
}

module.exports = {
  EXTERNAL_ACCOUNT_ACTIVATION_PLAYBOOK_ID,
  MISSION_PLAYBOOK_REGISTRY,
  buildExternalAccountActivationPlaybook,
  getMissionPlaybook,
  listMissionPlaybooks,
  resolveMissionPlaybook,
};
