import type { ProductHandbook } from '../schema';

export const macraIosHandbook: ProductHandbook = {
  id: 'macra-ios',
  name: 'Macra iOS',
  platform: 'iOS (SwiftUI)',
  summary:
    'Standalone nutrition AI app for macro tracking, food journaling, meal planning, label scanning, supplement tracking, Nora coaching, and subscription-gated access.',
  owner: 'Nutrition Systems + iOS Squad',
  repo: 'Macra',
  releaseChannel: 'TestFlight / App Store release assets',
  status: 'beta',
  keyOutcomes: [
    'Give users a daily macro cockpit that makes food choices easier to understand and act on.',
    'Turn text, voice, meal photos, labels, and meal-plan screenshots into structured nutrition records through Nora.',
    'Keep Macra data isolated from shared Pulse user records except for explicit patch-only access and onboarding fields.',
  ],
  featureInventory: [
    {
      id: 'macra-app-shell',
      name: 'Nutrition Shell and Routing',
      persona: 'Macra users',
      outcome:
        'Route users through auth, onboarding, subscription checks, and the five-tab nutrition shell without losing state.',
      entryPoints: ['Splash', 'Intro', 'Onboarding', 'Home > Journal / Plan / Scan / Supps / More'],
      dependentServices: ['FirebaseService', 'UserService', 'PurchaseService', 'ServiceManager'],
      firestoreCollections: ['users', 'users/{uid}/macra/profile'],
      integrations: ['Firebase Auth', 'RevenueCat'],
      owner: 'Nutrition Systems + iOS Squad',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'App Coordinator', path: '../Macra/Macra/AppCoordinator.swift' },
        { label: 'Content View', path: '../Macra/Macra/ContentView.swift' },
        { label: 'Home Shell', path: '../Macra/Macra/View/Screens/Home/HomeView.swift' },
      ],
    },
    {
      id: 'macra-onboarding-profile',
      name: 'Onboarding and Macra Profile',
      persona: 'New nutrition users',
      outcome:
        'Collect goal, routine, and nutrition context, then save it to the Macra-owned nested profile document.',
      entryPoints: ['Macra onboarding coordinator', 'Meet Nora step', 'Profile setup'],
      dependentServices: ['UserService', 'Firebase Auth', 'Firestore'],
      firestoreCollections: ['users/{uid}/macra/profile', 'users'],
      integrations: ['Firebase Auth'],
      owner: 'Nutrition Systems',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Onboarding Coordinator', path: '../Macra/Macra/Features/Onboarding/MacraOnboardingCoordinator.swift' },
        { label: 'Onboarding Steps', path: '../Macra/Macra/Features/Onboarding/MacraOnboardingSteps.swift' },
        { label: 'Macra User Service', path: '../Macra/Macra/Services/UserService.swift' },
      ],
    },
    {
      id: 'macra-food-journal',
      name: 'Food Journal and Macro Dashboard',
      persona: 'Daily nutrition trackers',
      outcome:
        'Track meals against calorie, protein, carb, and fat targets with a home dashboard, timeline, history, and reusable meal cards.',
      entryPoints: ['Journal tab', 'Log meal sheet', 'Meal history', 'Quick-add from prior meals'],
      dependentServices: ['MealService', 'MacraFoodJournalViewModel', 'NutritionCoreConfiguration'],
      firestoreCollections: ['users/{uid}/mealLogs', 'users/{uid}/pinnedMeals'],
      integrations: ['Firebase Auth', 'Cloud Firestore'],
      owner: 'Nutrition Systems',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Food Journal Core', path: '../Macra/Macra/Features/FoodJournal/MacraFoodJournalCore.swift' },
        { label: 'Meal Service', path: '../Macra/Macra/NutritionCore/Services/MealService.swift' },
        { label: 'Home Surface', path: '../Macra/Macra/View/Screens/Home/HomeView.swift' },
      ],
    },
    {
      id: 'macra-ai-meal-analysis',
      name: 'AI Meal Scan and Text Analysis',
      persona: 'Users who want fast logging',
      outcome:
        'Convert meal photos, text, notes, or voice-derived text into estimated ingredients and macros before saving.',
      entryPoints: ['Scan food', 'Meal note pad', 'Voice entry', 'Image confirmation'],
      dependentServices: ['GPTService', 'MacraOpenAIBridge', 'MealService', 'Firebase Auth'],
      firestoreCollections: ['users/{uid}/mealLogs', 'users/{uid}/pinnedFoodSnaps'],
      integrations: ['OpenAI', 'Netlify Functions', 'Firebase Auth'],
      owner: 'AI Systems + Nutrition Systems',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'GPT Service', path: '../Macra/Macra/Services/GPTService.swift' },
        { label: 'OpenAI Bridge Function', path: 'netlify/functions/openai-bridge.ts' },
        { label: 'Food Journal Capture', path: '../Macra/Macra/Features/FoodJournal/MacraFoodJournalCore.swift' },
      ],
    },
    {
      id: 'macra-label-scanner',
      name: 'Label Scanner and Product Deep Dive',
      persona: 'Grocery shoppers and supplement users',
      outcome:
        'Analyze nutrition or supplement labels, grade the product, persist scan history, and pin repeatable choices.',
      entryPoints: ['Scan tab', 'Label scanner route', 'Pinned label scans', 'Label history'],
      dependentServices: ['LabelScanService', 'LabelSupplementsAIService', 'MacraPinnedScanService', 'Firebase Storage'],
      firestoreCollections: ['users/{uid}/labelScans', 'users/{uid}/pinnedLabelScans'],
      integrations: ['OpenAI', 'Firebase Storage', 'Cloud Firestore'],
      owner: 'Nutrition Systems + AI Systems',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Label Scan Service', path: '../Macra/Macra/NutritionCore/Services/LabelScanService.swift' },
        { label: 'Label AI Service', path: '../Macra/Macra/Features/LabelSupplements/Services/LabelSupplementsAIService.swift' },
        { label: 'Pinned Scan Service', path: '../Macra/Macra/NutritionCore/NutritionCoreSupport.swift' },
      ],
    },
    {
      id: 'macra-meal-planning',
      name: 'Meal Planning and Macro Targets',
      persona: 'Users planning ahead',
      outcome:
        'Create day plans, save macro recommendations, and let Nora turn user context or screenshots into a ready meal plan.',
      entryPoints: ['Plan tab', 'Macro targets', 'Nora plan generation sheet', 'Meal plan editor'],
      dependentServices: ['MealPlanningRootViewModel', 'MacroRecommendationService', 'GPTService', 'generate-macra-meal-plan'],
      firestoreCollections: ['meal-plan', 'macro-profile/{uid}/macro-recommendations', 'generateMealMacros'],
      integrations: ['OpenAI', 'Netlify Functions', 'Cloud Firestore'],
      owner: 'Nutrition Systems + AI Systems',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Meal Planning ViewModels', path: '../Macra/Macra/Features/MealPlanning/MealPlanningViewModels.swift' },
        { label: 'Macro Targets View', path: '../Macra/Macra/Features/MealPlanning/MacroTargetsView.swift' },
        { label: 'Generate Plan Function', path: 'netlify/functions/generate-macra-meal-plan.ts' },
      ],
    },
    {
      id: 'macra-nora-chat',
      name: 'Ask Nora Nutrition Chat',
      persona: 'Users needing day-level guidance',
      outcome:
        'Answer nutrition questions against the current day meals, macro target, goal, and short chat history, then persist the thread by date.',
      entryPoints: ['Journal tab > Ask Nora', 'Daily prompt presets', 'Nora message composer'],
      dependentServices: ['NoraChatService', 'MacraNoraChatService', 'nora-nutrition-chat'],
      firestoreCollections: ['users/{uid}/noraChat', 'users/{uid}/mealLogs'],
      integrations: ['OpenAI', 'Netlify Functions', 'Firebase Auth'],
      owner: 'Nutrition Systems + AI Systems',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Ask Nora UI', path: '../Macra/Macra/View/Screens/Home/HomeView.swift' },
        { label: 'Nora Chat Persistence', path: '../Macra/Macra/Services/MacraNoraChatService.swift' },
        { label: 'Nora Function', path: 'netlify/functions/nora-nutrition-chat.ts' },
      ],
    },
    {
      id: 'macra-supplement-tracker',
      name: 'Supplement Tracker',
      persona: 'Users managing supplements',
      outcome:
        'Store supplement library items, log today intake, and reuse label-derived supplement details.',
      entryPoints: ['Supps tab', 'Supplement editor', 'Supplement checklist'],
      dependentServices: ['SupplementService', 'NutritionSupplementTrackerViewModel', 'LabelSupplementsAIService'],
      firestoreCollections: ['users/{uid}/savedSupplements', 'users/{uid}/supplementLogs'],
      integrations: ['Cloud Firestore', 'OpenAI'],
      owner: 'Nutrition Systems',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Supplement Service', path: '../Macra/Macra/NutritionCore/Services/SupplementService.swift' },
        { label: 'Supplement ViewModel', path: '../Macra/Macra/Features/LabelSupplements/ViewModels/SupplementChecklistViewModel.swift' },
        { label: 'Supplement Models', path: '../Macra/Macra/Features/LabelSupplements/Models/LabelSupplementsModels.swift' },
      ],
    },
    {
      id: 'macra-subscription-access',
      name: 'Subscription and Beta Access',
      persona: 'Free, beta, and paid users',
      outcome:
        'Gate Macra Plus access with RevenueCat, StoreKit, root-user subscription mirrors, and local beta fallback.',
      entryPoints: ['Paywall', 'Manage subscription', 'Post-onboarding route guard'],
      dependentServices: ['PurchaseService', 'RevenueCat Purchases', 'StoreKit', 'UserService'],
      firestoreCollections: ['users'],
      integrations: ['RevenueCat', 'StoreKit', 'Firebase Auth'],
      owner: 'Monetization Team + Nutrition Systems',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Purchase Service', path: '../Macra/Macra/Services/PurchaseService.swift' },
        { label: 'Paywall View', path: '../Macra/Macra/View/Screens/Subscription/PayWallView.swift' },
        { label: 'Macra App Bootstrap', path: '../Macra/Macra/MacraApp.swift' },
      ],
    },
    {
      id: 'macra-release-assets',
      name: 'App Store Screenshot Harness',
      persona: 'Release operators and App Store reviewers',
      outcome:
        'Maintain the locked 6.5-inch screenshot set with dummy data, premium imagery, and App Store Connect-compliant dimensions.',
      entryPoints: ['Playwright screenshot harness', 'System Overview Macra tab', 'App Store Connect upload'],
      dependentServices: ['Playwright', 'Static screenshot HTML', 'public/system-overview assets'],
      firestoreCollections: [],
      integrations: ['Playwright'],
      owner: 'Release Ops + Nutrition Systems',
      releaseChannel: 'App Store submission',
      status: 'active',
      sourceRefs: [
        { label: 'Screenshot Harness', path: '../Macra/scripts/app-store-screenshots/render.mjs' },
        { label: 'Screenshot README', path: '../Macra/scripts/app-store-screenshots/README.md' },
        { label: 'Locked Overview Assets', path: 'public/system-overview/macra/app-store-screenshots' },
      ],
    },
  ],
};
