import type { ProductHandbook } from '../schema';

export const pulseRitualIosHandbook: ProductHandbook = {
  id: 'pulse-ritual-ios',
  name: 'Pulse Ritual iOS',
  platform: 'iOS (SwiftUI)',
  summary:
    'Daily watering layer for human performance — three drops per day (Mind / Body / Fuel) that auto-water from the rest of the Pulse Intelligence Labs portfolio (Pulse Check, Fit With Pulse, Macra). Native SwiftUI app on iOS 16.4+, shares the same Firestore user record as every other PIL product, reads sibling collections directly with no sync layer.',
  owner: 'iOS Squad',
  repo: 'Pulse-Ritual',
  releaseChannel: 'TestFlight / App Store',
  status: 'beta',
  keyOutcomes: [
    'Give users one tiny daily check-in ("did you water yourself today?") that drives retention across the Pulse portfolio.',
    'Reflect a unified picture of cognitive, physical, and nutritional rhythm sourced directly from Pulse Check, Fit With Pulse, and Macra writes.',
    'Hold rhythm without streak shame — a missed day is "roots went dry, not dead." Returning is the win.',
    'Provide a Day 3 conversion moment that converts trial users into Pro by showing their first formed rhythm.',
  ],
  featureInventory: [
    {
      id: 'pulse-ritual-app-shell',
      name: 'Auth + Tab Shell',
      persona: 'New and returning Pulse users',
      outcome:
        'Boot Firebase, gate auth via Sign in with Apple, attach the signed-in user to the shared Pulse Firestore user doc, and route into onboarding or the 4-tab shell.',
      entryPoints: ['App launch', 'Sign in with Apple', 'Tab bar (Today / Rhythm / Garden / You)'],
      dependentServices: ['FirebaseService', 'AuthState', 'AppleSignInService', 'UserService', 'RitualStore'],
      firestoreCollections: ['users'],
      integrations: ['Firebase Auth', 'Sign in with Apple'],
      owner: 'iOS Squad',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'App entry', path: '../Pulse-Ritual/PulseRitual/PulseRitualApp.swift' },
        { label: 'Root nav + session glue', path: '../Pulse-Ritual/PulseRitual/ContentView.swift' },
        { label: 'Firebase config', path: '../Pulse-Ritual/PulseRitual/Services/FirebaseService.swift' },
        { label: 'Apple Sign-In service', path: '../Pulse-Ritual/PulseRitual/Services/AppleSignInService.swift' },
        { label: 'Auth state observer', path: '../Pulse-Ritual/PulseRitual/Store/AuthState.swift' },
      ],
    },
    {
      id: 'pulse-ritual-onboarding',
      name: 'Onboarding Ritual Setup',
      persona: 'First-time Pulse Ritual users',
      outcome:
        'Walk new users through five steps — growing intent, fall-off context, watering windows, seed minimum, and the 3-drop reveal — in under 90 seconds before unlocking the tab shell.',
      entryPoints: ['Post sign-in welcome', 'Onboarding coordinator'],
      dependentServices: ['RitualStore', 'NoraOrb', 'ChipView', 'NotificationsService'],
      firestoreCollections: ['users/{uid}/ritualState'],
      integrations: ['Local Notifications'],
      owner: 'iOS Squad',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Onboarding coordinator', path: '../Pulse-Ritual/PulseRitual/Features/Onboarding/OnboardingCoordinator.swift' },
        { label: 'Reveal screen + notif prompt', path: '../Pulse-Ritual/PulseRitual/Features/Onboarding/RevealView.swift' },
        { label: 'Notifications service', path: '../Pulse-Ritual/PulseRitual/Services/NotificationsService.swift' },
      ],
    },
    {
      id: 'pulse-ritual-today',
      name: 'Today — Plant + 3 Drops',
      persona: 'Daily watering users',
      outcome:
        'Surface the day\'s Mind / Body / Fuel drops with a 4-state animated plant, rain + sparkle on watering, completion banner at three drops, and a Day 3 conversion modal once history is established.',
      entryPoints: ['Today tab', 'Water tap on a drop card', 'Day 3 modal on app open'],
      dependentServices: ['RitualStore', 'PlantView', 'DropCardView', 'RainView', 'SparkleView', 'Day3ModalView', 'InsightService'],
      firestoreCollections: ['users/{uid}/ritualState', 'users/{uid}/ritualHistory'],
      integrations: ['UIKit Haptics'],
      owner: 'iOS Squad',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Today view', path: '../Pulse-Ritual/PulseRitual/Features/Today/TodayView.swift' },
        { label: 'Drop card', path: '../Pulse-Ritual/PulseRitual/Features/Today/DropCardView.swift' },
        { label: 'Animated plant', path: '../Pulse-Ritual/PulseRitual/Components/PlantView.swift' },
        { label: 'Day 3 modal', path: '../Pulse-Ritual/PulseRitual/Features/Today/Day3ModalView.swift' },
      ],
    },
    {
      id: 'pulse-ritual-rhythm',
      name: 'Rhythm — 28-Day Grid + Insights',
      persona: 'Users tracking patterns',
      outcome:
        'Show the user the last 28 days of rhythm as a colour-graded grid, surface real strongest / driest / anchor / return-rate insights computed from history, and allow tapping any cell for a day detail modal.',
      entryPoints: ['Rhythm tab', 'Rhythm grid cell tap → day detail modal'],
      dependentServices: ['RitualStore', 'InsightService', 'DayDetailModalView'],
      firestoreCollections: ['users/{uid}/ritualHistory'],
      integrations: ['UIKit Haptics'],
      owner: 'iOS Squad',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Rhythm view', path: '../Pulse-Ritual/PulseRitual/Features/Rhythm/RhythmView.swift' },
        { label: 'Day detail modal', path: '../Pulse-Ritual/PulseRitual/Features/Rhythm/DayDetailModalView.swift' },
        { label: 'Insight service', path: '../Pulse-Ritual/PulseRitual/Services/InsightService.swift' },
      ],
    },
    {
      id: 'pulse-ritual-garden',
      name: 'Garden — Identity Landscape',
      persona: 'Returning users seeing growth',
      outcome:
        'Render a custom SwiftUI night landscape (sun, stars, birds, hills, flowering tree) as a visual mirror of the user\'s rhythm, plus identity card copy, 3-drop growth bars, and milestone unlocks.',
      entryPoints: ['Garden tab'],
      dependentServices: ['GardenLandscapeView'],
      firestoreCollections: ['users/{uid}/ritualHistory'],
      integrations: [],
      owner: 'iOS Squad',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Garden view', path: '../Pulse-Ritual/PulseRitual/Features/Garden/GardenView.swift' },
        { label: 'Garden landscape', path: '../Pulse-Ritual/PulseRitual/Components/GardenLandscapeView.swift' },
      ],
    },
    {
      id: 'pulse-ritual-you',
      name: 'You — Profile + Connected Apps',
      persona: 'Users managing settings',
      outcome:
        'Render the signed-in user\'s shared Pulse profile (name, handle, since-date), let them toggle the three connection sources (Fit With Pulse, Macra, Pulse Check) that drive auto-watering, surface ritual settings, and offer sign-out.',
      entryPoints: ['You tab'],
      dependentServices: ['RitualStore', 'AuthState', 'UserService'],
      firestoreCollections: ['users'],
      integrations: ['Firebase Auth'],
      owner: 'iOS Squad',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'You view', path: '../Pulse-Ritual/PulseRitual/Features/You/YouView.swift' },
        { label: 'User service', path: '../Pulse-Ritual/PulseRitual/Services/UserService.swift' },
      ],
    },
    {
      id: 'pulse-ritual-state-sync',
      name: 'Cloud State Sync',
      persona: 'Multi-device users',
      outcome:
        'Bidirectional sync of the per-user ritual snapshot (current drops + profile + history) to Firestore. UserDefaults caches the latest snapshot for instant cold-start; the Firestore listener overwrites once authoritative state lands. History rolls over to a per-day document at midnight.',
      entryPoints: ['Background sync on sign-in', 'Every state mutation triggers a write-through'],
      dependentServices: ['RitualStore', 'RitualSyncService'],
      firestoreCollections: ['users/{uid}/ritualState', 'users/{uid}/ritualHistory'],
      integrations: ['Cloud Firestore'],
      owner: 'iOS Squad',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Sync service', path: '../Pulse-Ritual/PulseRitual/Services/RitualSyncService.swift' },
        { label: 'Store', path: '../Pulse-Ritual/PulseRitual/Store/RitualStore.swift' },
      ],
    },
    {
      id: 'pulse-ritual-autowater',
      name: 'Cross-App Auto-Watering',
      persona: 'Pulse portfolio users',
      outcome:
        'Subscribe (read-only, no sync layer) to today\'s documents in three sibling collections — `users/{uid}/mealLogs` (Macra → Fuel), `users/{uid}/workoutSummary` (Fit With Pulse → Body), and `sim-sessions/{uid}/sessions` (Pulse Check → Mind) — and auto-water the matching drop the moment a doc lands. User toggles in the You tab gate which sources are active.',
      entryPoints: ['Snapshot listeners spun up on sign-in', 'Connection toggle re-binds listeners'],
      dependentServices: ['AutoWaterService', 'RitualStore', 'SessionGlue'],
      firestoreCollections: [
        'users/{uid}/mealLogs',
        'users/{uid}/workoutSummary',
        'sim-sessions/{uid}/sessions',
      ],
      integrations: ['Cloud Firestore'],
      owner: 'iOS Squad + Nutrition Systems + PulseCheck',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Auto-water service', path: '../Pulse-Ritual/PulseRitual/Services/AutoWaterService.swift' },
        { label: 'Session glue', path: '../Pulse-Ritual/PulseRitual/ContentView.swift' },
      ],
    },
    {
      id: 'pulse-ritual-notifications',
      name: 'Daily Watering Reminders',
      persona: 'Users with chosen watering windows',
      outcome:
        'Request UNUserNotificationCenter permission on onboarding completion, then schedule repeating daily local notifications at 8am / noon / 6pm aligned with the user\'s chosen Morning / Midday / Evening windows.',
      entryPoints: ['End of onboarding (Reveal screen CTA)', 'Window selection changes'],
      dependentServices: ['NotificationsService'],
      firestoreCollections: [],
      integrations: ['UserNotifications'],
      owner: 'iOS Squad',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Notifications service', path: '../Pulse-Ritual/PulseRitual/Services/NotificationsService.swift' },
      ],
    },
    {
      id: 'pulse-ritual-project-tooling',
      name: 'Project Bootstrap + xcodeproj Automation',
      persona: 'Maintainers',
      outcome:
        'Generate PulseRitual.xcodeproj from scratch via Ruby + the xcodeproj gem (mirrors Macra). New .swift files are registered with `Scripts/add_new_files_to_xcodeproj.rb`. Firebase SPM dependencies and Sign in with Apple capability are wired in the bootstrap script.',
      entryPoints: ['ruby Scripts/bootstrap_xcodeproj.rb', 'ruby Scripts/add_new_files_to_xcodeproj.rb'],
      dependentServices: ['xcodeproj Ruby gem'],
      firestoreCollections: [],
      integrations: [],
      owner: 'iOS Squad',
      releaseChannel: 'Internal tooling',
      status: 'active',
      sourceRefs: [
        { label: 'Bootstrap script', path: '../Pulse-Ritual/Scripts/bootstrap_xcodeproj.rb' },
        { label: 'Add-files script', path: '../Pulse-Ritual/Scripts/add_new_files_to_xcodeproj.rb' },
      ],
    },
  ],
};
