import type { ProductHandbook } from '../schema';

export const pulseCheckAndroidHandbook: ProductHandbook = {
  id: 'pulsecheck-android',
  name: 'Pulse Check Android',
  platform: 'Android (Kotlin / Jetpack Compose)',
  summary:
    'Native Android client inside the unified PulseCheck repository. It shares product contracts, Sports Intelligence, Nora voice selection, mental-skills scoring, commercial access, and Firebase data with iOS and web.',
  owner: 'PulseCheck Team + Android Squad',
  repo: 'PulseCheck',
  releaseChannel: 'Internal beta',
  status: 'beta',
  keyOutcomes: [
    'Maintain athlete experience and data-contract parity with PulseCheck iOS',
    'Deliver Junior and Pro track experiences from the same commercial and team entitlement truth',
    'Use the same Sports Intelligence, Nora narration, mental-skill, coherence, conversation, and support-circle contracts across platforms',
  ],
  featureInventory: [
    {
      id: 'pulsecheck-android-shell-access',
      name: 'Unified App Shell, Authentication, and Access Resolution',
      persona: 'All Android athletes',
      outcome:
        'Launch the correct signed-in experience, redeem team invites, resolve team commercial access, and route the athlete into Junior or Pro track without maintaining a separate Android product model.',
      entryPoints: ['Android app launch', 'Google sign-in', 'PulseCheck invite links'],
      dependentServices: ['PulseCheckAuthClient', 'PulseCheckAccessClient', 'PulseCheckTeamInviteClient', 'PulseCheckSubscriptionClient'],
      firestoreCollections: ['users', 'pulsecheck-team-memberships', 'pulsecheck-teams', 'pulsecheck-organizations'],
      integrations: ['Firebase Auth', 'Cloud Firestore', 'Google Sign-In'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Android Build Configuration', path: '../PulseCheck/android/app/build.gradle.kts' },
        { label: 'Android Manifest', path: '../PulseCheck/android/app/src/main/AndroidManifest.xml' },
        { label: 'Android App Entry', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/MainActivity.kt' },
        { label: 'Parity Foundation and Navigation', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckParityFoundation.kt' },
        { label: 'Authentication Client', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckAuthClient.kt' },
        { label: 'Commercial Access Client', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckAccessClient.kt' },
        { label: 'Team Invite Client', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckTeamInviteClient.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-daily-three-skills',
      name: 'Junior and Pro Daily Three-Skill Experience',
      persona: 'Junior and Pro track athletes',
      outcome:
        'Show the appropriate morning or evening check-in and one skill in each discipline, unlock all three after check-in, and preserve the mature Pro presentation and guided Junior presentation.',
      entryPoints: ['Today tab', 'morning check-in', 'evening check-in', 'daily skill cards'],
      dependentServices: ['PulseCheckCheckInClient', 'PulseCheckTrainingClient', 'PulseCheckJuniorClient', 'PulseCheckYouthTrackClient'],
      firestoreCollections: ['pulsecheck-daily-checkins', 'athlete-mental-progress', 'mental-training-assignments'],
      integrations: ['Cloud Firestore', 'Netlify Functions'],
      owner: 'PulseCheck Team + Curriculum',
      releaseChannel: 'Internal beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Shared Athlete Screens', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckParityScreens.kt' },
        { label: 'Junior Track Screens', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/JuniorTrackScreens.kt' },
        { label: 'Check-In Client', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckCheckInClient.kt' },
        { label: 'Training Client', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckTrainingClient.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-mental-skills-starting-point',
      name: 'Mental Skills Starting Point',
      persona: 'Athletes beginning structured mental training',
      outcome:
        'Match the web and iOS interactive starting-point game with eight-family scoring, unscored current-state context, sport-specific situations, selected Nora narration, server persistence, and one starting skill per discipline.',
      entryPoints: ['Required first-run task', 'signed-in athlete gate'],
      dependentServices: ['MentalSkillsBaselineScorer', 'Sports Intelligence content packs', 'PulseCheckProfileClient', 'NoraVoiceServiceAndroid'],
      firestoreCollections: ['athlete-mental-progress'],
      integrations: ['Firebase Auth', 'Cloud Firestore', 'OpenAI narration bridge'],
      owner: 'PulseCheck Team + Curriculum + Sports Intelligence',
      releaseChannel: 'Internal beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Scoring, Sport Packs, and Save Contract', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/MentalSkillsBaseline.kt' },
        { label: 'Interactive Starting Point', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/MentalSkillsBaselineScreen.kt' },
        { label: 'Completion Gate', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckParityScreens.kt' },
        { label: 'Regression Tests', path: '../PulseCheck/android/app/src/test/java/com/fitwithpulse/pulsecheck/MentalSkillsBaselineTest.kt' },
        { label: 'Experience and Scoring Spec', path: '../PulseCheck/docs/specs/mental-skills-starting-point-spec.md' },
      ],
    },
    {
      id: 'pulsecheck-android-skills-teaching-narration',
      name: 'Skills, Teaching Moments, and Nora Narration',
      persona: 'Athletes completing protocols and simulations',
      outcome:
        'Present exercises as skills, introduce unseen skill types through interactive teaching moments, and narrate screens with the athlete-selected Nora voice.',
      entryPoints: ['Daily skill card', 'skill library', 'first skill-type introduction'],
      dependentServices: ['PulseCheckParityExperience', 'PulseCheckTrainingClient', 'NoraVoiceServiceAndroid'],
      firestoreCollections: ['mental-exercises', 'athlete-mental-progress', 'users'],
      integrations: ['OpenAI narration bridge', 'Android audio playback'],
      owner: 'PulseCheck Team + Curriculum',
      releaseChannel: 'Internal beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Interactive Skill Runtime', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckParityExperience.kt' },
        { label: 'Nora Voice Service', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/NoraVoiceServiceAndroid.kt' },
        { label: 'Training Data Client', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckTrainingClient.kt' },
        { label: 'Teaching Moment Spec', path: '../PulseCheck/docs/specs/exercise-teaching-moments-spec.md' },
      ],
    },
    {
      id: 'pulsecheck-android-conversations-circle',
      name: 'Conversations, Primary Coach, and Support Circle',
      persona: 'Athletes communicating with Nora and team staff',
      outcome:
        'Keep Conversations as the communication tab, provide direct entry to the primary coach, and expose all connected coaches and staff through the athlete support circle.',
      entryPoints: ['Conversations tab', 'Profile support-circle action', 'Ask Nora'],
      dependentServices: ['PulseCheckNoraClient', 'PulseCheckSupportCircleClient'],
      firestoreCollections: ['pulsecheck-nora-conversations', 'pulsecheck-coach-conversations', 'pulsecheck-team-memberships'],
      integrations: ['Cloud Firestore', 'Netlify Functions'],
      owner: 'PulseCheck Team + Coaching',
      releaseChannel: 'Internal beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Nora Conversation Client', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckNoraClient.kt' },
        { label: 'Support Circle Client', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckSupportCircleClient.kt' },
        { label: 'Conversation and Profile Screens', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckParityScreens.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-profile-program-coherence',
      name: 'Profile, Program, and Coherence Progress',
      persona: 'Athletes reviewing progress and current programming',
      outcome:
        'Center controllable progress through coherence, consistency, follow-through, feeling-good patterns, sessions, and current curriculum instead of retired composure, focus, decision, or MPR UI scores.',
      entryPoints: ['Program tab', 'Profile tab'],
      dependentServices: ['PulseCheckProfileClient', 'PulseCheckTrainingClient'],
      firestoreCollections: ['athlete-mental-progress', 'mental-training-assignments', 'pulsecheck-daily-checkins'],
      integrations: ['Cloud Firestore'],
      owner: 'PulseCheck Team + Mental Performance',
      releaseChannel: 'Internal beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Profile Data Client', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckProfileClient.kt' },
        { label: 'Program and Profile Screens', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckParityScreens.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-sports-intelligence',
      name: 'Sports Intelligence Personalization and Sport Guide',
      persona: 'Athletes receiving sport-specific mental training',
      outcome:
        'Resolve the athlete sport, apply sport-correct event and scenario language, show personalization badges, and provide a sport deep dive with skills, secrets, tips, and examples of great performers.',
      entryPoints: ['Personalized skill screens', 'sport card in Profile'],
      dependentServices: ['PulseCheckSportsIntelClient', 'sport scenario packs'],
      firestoreCollections: ['users', 'sports-intelligence'],
      integrations: ['Cloud Firestore'],
      owner: 'PulseCheck Sports Intelligence',
      releaseChannel: 'Internal beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Sports Intelligence Client', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckSportsIntelClient.kt' },
        { label: 'Sports Intelligence Experience', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckParityExperience.kt' },
        { label: 'Sports Intelligence Source of Truth', path: '../PulseCheck/docs/specs/sports-intelligence-source-of-truth-spec.md' },
        { label: 'Sport Scenario Pack Spec', path: '../PulseCheck/docs/specs/sport-scenario-packs-spec.md' },
      ],
    },
    {
      id: 'pulsecheck-android-health-safety-reminders',
      name: 'Wearables, Recovery Context, Safety, and Reminders',
      persona: 'Athletes using connected health data and daily support',
      outcome:
        'Read permitted Health Connect and wearable data as context, schedule daily check-in reminders, and preserve the crisis-wall and safety-access path.',
      entryPoints: ['Wearable settings', 'Energy Reset', 'daily reminders', 'safety route'],
      dependentServices: ['PulseCheckHealthConnectClient', 'PulseCheckWearableAuthClient', 'PulseCheckCrisisWallClient', 'PulseCheckDailyReminderScheduler'],
      firestoreCollections: ['users', 'wearable-connections', 'athlete-mental-progress'],
      integrations: ['Health Connect', 'Android notifications', 'Fitbit and wearable OAuth'],
      owner: 'PulseCheck Team + Safety',
      releaseChannel: 'Internal beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Health Connect Client', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckHealthConnectClient.kt' },
        { label: 'Wearable Authorization Client', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckWearableAuthClient.kt' },
        { label: 'Crisis Wall Client', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckCrisisWallClient.kt' },
        { label: 'Daily Reminder Scheduler', path: '../PulseCheck/android/app/src/main/java/com/fitwithpulse/pulsecheck/PulseCheckDailyReminderScheduler.kt' },
      ],
    },
  ],
};
