import type { ProductHandbook } from '../schema';

export const pulseCheckIosHandbook: ProductHandbook = {
  id: 'pulsecheck-ios',
  name: 'Pulse Check iOS',
  platform: 'iOS (SwiftUI)',
  summary:
    'White-glove elite athlete service technology for mental performance, readiness, coach visibility, protocols, pilot operations, and governed athlete support.',
  owner: 'PulseCheck Team',
  repo: 'PulseCheck',
  releaseChannel: 'App Store beta + internal TestFlight',
  status: 'active',
  keyOutcomes: [
    'Elite athlete readiness and mental-performance support',
    'Coach and operator visibility for white-glove service delivery',
    'Protocol, simulation, and longitudinal intervention loops governed by evidence and safety posture',
  ],
  featureInventory: [
    {
      id: 'pulsecheck-onboarding-chat',
      name: 'Chat-Led Onboarding',
      persona: 'New athletes',
      outcome: 'Collect baseline identity, mood, and goals without a rigid form onboarding flow.',
      entryPoints: ['Nora onboarding view', 'First-launch conversation'],
      dependentServices: ['Firebase Auth', 'Conversation services'],
      firestoreCollections: ['pulseCheck_profiles', 'conversations'],
      integrations: ['OpenAI'],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Nora Onboarding', path: '../PulseCheck/PulseCheck/Views/Onboarding/NoraOnboardingView.swift' },
        { label: 'PulseCheck App', path: '../PulseCheck/PulseCheck/PulseCheckApp.swift' },
      ],
    },
    {
      id: 'pulsecheck-conversation-core',
      name: 'Conversation Interface and Coaching Responses',
      persona: 'Athletes in active mental coaching',
      outcome: 'Enable real-time conversational coaching with context-aware responses.',
      entryPoints: ['Main chat view', 'Input area', 'action cards'],
      dependentServices: ['Conversation service', 'message pipeline'],
      firestoreCollections: ['conversations', 'conversations/{id}/messages'],
      integrations: ['OpenAI'],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Chat View', path: '../PulseCheck/PulseCheck/Views/Chat/ChatView.swift' },
        { label: 'Chat Bubble', path: '../PulseCheck/PulseCheck/Views/Chat/ChatBubbleView.swift' },
      ],
    },
    {
      id: 'pulsecheck-mental-notes',
      name: 'Mental Notes Detection and Tracking',
      persona: 'Athletes and coaches',
      outcome: 'Detect recurring concerns and track severity/status over time.',
      entryPoints: ['Mental notes bar', 'mental note detail modal', 'coach insight surfaces'],
      dependentServices: ['Mental note service', 'conversation analyzer'],
      firestoreCollections: ['mental-notes', 'conversations'],
      integrations: ['OpenAI'],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Mental Notes Bar', path: '../PulseCheck/PulseCheck/Views/Chat/MentalNotesBar.swift' },
        { label: 'Mental Note Detail', path: '../PulseCheck/PulseCheck/Views/Chat/MentalNoteDetailModal.swift' },
      ],
    },
    {
      id: 'pulsecheck-proactive-insights',
      name: 'Proactive Insight Cards',
      persona: 'Athletes',
      outcome: 'Surface actionable prompts before performance or wellness decline compounds.',
      entryPoints: ['Main tab cards', 'health story cards'],
      dependentServices: ['Insight generation layer', 'profile services'],
      firestoreCollections: ['mental-notes', 'users/{uid}/health-data'],
      integrations: ['OpenAI'],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Proactive Card', path: '../PulseCheck/PulseCheck/Views/Components/ProactiveHealthInsightCard.swift' },
        { label: 'Health Story Card', path: '../PulseCheck/PulseCheck/Views/Components/HealthStoryCard.swift' },
      ],
    },
    {
      id: 'pulsecheck-baseline-assessment',
      name: 'Baseline Assessment and Curriculum Assignment',
      persona: 'Athletes in structured mental training',
      outcome: 'Assess current state and assign a curriculum path with exercise recommendations.',
      entryPoints: ['Mental training baseline assessment', 'curriculum assignment views'],
      dependentServices: ['Mental training service', 'curriculum logic'],
      firestoreCollections: ['mental-training-assignments', 'users/{uid}/mental-progress'],
      integrations: [],
      owner: 'PulseCheck Team + Mental Performance',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Baseline Assessment', path: '../PulseCheck/PulseCheck/Views/MentalTraining/BaselineAssessmentView.swift' },
        { label: 'Curriculum Assignment', path: '../PulseCheck/PulseCheck/Views/MentalTraining/CurriculumAssignmentView.swift' },
      ],
    },
    {
      id: 'pulsecheck-athlete-task-gate',
      name: 'Athlete Task Gate and Baseline Unlock',
      persona: 'Team-invited athletes',
      outcome:
        'Keep training locked until consent and a baseline are complete, accepting either web baselineAssessment or native baselineProbe evidence.',
      entryPoints: ['PulseCheck team invite entry', 'team workspace', 'Nora Daily'],
      dependentServices: ['Athlete task state resolver', 'PulseCheck provisioning access state', 'mental progress service'],
      firestoreCollections: [
        'pulsecheck-team-memberships',
        'pulsecheck-pilot-enrollments',
        'athlete-mental-progress',
      ],
      integrations: ['Firebase Auth', 'Cloud Firestore'],
      owner: 'PulseCheck Team + Platform',
      releaseChannel: 'Pilot',
      status: 'active',
      sourceRefs: [
        { label: 'Athlete Task State', path: 'src/api/firebase/pulsecheckProvisioning/athleteTaskState.ts' },
        { label: 'Access State', path: 'src/api/firebase/pulsecheckProvisioning/accessState.ts' },
        { label: 'Team Invite Entry', path: '../PulseCheck/PulseCheck/Views/Onboarding/PulseCheckPilotInviteEntryView.swift' },
        { label: 'Nora Daily View', path: '../PulseCheck/PulseCheck/Views/Chat/NoraDailyView.swift' },
      ],
    },
    {
      id: 'pulsecheck-ios-nora-conversation-inbox',
      name: 'Nora Conversation Inbox and Reply Surface',
      persona: 'Athletes receiving reactive Nora check-ins',
      outcome:
        'Show guardrail-reviewed Nora conversation threads, let athletes reply, and let the server advance the conversation state machine.',
      entryPoints: ['Nora tab', 'nora_conversation push tap', 'Today screen Nora card'],
      dependentServices: ['NoraConversationService', 'nora-athlete-reply', 'pulsecheck-nora-conversations listener'],
      firestoreCollections: ['pulsecheck-nora-conversations'],
      integrations: ['Firebase Auth', 'Cloud Firestore', 'Netlify Functions', 'Push Notifications'],
      owner: 'PulseCheck iOS + PulseCheck Platform',
      releaseChannel: 'Pilot',
      status: 'active',
      sourceRefs: [
        { label: 'Nora Conversation Service', path: '../PulseCheck/PulseCheck/Services/NoraConversationService.swift' },
        { label: 'Nora Inbox View', path: '../PulseCheck/PulseCheck/Views/NoraInboxView.swift' },
        { label: 'Athlete Reply Function', path: 'netlify/functions/nora-athlete-reply.ts' },
      ],
    },
    {
      id: 'pulsecheck-ios-daily-curriculum-reader',
      name: 'Daily Curriculum Reader',
      persona: 'Athletes with curriculum-engine assignments',
      outcome:
        'Listen for today’s curriculum-engine protocol and simulation assignments without exposing engine internals to the athlete.',
      entryPoints: ['Today view', 'Nora Daily', 'Training Room handoff'],
      dependentServices: ['DailyCurriculumReader', 'pulsecheck-daily-assignments listener'],
      firestoreCollections: ['pulsecheck-daily-assignments'],
      integrations: ['Cloud Firestore'],
      owner: 'PulseCheck iOS + Mental Performance',
      releaseChannel: 'Pilot',
      status: 'active',
      sourceRefs: [
        { label: 'Daily Curriculum Reader', path: '../PulseCheck/PulseCheck/Services/DailyCurriculumReader.swift' },
        { label: 'Nora Daily View', path: '../PulseCheck/PulseCheck/Views/Chat/NoraDailyView.swift' },
        { label: 'Daily Curriculum Spec', path: 'src/components/admin/system-overview/PulseCheckCurriculumLayerSpecTab.tsx' },
      ],
    },
    {
      id: 'pulsecheck-junior-daily-state-loop',
      name: 'Junior Daily State Loop and Energy Recalibration',
      persona: 'Junior-track athletes',
      outcome:
        'Join morning and evening check-ins, same-day answer changes, assigned training, drained-state awareness, silent recovery routing, symptom follow-up, and internal recalibration into one athlete-local day.',
      entryPoints: ['Junior Home morning card', 'Junior Home evening card', 'Help Me Reset'],
      dependentServices: [
        'JuniorCheckInCard',
        'JuniorEnergyResetView',
        'record-morning-checkin',
        'record-evening-checkin',
        'record-checkin-signal-alignment',
      ],
      firestoreCollections: ['pulsecheck-morning-checkins', 'athlete-state-signal-alignments', 'junior-progress'],
      integrations: ['Cloud Firestore', 'Canonical Health Context Snapshot', 'Fitbit via Google Health'],
      owner: 'PulseCheck iOS + PulseCheck Platform + Safety',
      releaseChannel: 'Junior Track beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Athlete Daily State Loop', path: 'src/components/admin/system-overview/PulseCheckAthleteDailyStateLoopTab.tsx' },
        { label: 'Junior Check-In Card', path: '../PulseCheck/PulseCheck/Views/Junior/JuniorCheckInCard.swift' },
        { label: 'Energy Recalibration', path: '../PulseCheck/PulseCheck/Views/Junior/JuniorEnergyResetView.swift' },
        { label: 'Morning Endpoint', path: 'netlify/functions/record-morning-checkin.ts' },
        { label: 'Evening Endpoint', path: 'netlify/functions/record-evening-checkin.ts' },
      ],
    },
    {
      id: 'pulsecheck-exercise-library',
      name: 'Mental Exercise Library and Player',
      persona: 'Athletes executing mental drills',
      outcome: 'Browse and run structured mental exercises tied to assigned curriculum.',
      entryPoints: ['Exercise library', 'generic exercise player'],
      dependentServices: ['Exercise library service', 'progress tracker'],
      firestoreCollections: ['mental-training-library', 'users/{uid}/mental-progress'],
      integrations: [],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Exercise Library', path: '../PulseCheck/PulseCheck/Views/MentalTraining/ExerciseLibraryView.swift' },
        { label: 'Exercise Player', path: '../PulseCheck/PulseCheck/Views/MentalTraining/GenericExercisePlayerView.swift' },
      ],
    },
    {
      id: 'pulsecheck-exercise-teaching-moments',
      name: 'Exercise Teaching Moments',
      persona: 'Athletes encountering a mental-training family for the first time',
      outcome:
        'Teach why an exercise matters through three narrated, animated, captioned scenes before automatically handing off into training.',
      entryPoints: ['Exercise launch gate', 'Screen Demo teaching-moment gallery'],
      dependentServices: ['Exercise teaching-family registry', 'teaching progress store', 'narration preload/cache'],
      firestoreCollections: ['mental-training-education-progress'],
      integrations: ['Cloud Firestore', 'Narration audio'],
      owner: 'PulseCheck iOS + Mental Performance Education',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Teaching Moments Spec', path: '../PulseCheck/docs/specs/exercise-teaching-moments-spec.md' },
        { label: 'Teaching Moment Model', path: '../PulseCheck/PulseCheck/Models/ExerciseTeachingMoment.swift' },
        { label: 'Teaching Journey', path: '../PulseCheck/PulseCheck/Views/MentalTraining/ExerciseTeachingMomentView.swift' },
        { label: 'Overview Artifact', path: 'src/components/admin/system-overview/PulseCheckExerciseTeachingMomentsTab.tsx' },
      ],
    },
    {
      id: 'pulsecheck-sport-scenario-personalization',
      name: 'Sport-Native Exercise Scenario Personalization',
      persona: 'Athletes running Sports Intelligence-enabled modules',
      outcome:
        'Resolve the athlete sport, event, position, or division into sport-native situations, vocabulary, visible personalization labels, and traceable scenario evidence.',
      entryPoints: ['Today module cards', 'module detail and intro', 'interactive scenario rounds'],
      dependentServices: ['Sport scenario archetype registry', 'SportsEventVocabulary', 'sport scenario packs', 'Sports Intelligence catalog'],
      firestoreCollections: ['company-config/pulsecheck-sports', 'mental-exercise-completions'],
      integrations: ['Cloud Firestore'],
      owner: 'PulseCheck iOS + Sports Intelligence',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Scenario Pack Spec', path: '../PulseCheck/docs/specs/sport-scenario-packs-spec.md' },
        { label: 'Source Of Truth Spec', path: '../PulseCheck/docs/specs/sports-intelligence-source-of-truth-spec.md' },
        { label: 'Scenario Archetypes', path: 'src/api/firebase/mentaltraining/sportScenarioArchetypes.ts' },
        { label: 'Catalog Coverage Tests', path: 'tests/unit/sport-catalog-coverage.test.ts' },
      ],
    },
    {
      id: 'pulsecheck-signal-window-cue-runtime',
      name: 'Signal Window Sport-Aware Cue Runtime',
      persona: 'Athletes training signal discrimination and commitment timing',
      outcome:
        'Train the athlete to wait through a false cue, identify a valid sport-themed cue, and commit inside a narrowing response window.',
      entryPoints: ['Assigned simulation', 'Training Room', 'Screen Demo'],
      dependentServices: ['Simulation runtime engine', 'Sports Intelligence sport resolver', 'simulation completion writer'],
      firestoreCollections: ['mental-exercise-completions', 'sim-session-records'],
      integrations: [],
      owner: 'PulseCheck iOS + Simulation Science',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Signal Window Spec', path: 'src/components/admin/system-overview/SignalWindowSpecTab.tsx' },
        { label: 'Runtime Engine Views', path: '../PulseCheck/PulseCheck/Views/MentalTraining/SimRuntimeEngineViews.swift' },
      ],
    },
    {
      id: 'pulsecheck-coach-connection',
      name: 'Coach Connection and Messaging',
      persona: 'Athletes with performance staff',
      outcome: 'Connect athlete accounts to coaches and expose communication/session access.',
      entryPoints: ['Coach connection view', 'coach messaging', 'booking view'],
      dependentServices: ['Coach relationship service', 'messaging layer'],
      firestoreCollections: ['coach_dashboards', 'coach-athlete-links', 'conversations'],
      integrations: ['Scheduling links'],
      owner: 'Coach Platform + PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Coach Connection', path: '../PulseCheck/PulseCheck/Views/Coach/CoachConnectionView.swift' },
        { label: 'Coach Messaging', path: '../PulseCheck/PulseCheck/Views/Coach/CoachMessagingView.swift' },
      ],
    },
    {
      id: 'pulsecheck-health-stories',
      name: 'Health Story Surface',
      persona: 'Athletes and coaches',
      outcome: 'Translate mental and physical context into readable trend narratives.',
      entryPoints: ['Health story cards', 'profile insight views'],
      dependentServices: ['Health aggregation service', 'insight renderer'],
      firestoreCollections: ['users/{uid}/health-data', 'users/{uid}/mental-progress'],
      integrations: ['HealthKit (permissioned)'],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Health Story Test View', path: '../PulseCheck/PulseCheck/Views/HealthStoryTestView.swift' },
        { label: 'Insights Section', path: '../PulseCheck/PulseCheck/Views/ProfileSections/InsightsSection.swift' },
      ],
    },
    {
      id: 'pulsecheck-profile-readiness',
      name: 'Athlete Coherence Profile',
      persona: 'Athletes',
      outcome:
        'Center controllable progress through Consistency, Follow-through, Feeling Good, and Overall Coherence while keeping module-level performance evidence available beneath the primary athlete view.',
      entryPoints: ['User profile', 'overview/performance/biometrics sections'],
      dependentServices: ['AthleteCoherenceService', 'profile service', 'check-in history', 'assignment and completion history'],
      firestoreCollections: ['users/{uid}', 'pulsecheck-morning-checkins', 'mental-exercise-completions', 'junior-progress'],
      integrations: [],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'User Profile View', path: '../PulseCheck/PulseCheck/Views/UserProfileView.swift' },
        { label: 'Athlete Coherence Service', path: '../PulseCheck/PulseCheck/Services/AthleteCoherenceService.swift' },
        { label: 'Coherence Progress Card', path: '../PulseCheck/PulseCheck/Views/Components/AthleteCoherenceProgressCard.swift' },
        { label: 'Profile Architecture', path: 'src/components/admin/system-overview/PulseCheckProfileArchitectureTab.tsx' },
      ],
    },
    {
      id: 'pulsecheck-sports-intel-screen',
      name: 'Unified Sports Intel Screen (Device-Agnostic)',
      persona: 'Athletes',
      outcome:
        'Replace the Polar-only device detail screen with one aggregated Sports Intel read that accepts any connected performance device (Polar, Fitbit Air via Google Health, Oura Ring, Apple Watch), takes the best source per metric from the canonical snapshot merge, and shows per-metric "via <device>" source tags plus the sport-aware Nora read.',
      entryPoints: [
        'Home "N devices live" strip (NoraDailyView)',
        'Your Devices sheet — every connected device card (WearablePickerSheet)',
      ],
      dependentServices: [
        'Health context snapshot assembler (DOMAIN_PRECEDENCE per-domain source precedence)',
        'HealthContextSnapshotReader (iOS canonical snapshot reads)',
        'SportsIntelligenceReasoningLayer (sport-aware read generation)',
        'SportsIntelComposer (snapshot → source-attributed metric rows)',
        'PolarBleService (live-HR overlay, Polar signature device, today only)',
      ],
      firestoreCollections: ['health-context-snapshots', 'health-context-source-records', 'users/{uid}'],
      integrations: ['Polar AccessLink + BLE', 'Google Health (Fitbit Air)', 'Oura Cloud', 'HealthKit'],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Sports Intel Generalization Spec', path: '../PulseCheck/docs/specs/sports-intel-generalization-spec.md' },
        { label: 'Sports Intel Models + Composer', path: '../PulseCheck/PulseCheck/Models/SportsIntelModels.swift' },
        { label: 'Sports Intel View Model', path: '../PulseCheck/PulseCheck/ViewModels/SportsIntelViewModel.swift' },
        { label: 'Sports Intel View', path: '../PulseCheck/PulseCheck/Views/SportsIntel/SportsIntelView.swift' },
        { label: 'Domain Precedence (priority list)', path: '../QuickLifts-Web/src/api/firebase/healthContextSnapshotAssembler.ts' },
        { label: 'Legacy Polar Detail Screen (retiring after parity)', path: '../PulseCheck/PulseCheck/Views/Settings/PolarDataDumpView.swift' },
      ],
    },
    {
      id: 'pulsecheck-profile-snapshots-export',
      name: 'Canonical Profile Snapshot Pipeline',
      persona: 'Athletes, staff, and research operators',
      outcome: 'Persist milestone-based canonical profile snapshots with revision history and export them through a stable research-safe contract.',
      entryPoints: ['Baseline completion', 'midpoint and endpoint trials', 'retention trials', 'admin research export'],
      dependentServices: ['Athlete progress service', 'profile snapshot writer', 'research export service'],
      firestoreCollections: [
        'athlete-mental-progress',
        'athlete-mental-progress/{uid}/profile-snapshots',
        'research-export-jobs',
      ],
      integrations: [],
      owner: 'PulseCheck Team + Mental Performance',
      releaseChannel: 'Planned',
      status: 'planned',
      sourceRefs: [
        { label: 'Profile Snapshot & Export Spec', path: '../QuickLifts-Web/src/components/admin/system-overview/PulseCheckProfileSnapshotExportSpecTab.tsx' },
        { label: 'Athlete Progress Service', path: '../QuickLifts-Web/src/api/firebase/mentaltraining/athleteProgressService.ts' },
      ],
    },
    {
      id: 'pulsecheck-athlete-showroom-avatar',
      name: 'Optional Multi-View 3D Athlete Avatar',
      persona: 'Athletes who want a premium profile identity surface',
      outcome:
        'Let athletes optionally create a personalized 3D profile avatar from front, left-side, back, and right-side full-body captures, rendered in the Profile showroom without affecting onboarding or product access.',
      entryPoints: ['Profile image area only', 'Avatar settings from Profile'],
      dependentServices: ['Avatar capture validator', 'Avatar upload service', 'Avatar generation job service', 'RealityKit showroom renderer'],
      firestoreCollections: ['users/{uid}.avatarShowroom', 'profile-avatars/{uid}/sessions/{sessionId}'],
      integrations: ['Apple Vision', 'RealityKit', 'Firebase Storage', 'backend avatar generation pipeline'],
      owner: 'PulseCheck Team + Platform + 3D Generation',
      releaseChannel: 'Planned optional profile feature',
      status: 'planned',
      sourceRefs: [
        { label: 'Avatar Spec', path: '../PulseCheck/docs/specs/athlete-showroom-avatar.md' },
        { label: 'Avatar Implementation Plan', path: '../PulseCheck/docs/specs/athlete-showroom-avatar-implementation-plan.md' },
        { label: 'Profile View', path: '../PulseCheck/PulseCheck/Views/UserProfileView.swift' },
      ],
    },
    {
      id: 'pulsecheck-daily-reflection-settings',
      name: 'Daily Reflection and Settings Controls',
      persona: 'Athletes',
      outcome: 'Configure cadence, privacy, and reflective prompts for consistent mental check-ins.',
      entryPoints: ['Settings view', 'daily reflection settings'],
      dependentServices: ['Settings service', 'notifications'],
      firestoreCollections: ['users/{uid}/preferences'],
      integrations: ['Push Notifications'],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Settings View', path: '../PulseCheck/PulseCheck/Views/Settings/SettingsView.swift' },
        { label: 'Daily Reflection Settings', path: '../PulseCheck/PulseCheck/Views/Settings/DailyReflectionSettingsView.swift' },
      ],
    },
    {
      id: 'pulsecheck-subscription-access',
      name: 'Pulse Check Subscription Access',
      persona: 'Athletes entering premium coaching loops',
      outcome: 'Gate paid features and align entitlement status with ecosystem subscriptions.',
      entryPoints: ['Subscription modal', 'subscription plans in chat'],
      dependentServices: ['Subscription entitlement service', 'auth'],
      firestoreCollections: ['users', 'subscriptionRecords'],
      integrations: ['RevenueCat', 'Stripe'],
      owner: 'Monetization Team',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Subscription View', path: '../PulseCheck/PulseCheck/Views/Subscription/SubscriptionView.swift' },
        { label: 'Subscription Card', path: '../PulseCheck/PulseCheck/Views/Chat/SubscriptionPlansCardContent.swift' },
      ],
    },
    {
      id: 'pulsecheck-privacy-consent',
      name: 'Privacy Consent Flow and Consent v6',
      persona: 'All Pulse Check users',
      outcome:
        'Capture product consent plus pilot/research required documents, and re-prompt athletes when stored pilot consent versions are older than the current v6 documents.',
      entryPoints: ['Privacy consent modal', 'chat consent card', 'athlete onboarding consent step', 'pilot/team invite redemption'],
      dependentServices: ['PulseCheck provisioning access state', 'team invite redemption API', 'consent PDF renderer'],
      firestoreCollections: ['pulsecheck-team-memberships', 'pulsecheck-pilot-enrollments', 'users/{uid}/consents'],
      integrations: [],
      owner: 'PulseCheck Team + Legal Ops',
      releaseChannel: 'Pilot',
      status: 'active',
      sourceRefs: [
        { label: 'Privacy Consent Modal', path: '../PulseCheck/PulseCheck/Views/Components/PrivacyConsentModal.swift' },
        { label: 'Consent Card Content', path: '../PulseCheck/PulseCheck/Views/Chat/PrivacyConsentCardContent.swift' },
        { label: 'Provisioning Consent Types', path: 'src/api/firebase/pulsecheckProvisioning/types.ts' },
        { label: 'Consent Access State', path: 'src/api/firebase/pulsecheckProvisioning/accessState.ts' },
        { label: 'Consent v6 Tests', path: 'tests/unit/pulsecheck-consent-access-state.test.ts' },
      ],
    },
  ],
};
