import type { ProductHandbook } from '../schema';

export const pulseCheckIosHandbook: ProductHandbook = {
  id: 'pulsecheck-ios',
  name: 'Pulse Check iOS',
  platform: 'iOS (SwiftUI)',
  summary:
    'White-glove elite athlete service technology for mental performance, readiness, coach visibility, protocols, pilot operations, and governed athlete support.',
  owner: 'PulseCheck Team',
  repo: 'PulseCheck',
  releaseChannel: 'App Store beta + internal TestFlight',
  status: 'active',
  keyOutcomes: [
    'Elite athlete readiness and mental-performance support',
    'Coach and operator visibility for white-glove service delivery',
    'Protocol, simulation, and longitudinal intervention loops governed by evidence and safety posture',
  ],
  featureInventory: [
    {
      id: 'pulsecheck-onboarding-chat',
      name: 'Chat-Led Onboarding',
      persona: 'New athletes',
      outcome: 'Collect baseline identity, mood, and goals without a rigid form onboarding flow.',
      entryPoints: ['Nora onboarding view', 'First-launch conversation'],
      dependentServices: ['Firebase Auth', 'Conversation services'],
      firestoreCollections: ['pulseCheck_profiles', 'conversations'],
      integrations: ['OpenAI'],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Nora Onboarding', path: '../PulseCheck/PulseCheck/Views/Onboarding/NoraOnboardingView.swift' },
        { label: 'PulseCheck App', path: '../PulseCheck/PulseCheck/PulseCheckApp.swift' },
      ],
    },
    {
      id: 'pulsecheck-conversation-core',
      name: 'Conversation Interface and Coaching Responses',
      persona: 'Athletes in active mental coaching',
      outcome: 'Enable real-time conversational coaching with context-aware responses.',
      entryPoints: ['Main chat view', 'Input area', 'action cards'],
      dependentServices: ['Conversation service', 'message pipeline'],
      firestoreCollections: ['conversations', 'conversations/{id}/messages'],
      integrations: ['OpenAI'],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Chat View', path: '../PulseCheck/PulseCheck/Views/Chat/ChatView.swift' },
        { label: 'Chat Bubble', path: '../PulseCheck/PulseCheck/Views/Chat/ChatBubbleView.swift' },
      ],
    },
    {
      id: 'pulsecheck-mental-notes',
      name: 'Mental Notes Detection and Tracking',
      persona: 'Athletes and coaches',
      outcome: 'Detect recurring concerns and track severity/status over time.',
      entryPoints: ['Mental notes bar', 'mental note detail modal', 'coach insight surfaces'],
      dependentServices: ['Mental note service', 'conversation analyzer'],
      firestoreCollections: ['mental-notes', 'conversations'],
      integrations: ['OpenAI'],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Mental Notes Bar', path: '../PulseCheck/PulseCheck/Views/Chat/MentalNotesBar.swift' },
        { label: 'Mental Note Detail', path: '../PulseCheck/PulseCheck/Views/Chat/MentalNoteDetailModal.swift' },
      ],
    },
    {
      id: 'pulsecheck-proactive-insights',
      name: 'Proactive Insight Cards',
      persona: 'Athletes',
      outcome: 'Surface actionable prompts before performance or wellness decline compounds.',
      entryPoints: ['Main tab cards', 'health story cards'],
      dependentServices: ['Insight generation layer', 'profile services'],
      firestoreCollections: ['mental-notes', 'users/{uid}/health-data'],
      integrations: ['OpenAI'],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Proactive Card', path: '../PulseCheck/PulseCheck/Views/Components/ProactiveHealthInsightCard.swift' },
        { label: 'Health Story Card', path: '../PulseCheck/PulseCheck/Views/Components/HealthStoryCard.swift' },
      ],
    },
    {
      id: 'pulsecheck-baseline-assessment',
      name: 'Baseline Assessment and Curriculum Assignment',
      persona: 'Athletes in structured mental training',
      outcome: 'Assess current state and assign a curriculum path with exercise recommendations.',
      entryPoints: ['Mental training baseline assessment', 'curriculum assignment views'],
      dependentServices: ['Mental training service', 'curriculum logic'],
      firestoreCollections: ['mental-training-assignments', 'users/{uid}/mental-progress'],
      integrations: [],
      owner: 'PulseCheck Team + Mental Performance',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Baseline Assessment', path: '../PulseCheck/PulseCheck/Views/MentalTraining/BaselineAssessmentView.swift' },
        { label: 'Curriculum Assignment', path: '../PulseCheck/PulseCheck/Views/MentalTraining/CurriculumAssignmentView.swift' },
      ],
    },
    {
      id: 'pulsecheck-athlete-task-gate',
      name: 'Athlete Task Gate and Baseline Unlock',
      persona: 'Team-invited athletes',
      outcome:
        'Keep training locked until consent and a baseline are complete, accepting either web baselineAssessment or native baselineProbe evidence.',
      entryPoints: ['PulseCheck team invite entry', 'team workspace', 'Nora Daily'],
      dependentServices: ['Athlete task state resolver', 'PulseCheck provisioning access state', 'mental progress service'],
      firestoreCollections: [
        'pulsecheck-team-memberships',
        'pulsecheck-pilot-enrollments',
        'athlete-mental-progress',
      ],
      integrations: ['Firebase Auth', 'Cloud Firestore'],
      owner: 'PulseCheck Team + Platform',
      releaseChannel: 'Pilot',
      status: 'active',
      sourceRefs: [
        { label: 'Athlete Task State', path: 'src/api/firebase/pulsecheckProvisioning/athleteTaskState.ts' },
        { label: 'Access State', path: 'src/api/firebase/pulsecheckProvisioning/accessState.ts' },
        { label: 'Team Invite Entry', path: '../PulseCheck/PulseCheck/Views/Onboarding/PulseCheckPilotInviteEntryView.swift' },
        { label: 'Nora Daily View', path: '../PulseCheck/PulseCheck/Views/Chat/NoraDailyView.swift' },
      ],
    },
    {
      id: 'pulsecheck-ios-nora-conversation-inbox',
      name: 'Nora Conversation Inbox and Reply Surface',
      persona: 'Athletes receiving reactive Nora check-ins',
      outcome:
        'Show guardrail-reviewed Nora conversation threads, let athletes reply, and let the server advance the conversation state machine.',
      entryPoints: ['Nora tab', 'nora_conversation push tap', 'Today screen Nora card'],
      dependentServices: ['NoraConversationService', 'nora-athlete-reply', 'pulsecheck-nora-conversations listener'],
      firestoreCollections: ['pulsecheck-nora-conversations'],
      integrations: ['Firebase Auth', 'Cloud Firestore', 'Netlify Functions', 'Push Notifications'],
      owner: 'PulseCheck iOS + PulseCheck Platform',
      releaseChannel: 'Pilot',
      status: 'active',
      sourceRefs: [
        { label: 'Nora Conversation Service', path: '../PulseCheck/PulseCheck/Services/NoraConversationService.swift' },
        { label: 'Nora Inbox View', path: '../PulseCheck/PulseCheck/Views/NoraInboxView.swift' },
        { label: 'Athlete Reply Function', path: 'netlify/functions/nora-athlete-reply.ts' },
      ],
    },
    {
      id: 'pulsecheck-ios-daily-curriculum-reader',
      name: 'Daily Curriculum Reader',
      persona: 'Athletes with curriculum-engine assignments',
      outcome:
        'Listen for today’s curriculum-engine protocol and simulation assignments without exposing engine internals to the athlete.',
      entryPoints: ['Today view', 'Nora Daily', 'Mental Training handoff'],
      dependentServices: ['DailyCurriculumReader', 'pulsecheck-daily-assignments listener'],
      firestoreCollections: ['pulsecheck-daily-assignments'],
      integrations: ['Cloud Firestore'],
      owner: 'PulseCheck iOS + Mental Performance',
      releaseChannel: 'Pilot',
      status: 'active',
      sourceRefs: [
        { label: 'Daily Curriculum Reader', path: '../PulseCheck/PulseCheck/Services/DailyCurriculumReader.swift' },
        { label: 'Nora Daily View', path: '../PulseCheck/PulseCheck/Views/Chat/NoraDailyView.swift' },
        { label: 'Daily Curriculum Spec', path: 'src/components/admin/system-overview/PulseCheckCurriculumLayerSpecTab.tsx' },
      ],
    },
    {
      id: 'pulsecheck-exercise-library',
      name: 'Mental Exercise Library and Player',
      persona: 'Athletes executing mental drills',
      outcome: 'Browse and run structured mental exercises tied to assigned curriculum.',
      entryPoints: ['Exercise library', 'generic exercise player'],
      dependentServices: ['Exercise library service', 'progress tracker'],
      firestoreCollections: ['mental-training-library', 'users/{uid}/mental-progress'],
      integrations: [],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Exercise Library', path: '../PulseCheck/PulseCheck/Views/MentalTraining/ExerciseLibraryView.swift' },
        { label: 'Exercise Player', path: '../PulseCheck/PulseCheck/Views/MentalTraining/GenericExercisePlayerView.swift' },
      ],
    },
    {
      id: 'pulsecheck-coach-connection',
      name: 'Coach Connection and Messaging',
      persona: 'Athletes with performance staff',
      outcome: 'Connect athlete accounts to coaches and expose communication/session access.',
      entryPoints: ['Coach connection view', 'coach messaging', 'booking view'],
      dependentServices: ['Coach relationship service', 'messaging layer'],
      firestoreCollections: ['coach_dashboards', 'coach-athlete-links', 'conversations'],
      integrations: ['Scheduling links'],
      owner: 'Coach Platform + PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Coach Connection', path: '../PulseCheck/PulseCheck/Views/Coach/CoachConnectionView.swift' },
        { label: 'Coach Messaging', path: '../PulseCheck/PulseCheck/Views/Coach/CoachMessagingView.swift' },
      ],
    },
    {
      id: 'pulsecheck-health-stories',
      name: 'Health Story Surface',
      persona: 'Athletes and coaches',
      outcome: 'Translate mental and physical context into readable trend narratives.',
      entryPoints: ['Health story cards', 'profile insight views'],
      dependentServices: ['Health aggregation service', 'insight renderer'],
      firestoreCollections: ['users/{uid}/health-data', 'users/{uid}/mental-progress'],
      integrations: ['HealthKit (permissioned)'],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Health Story Test View', path: '../PulseCheck/PulseCheck/Views/HealthStoryTestView.swift' },
        { label: 'Insights Section', path: '../PulseCheck/PulseCheck/Views/ProfileSections/InsightsSection.swift' },
      ],
    },
    {
      id: 'pulsecheck-profile-readiness',
      name: 'Profile Readiness Dashboard',
      persona: 'Athletes',
      outcome: 'Provide a single readiness snapshot across performance, biometrics, and mental map dimensions.',
      entryPoints: ['User profile', 'overview/performance/biometrics sections'],
      dependentServices: ['Profile service', 'readiness aggregation'],
      firestoreCollections: ['users/{uid}', 'mental-notes', 'users/{uid}/health-data'],
      integrations: [],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'User Profile View', path: '../PulseCheck/PulseCheck/Views/UserProfileView.swift' },
        { label: 'Overview Section', path: '../PulseCheck/PulseCheck/Views/ProfileSections/OverviewSection.swift' },
      ],
    },
    {
      id: 'pulsecheck-profile-snapshots-export',
      name: 'Canonical Profile Snapshot Pipeline',
      persona: 'Athletes, staff, and research operators',
      outcome: 'Persist milestone-based canonical profile snapshots with revision history and export them through a stable research-safe contract.',
      entryPoints: ['Baseline completion', 'midpoint and endpoint trials', 'retention trials', 'admin research export'],
      dependentServices: ['Athlete progress service', 'profile snapshot writer', 'research export service'],
      firestoreCollections: [
        'athlete-mental-progress',
        'athlete-mental-progress/{uid}/profile-snapshots',
        'research-export-jobs',
      ],
      integrations: [],
      owner: 'PulseCheck Team + Mental Performance',
      releaseChannel: 'Planned',
      status: 'planned',
      sourceRefs: [
        { label: 'Profile Snapshot & Export Spec', path: '../QuickLifts-Web/src/components/admin/system-overview/PulseCheckProfileSnapshotExportSpecTab.tsx' },
        { label: 'Athlete Progress Service', path: '../QuickLifts-Web/src/api/firebase/mentaltraining/athleteProgressService.ts' },
      ],
    },
    {
      id: 'pulsecheck-athlete-showroom-avatar',
      name: 'Optional Multi-View 3D Athlete Avatar',
      persona: 'Athletes who want a premium profile identity surface',
      outcome:
        'Let athletes optionally create a personalized 3D profile avatar from front, left-side, back, and right-side full-body captures, rendered in the Profile showroom without affecting onboarding or product access.',
      entryPoints: ['Profile image area only', 'Avatar settings from Profile'],
      dependentServices: ['Avatar capture validator', 'Avatar upload service', 'Avatar generation job service', 'RealityKit showroom renderer'],
      firestoreCollections: ['users/{uid}.avatarShowroom', 'profile-avatars/{uid}/sessions/{sessionId}'],
      integrations: ['Apple Vision', 'RealityKit', 'Firebase Storage', 'backend avatar generation pipeline'],
      owner: 'PulseCheck Team + Platform + 3D Generation',
      releaseChannel: 'Planned optional profile feature',
      status: 'planned',
      sourceRefs: [
        { label: 'Avatar Spec', path: '../PulseCheck/docs/specs/athlete-showroom-avatar.md' },
        { label: 'Avatar Implementation Plan', path: '../PulseCheck/docs/specs/athlete-showroom-avatar-implementation-plan.md' },
        { label: 'Profile View', path: '../PulseCheck/PulseCheck/Views/UserProfileView.swift' },
      ],
    },
    {
      id: 'pulsecheck-daily-reflection-settings',
      name: 'Daily Reflection and Settings Controls',
      persona: 'Athletes',
      outcome: 'Configure cadence, privacy, and reflective prompts for consistent mental check-ins.',
      entryPoints: ['Settings view', 'daily reflection settings'],
      dependentServices: ['Settings service', 'notifications'],
      firestoreCollections: ['users/{uid}/preferences'],
      integrations: ['Push Notifications'],
      owner: 'PulseCheck Team',
      releaseChannel: 'Beta',
      status: 'active',
      sourceRefs: [
        { label: 'Settings View', path: '../PulseCheck/PulseCheck/Views/Settings/SettingsView.swift' },
        { label: 'Daily Reflection Settings', path: '../PulseCheck/PulseCheck/Views/Settings/DailyReflectionSettingsView.swift' },
      ],
    },
    {
      id: 'pulsecheck-subscription-access',
      name: 'Pulse Check Subscription Access',
      persona: 'Athletes entering premium coaching loops',
      outcome: 'Gate paid features and align entitlement status with ecosystem subscriptions.',
      entryPoints: ['Subscription modal', 'subscription plans in chat'],
      dependentServices: ['Subscription entitlement service', 'auth'],
      firestoreCollections: ['users', 'subscriptionRecords'],
      integrations: ['RevenueCat', 'Stripe'],
      owner: 'Monetization Team',
      releaseChannel: 'Beta',
      status: 'beta',
      sourceRefs: [
        { label: 'Subscription View', path: '../PulseCheck/PulseCheck/Views/Subscription/SubscriptionView.swift' },
        { label: 'Subscription Card', path: '../PulseCheck/PulseCheck/Views/Chat/SubscriptionPlansCardContent.swift' },
      ],
    },
    {
      id: 'pulsecheck-privacy-consent',
      name: 'Privacy Consent Flow and Consent v6',
      persona: 'All Pulse Check users',
      outcome:
        'Capture product consent plus pilot/research required documents, and re-prompt athletes when stored pilot consent versions are older than the current v6 documents.',
      entryPoints: ['Privacy consent modal', 'chat consent card', 'athlete onboarding consent step', 'pilot/team invite redemption'],
      dependentServices: ['PulseCheck provisioning access state', 'team invite redemption API', 'consent PDF renderer'],
      firestoreCollections: ['pulsecheck-team-memberships', 'pulsecheck-pilot-enrollments', 'users/{uid}/consents'],
      integrations: [],
      owner: 'PulseCheck Team + Legal Ops',
      releaseChannel: 'Pilot',
      status: 'active',
      sourceRefs: [
        { label: 'Privacy Consent Modal', path: '../PulseCheck/PulseCheck/Views/Components/PrivacyConsentModal.swift' },
        { label: 'Consent Card Content', path: '../PulseCheck/PulseCheck/Views/Chat/PrivacyConsentCardContent.swift' },
        { label: 'Provisioning Consent Types', path: 'src/api/firebase/pulsecheckProvisioning/types.ts' },
        { label: 'Consent Access State', path: 'src/api/firebase/pulsecheckProvisioning/accessState.ts' },
        { label: 'Consent v6 Tests', path: 'tests/unit/pulsecheck-consent-access-state.test.ts' },
      ],
    },
  ],
};
