import type { ProductHandbook } from '../schema';

export const pulseAndroidHandbook: ProductHandbook = {
  id: 'pulse-android',
  name: 'Fit With Pulse Android',
  platform: 'Android (Kotlin + Jetpack Compose)',
  summary:
    'Android client for the Fit With Pulse consumer fitness surface, mirroring clubs, rounds, workouts, and social accountability workflows.',
  owner: 'Android Squad',
  repo: 'Pulse-Android',
  releaseChannel: 'devDebug/devRelease internal + prodRelease rollout',
  status: 'active',
  keyOutcomes: [
    'Cross-platform Fit With Pulse parity for growth and retention',
    'Native Android workout and round execution',
    'Shared Firestore contract consistency with iOS',
  ],
  featureInventory: [
    {
      id: 'android-auth',
      name: 'Authentication and Account Entry',
      persona: 'New and returning Android users',
      outcome: 'Enable sign-in, sign-up, and secure session recovery for app access.',
      entryPoints: ['Start screen', 'Sign in screen', 'Sign up screen'],
      dependentServices: ['Firebase Auth', 'User repository'],
      firestoreCollections: ['users'],
      integrations: ['Firebase Auth'],
      owner: 'Android Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Sign In Screen', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/auth/SignInScreen.kt' },
        { label: 'Auth ViewModel', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/auth/AuthViewModel.kt' },
      ],
    },
    {
      id: 'android-home-shell',
      name: 'Home Surface and Navigation Shell',
      persona: 'Daily active users',
      outcome: 'Provide entry to workouts, rounds, messages, and profile workflows.',
      entryPoints: ['Home screen', 'Bottom navigation', 'Deep link router'],
      dependentServices: ['Navigation host', 'Home view model'],
      firestoreCollections: ['users', 'sweatlistCollections'],
      integrations: [],
      owner: 'Android Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Home Screen', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/home/HomeScreen.kt' },
        { label: 'Nav Host', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/navigation/PulseNavHost.kt' },
      ],
    },
    {
      id: 'android-workout-builder',
      name: 'Workout Creation and Editing',
      persona: 'Athletes and creators',
      outcome: 'Build workout templates and configure exercises before session execution.',
      entryPoints: ['Workout list', 'Create workout screen', 'Workout detail'],
      dependentServices: ['Workout repository', 'Exercise data layer'],
      firestoreCollections: ['users/{uid}/workouts', 'exercises'],
      integrations: [],
      owner: 'Android Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Create Workout', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/workout/CreateWorkoutScreen.kt' },
        { label: 'Workout ViewModel', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/workout/WorkoutViewModel.kt' },
      ],
    },
    {
      id: 'android-live-workout',
      name: 'Live Workout Session Modes',
      persona: 'Athletes completing sessions',
      outcome: 'Execute lift, run, bike, stretch, and fat-burn sessions with progress state and summaries.',
      entryPoints: ['Workout type selection', 'Ready screens', 'Active session screens'],
      dependentServices: ['Session view models', 'History repository'],
      firestoreCollections: ['users/{uid}/completed-workouts', 'users/{uid}/exercise-logs'],
      integrations: ['Health Connect (in progress)'],
      owner: 'Android Squad',
      releaseChannel: 'Production',
      status: 'beta',
      sourceRefs: [
        { label: 'Lift Session', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/workout/LiftWorkoutSessionScreen.kt' },
        { label: 'Run Session', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/workout/RunSessionScreen.kt' },
      ],
    },
    {
      id: 'android-rounds',
      name: 'Round Discovery, Join, and Detail',
      persona: 'Athletes in challenges',
      outcome: 'Browse rounds, join participation, and track position/status.',
      entryPoints: ['Round detail screen', 'Round library', 'Invitation routes'],
      dependentServices: ['Round repository', 'Leaderboard reads'],
      firestoreCollections: ['sweatlistCollections', 'sweatlistCollections/{id}/participants', 'sweatlistCollections/{id}/leaderboard-entries'],
      integrations: [],
      owner: 'Android Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Round Detail', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/round/RoundDetailScreen.kt' },
        { label: 'Round ViewModel', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/round/RoundViewModel.kt' },
      ],
    },
    {
      id: 'android-round-creation',
      name: 'Round Creation and Template Flow',
      persona: 'Creators and coaches',
      outcome: 'Create and configure rounds directly from Android surfaces.',
      entryPoints: ['Create round screen', 'Template library', 'Generation screens'],
      dependentServices: ['Round template view models', 'Firestore writes'],
      firestoreCollections: ['sweatlistCollections', 'users/{uid}/workouts'],
      integrations: ['OpenAI'],
      owner: 'Android Squad',
      releaseChannel: 'Internal QA',
      status: 'beta',
      sourceRefs: [
        { label: 'Create Round', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/round/CreateRoundScreen.kt' },
        { label: 'Template Generating', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/round/RoundTemplateGeneratingScreen.kt' },
      ],
    },
    {
      id: 'android-nutrition',
      name: 'Legacy Nutrition and Macra Boundary',
      persona: 'Athletes managing diet quality',
      outcome: 'Preserve legacy meal and label context where it supports the consumer fitness app while recognizing Macra as the dedicated nutrition surface.',
      entryPoints: ['Legacy nutrition screen', 'Scan food', 'Scan label', 'History views', 'Macra handoff planning'],
      dependentServices: ['Nutrition repositories', 'Image processing'],
      firestoreCollections: ['users/{uid}/meals', 'users/{uid}/nutrition-logs'],
      integrations: ['Camera', 'Macra boundary'],
      owner: 'Android Squad + Nutrition Systems',
      releaseChannel: 'Legacy / migration-aware',
      status: 'active',
      sourceRefs: [
        { label: 'Nutrition Screen', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/nutrition/NutritionScreen.kt' },
        { label: 'Scan Label Screen', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/nutrition/ScanLabelScreen.kt' },
      ],
    },
    {
      id: 'android-checkins',
      name: 'Check-ins and Profile Accountability',
      persona: 'Athletes and coaches',
      outcome: 'Record progress and reflections with privacy controls.',
      entryPoints: ['Check-in screens', 'Profile check-in detail'],
      dependentServices: ['Profile services', 'Privacy settings'],
      firestoreCollections: ['users/{uid}/check-ins'],
      integrations: [],
      owner: 'Android Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Check-In Screen', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/checkin/CheckInScreen.kt' },
        { label: 'Checkin Privacy', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/settings/CheckinPrivacySettingsScreen.kt' },
      ],
    },
    {
      id: 'android-messaging',
      name: 'Direct Messaging',
      persona: 'Athletes and creators',
      outcome: 'Maintain one-to-one communication for support and accountability.',
      entryPoints: ['Direct message list', 'Direct message thread'],
      dependentServices: ['Messaging repository', 'Realtime listeners'],
      firestoreCollections: ['conversations', 'messages'],
      integrations: ['Push Notifications'],
      owner: 'Android Squad',
      releaseChannel: 'Production',
      status: 'beta',
      sourceRefs: [
        { label: 'Direct Message Screen', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/messages/DirectMessageScreen.kt' },
        { label: 'Direct Message ViewModel', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/messages/DirectMessageViewModel.kt' },
      ],
    },
    {
      id: 'android-subscriptions',
      name: 'Purchase and Subscription Surface',
      persona: 'Free users converting to paid',
      outcome: 'Expose package selection and execute purchase workflows.',
      entryPoints: ['Purchase screen', 'Paywall intercepts'],
      dependentServices: ['Subscription view models', 'Auth'],
      firestoreCollections: ['users', 'subscriptionRecords'],
      integrations: ['RevenueCat', 'Stripe'],
      owner: 'Monetization Team',
      releaseChannel: 'Production',
      status: 'beta',
      sourceRefs: [
        { label: 'Purchase Screen', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/subscription/PurchaseScreen.kt' },
        { label: 'Offering ViewModel', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/subscription/OfferingViewModel.kt' },
      ],
    },
    {
      id: 'android-health-connect',
      name: 'Health Connect Capture',
      persona: 'Android users with wearable/health data',
      outcome: 'Capture external health context for improved readiness and insights.',
      entryPoints: ['Health capture screens', 'Health data story views'],
      dependentServices: ['HealthConnect view model', 'Story rendering'],
      firestoreCollections: ['users/{uid}/health-data'],
      integrations: ['Health Connect'],
      owner: 'Android Squad',
      releaseChannel: 'Staged rollout',
      status: 'beta',
      sourceRefs: [
        { label: 'Health Connect Capture', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/health/HealthConnectCaptureScreen.kt' },
        { label: 'Health Data Story', path: '../Pulse-Android/app/src/main/java/ai/fitwithpulse/pulse/ui/health/HealthDataStoryScreen.kt' },
      ],
    },
    {
      id: 'android-firestore-contract',
      name: 'Cross-Platform Firestore Contract Compliance',
      persona: 'Engineering and QA teams',
      outcome: 'Keep Android payloads aligned with iOS schema conventions (including timestamp semantics).',
      entryPoints: ['Repository serializers', 'QA checklists', 'release gates'],
      dependentServices: ['Repository layer', 'QA pipeline'],
      firestoreCollections: ['users', 'sweatlistCollections', 'workout collections'],
      integrations: [],
      owner: 'Android Squad + Platform',
      releaseChannel: 'Engineering governance',
      status: 'active',
      sourceRefs: [
        { label: 'Firestore Contract', path: '../Pulse-Android/docs/FIRESTORE_CONTRACT.md' },
        { label: 'README', path: '../Pulse-Android/README.md' },
      ],
    },
  ],
};
