import type { ProductHandbook } from '../schema';

export const pulseCheckAndroidHandbook: ProductHandbook = {
  id: 'pulsecheck-android',
  name: 'Pulse Check Android',
  platform: 'Android (Kotlin / Jetpack Compose / Material 3)',
  summary:
    'Native Android parity port of Pulse Check, built for exact, continuously-maintained parity with the iOS app. Mirrors the Fit With Pulse Android stack (Kotlin, Compose, Hilt, Firebase) and shares the ecosystem Firebase. iOS is the source of truth; parity is governed by IOS_PARITY_AUDIT.md and FIRESTORE_CONTRACT.md.',
  owner: 'PulseCheck Team + Android Squad',
  repo: 'PulseCheck-Android',
  releaseChannel: 'Internal dev (pre-release)',
  status: 'beta',
  keyOutcomes: [
    'Reach and hold exact UI + data-contract parity with Pulse Check iOS on Android',
    'Share the ecosystem Firebase (quicklifts-dd3f1 / quicklifts-dev-01) so athletes are cross-platform',
    'Keep technical adds tracked against iOS via a living parity audit + Firestore contract',
  ],
  featureInventory: [
    {
      id: 'pulsecheck-android-foundation-shell',
      name: 'Foundation + Navigation Shell (M1)',
      persona: 'All Pulse Check Android athletes',
      outcome:
        'A buildable Kotlin/Compose foundation: splash -> Google sign-in -> 4-tab chromatic nav shell, dev/prod flavors on the shared Firebase, single-activity Compose architecture.',
      entryPoints: ['App launch', 'MainActivity', 'PulseCheckApp root router', 'ChromaticTabBar'],
      dependentServices: ['Firebase Auth', 'Cloud Firestore', 'Hilt DI', 'Compose Navigation'],
      firestoreCollections: ['users'],
      integrations: ['Firebase Auth', 'Cloud Firestore', 'Google Sign-In'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'App Module Build Config', path: '../PulseCheck-Android/app/build.gradle.kts' },
        { label: 'Root Router (mirrors iOS ContentView)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/navigation/PulseCheckApp.kt' },
        { label: 'Chromatic Tab Bar (mirrors iOS MainTabView)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/navigation/ChromaticTabBar.kt' },
        { label: 'Priority-Modal Gate', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/navigation/PriorityModal.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-design-system',
      name: 'Design System Port (M1)',
      persona: 'Android engineers maintaining parity',
      outcome:
        'Color, typography, theme, and animation tokens ported verbatim from the iOS Design/ folder so Android renders identical chrome (dark-only, immersive status bar, lime/purple/cyan/blue tab accents).',
      entryPoints: ['PulseCheckTheme', 'PulseCheckColors', 'PulseCheckType'],
      dependentServices: ['Material 3 theming'],
      firestoreCollections: [],
      integrations: [],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Color (from PulseCheckColors.swift)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/theme/Color.kt' },
        { label: 'Theme (dark-only, immersive bars)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/theme/Theme.kt' },
        { label: 'Typography (from PulseCheckTypography.swift)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/theme/Type.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-google-auth',
      name: 'Google Sign-In Auth (M1)',
      persona: 'Android athletes signing in',
      outcome:
        'Google Sign-In via Credential Manager exchanged for a Firebase session, resolving the shared users/{uid} doc with additive/merge-only writes. (Google Sign-In is being added to iOS too for cross-platform login.)',
      entryPoints: ['Sign-in screen', 'SignInScreen Google button'],
      dependentServices: ['AuthRepository', 'GoogleSignInClient', 'UserRepository'],
      firestoreCollections: ['users'],
      integrations: ['Firebase Auth', 'Google Sign-In (Credential Manager)'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Auth ViewModel (3-state gate)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/auth/AuthViewModel.kt' },
        { label: 'Google Sign-In Client', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/repository/GoogleSignInClient.kt' },
        { label: 'User Repository (additive merge)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/repository/UserRepository.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-nora-inbox-reply',
      name: 'Nora Conversation Inbox & Reply (M2)',
      persona: 'Athletes receiving reactive Nora check-ins',
      outcome:
        'Live Phase H inbox (grouped by day, unread dots) and conversation detail with turn bubbles and a reply composer. Reads pulsecheck-nora-conversations; replies POST to nora-athlete-reply with a Firebase ID token (no direct doc writes), matching iOS exactly.',
      entryPoints: ['Nora tab', 'NoraInboxScreen', 'NoraConversationScreen'],
      dependentServices: ['NoraConversationRepository', 'pulsecheck-nora-conversations listener', 'nora-athlete-reply'],
      firestoreCollections: ['pulsecheck-nora-conversations'],
      integrations: ['Firebase Auth', 'Cloud Firestore', 'Netlify Functions'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Nora Conversation Repository (mirrors NoraConversationService)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/repository/NoraConversationRepository.kt' },
        { label: 'Nora Inbox Screen (mirrors NoraInboxView)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/nora/NoraInboxScreen.kt' },
        { label: 'Nora Conversation Screen (mirrors NoraConversationDetailView)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/nora/NoraConversationScreen.kt' },
        { label: 'Shared Athlete Reply Function', path: 'netlify/functions/nora-athlete-reply.ts' },
      ],
    },
    {
      id: 'pulsecheck-android-onboarding-gate',
      name: 'Nora Onboarding + Signed-In Gate (M3)',
      persona: 'First-run athletes',
      outcome:
        'Multi-step Nora onboarding (welcome → profile: name/sport/position → goal → wearables) that writes the user doc (preferredName, sport, position, primaryGoal, registrationComplete, pulseCheckOnboardingComplete) with exact iOS field parity. A SignedInRoot gate (live user listener) keeps onboarding in front of the tabs until it completes — the functional first link of the priority-modal chain.',
      entryPoints: ['First launch after sign-in', 'NoraOnboardingScreen', 'SignedInRoot gate'],
      dependentServices: ['NoraOnboardingViewModel', 'UserRepository.completeOnboarding', 'AuthViewModel live user listener'],
      firestoreCollections: ['users'],
      integrations: ['Cloud Firestore', 'Health Connect (wearables step)'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Nora Onboarding Screen (mirrors NoraOnboardingView)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/onboarding/NoraOnboardingScreen.kt' },
        { label: 'Signed-In Gate', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/navigation/SignedInRoot.kt' },
        { label: 'Onboarding Write (User repository)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/repository/UserRepository.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-today-gpt-chat',
      name: 'Today Tab + Free Nora GPT Chat (M2.5)',
      persona: 'Athletes in active mental coaching',
      outcome:
        'Free-form Nora chat on the Today tab, powered by the shared OpenAI proxy (gpt-4o-mini, Nora persona, no client key) with a typing indicator, and persisted to the conversations collection. The rich daily briefing (health snapshot, readiness, action cards) and mental notes are the next increment (M2.6).',
      entryPoints: ['Today tab', 'ChatScreen input area'],
      dependentServices: ['PulseCheckGptService (OpenAI proxy)', 'ConversationRepository', 'AuthRepository'],
      firestoreCollections: ['conversations'],
      integrations: ['OpenAI (via openai-bridge proxy)', 'Firebase Auth', 'Cloud Firestore'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Nora GPT Service (mirrors PulseCheckGPTService)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/repository/PulseCheckGptService.kt' },
        { label: 'Chat Screen (Today tab)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/chat/ChatScreen.kt' },
        { label: 'Conversation Persistence', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/repository/ConversationRepository.kt' },
        { label: 'OpenAI Bridge (proxy target)', path: 'netlify/functions/openai-bridge.ts' },
      ],
    },
    {
      id: 'pulsecheck-android-mental-notes',
      name: 'Mental Notes (M2.6)',
      persona: 'Athletes and coaches tracking recurring concerns',
      outcome:
        'Live mental-notes bar on the Today tab (active notes as category-colored pills) plus a detail sheet to review a note and change its status or delete it. Reads/writes user-mental-notes/{uid}/notes with full iOS field + enum parity.',
      entryPoints: ['Today tab mental-notes bar', 'Mental note detail sheet'],
      dependentServices: ['MentalNotesRepository', 'MentalNotesViewModel'],
      firestoreCollections: ['user-mental-notes'],
      integrations: ['Cloud Firestore'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Mental Note Model + Repo (mirrors MentalNotesService)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/repository/MentalNotesRepository.kt' },
        { label: 'Mental Notes Bar + Detail Sheet', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/chat/MentalNotesBar.kt' },
        { label: 'Firestore Contract (user-mental-notes)', path: '../PulseCheck-Android/docs/FIRESTORE_CONTRACT.md' },
      ],
    },
    {
      id: 'pulsecheck-android-hcsr-write',
      name: 'Health-Context Source Records (HCSR write, M4.5)',
      persona: 'The shared health-context pipeline',
      outcome:
        'Feeds the shared health-context input layer so the server assembler folds Android data into the canonical snapshots. HealthContextSourceWriter batch-writes activity + recovery source records to health-context-source-records and a source-status doc to health-context-source-status (sourceFamily "healthconnect"), with byte-for-byte iOS schema + unit parity (distance km, sleep hours, kcal). Clients write source records + status only — never the canonical snapshot. Fires after a granted Health Connect read.',
      entryPoints: ['Today daily-briefing sync (after Health Connect read)'],
      dependentServices: ['HealthContextSourceWriter', 'HealthConnectReader', 'DailyBriefingViewModel'],
      firestoreCollections: ['health-context-source-records', 'health-context-source-status'],
      integrations: ['Cloud Firestore', 'Health Connect'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Health Context Source Writer (mirrors HCSRRecordWriter)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/health/HealthContextSourceWriter.kt' },
        { label: 'iOS HCSR Writer (contract source)', path: '../PulseCheck/PulseCheck/Services/HCSRRecordWriter.swift' },
        { label: 'Firestore Contract (HCSR schema)', path: '../PulseCheck-Android/docs/FIRESTORE_CONTRACT.md' },
      ],
    },
    {
      id: 'pulsecheck-android-mental-training',
      name: 'Training Room — ExerciseLibraryView Design Parity (M5 / M5.5)',
      persona: 'Athletes doing mental drills',
      outcome:
        'The full Training tab rebuilt to match iOS ExerciseLibraryView ("Training Room") via a screenshot-driven design loop — every iOS surface in scroll order: header ("Training Room" + subtitle + orange streak flame badge) → StreakProgressCard (day stack / completed / minutes) → "Today\'s Work" (assignment task cards — purple circle, FROM-{coach} eyebrow, reason, pills — or the between-programs / no-task empty card) → "Baseline Checkpoint" baseline card (Set your starting mental read, 3-min/First-read pills, Start Baseline CTA) → "Active Plans" Nora foundation plan card ("Universal Foundation Block", goal, Step N of M, outcome, pills) → "All exercises" browse (category-colored cards, reads mental-exercises with full exerciseConfig parsing, opens the guided breathing player [phase timer + expanding circle] or generic prompt/timer player). Completing an exercise writes a completion, updates the streak (new-day/yesterday logic), and closes the assignment. The training-plan / practice-history / recommendation / baseline-assessment engine renders the iOS empty state (no DailyTask/TrainingPlan/results pipeline on Android yet). The 3D sim / Vision-Pro runtimes stay iOS-only.',
      entryPoints: ['Training tab', 'Assigned section → player', 'Exercise card → player'],
      dependentServices: ['MentalTrainingRepository', 'MentalTrainingViewModel'],
      firestoreCollections: ['mental-exercises', 'mental-exercise-completions', 'mental-exercise-assignments', 'mental-training-streaks'],
      integrations: ['Cloud Firestore'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Mental Training Repository (mirrors MentalTrainingService)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/repository/MentalTrainingRepository.kt' },
        { label: 'Exercise Library Screen (mirrors ExerciseLibraryView)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/training/ExerciseLibraryScreen.kt' },
        { label: 'Exercise Players (breathing + generic)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/training/ExercisePlayerScreen.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-profile-settings',
      name: 'Settings + Device Connections — Design Parity (M7)',
      persona: 'All athletes',
      outcome:
        'Settings rebuilt to full iOS SettingsView parity via the screenshot design loop: X-circle header → PREFERENCES (Daily Reflection — toggle + reminder time persisted under the same dailyReflectionEnabled/Hour/Minute keys as iOS UserDefaults; Subscription Plan → paywall) → ACCOUNT (email row, Sign Out with the iOS confirm alert, Delete Account modal with password reauthentication for email accounts performing a real Firebase user.delete()) → INTEGRATIONS (Device Connections + Health Connect permissions deep link) → SUPPORT (Privacy, Terms, Help & Support) → waveform footer with version + DB code name (ECHO-7 prod / NOVA-9 dev). Plus a full port of the iOS WearablePickerSheet as the Device Connections screen: connect/manage/add modes with exact per-mode copy, purple-gradient backdrop, the Polar "OUR SIGNATURE DEVICE" hero card, the Fitbit Air card (screenless woven-loop illustration with orange piping, REAL connect through the Health Connect permission contract, CONNECTED badge + refresh), the Oura card, and the "Different device" capture writing users/{uid}.wearableOnboarding.otherDeviceName — the same field iOS writes. Entry points: Settings → Device Connections and the Profile health-sources card ("Add another source"/"Manage sources" pill). Polar/Oura native pairing walkthroughs stay iOS-only; the Android cards explain the Health Connect sync path honestly. iOS Admin section, Screen Demo, and tutorial replay are iOS-only.',
      entryPoints: ['Profile tab → Settings', 'Settings → Device Connections', 'Profile sources card → Manage sources'],
      dependentServices: ['AuthViewModel', 'AuthRepository (deleteAccount + reauth)', 'WearableDevicesViewModel', 'HealthConnectManager'],
      firestoreCollections: ['users'],
      integrations: ['Firebase Auth', 'Cloud Firestore', 'Health Connect', 'RevenueCat'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Settings Screen (mirrors SettingsView + DeleteAccountModal + DailyReflectionSettingsView)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/profile/SettingsScreen.kt' },
        { label: 'Device Connections (mirrors WearablePickerSheet + WearableDeviceIllustrations)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/wearables/WearableDevicesScreen.kt' },
        { label: 'Wearable Devices ViewModel (Health Connect state + other-device capture)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/wearables/WearableDevicesViewModel.kt' },
        { label: 'Auth Repository (account deletion with password reauth)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/repository/AuthRepository.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-crisis-wall',
      name: 'Tier-3 Crisis Wall (M7)',
      persona: 'Athletes flagged for Tier-3 escalation',
      outcome:
        'Safety net mirroring iOS CrisisWallView. When the server sets crisisWallActive, a full-screen wall overlays everything in the signed-in surface with the canonical national resources (988 Suicide & Crisis Lifeline, Crisis Text Line 741741, 911) as tap-to-call/text. The app never places a call or text — the athlete chooses to tap. Acknowledging writes to pulsecheck-clinical-escalations/{id}/athleteAcknowledgements and never traps the athlete. Copy is byte-for-byte parity.',
      entryPoints: ['Server-set crisisWallActive', 'SignedInRoot overlay'],
      dependentServices: ['CrisisWallViewModel', 'UserRepository (live user listener)'],
      firestoreCollections: ['users', 'pulsecheck-clinical-escalations'],
      integrations: ['Cloud Firestore', 'Android dialer / messaging intents'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Crisis Wall Screen (mirrors CrisisWallView)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/crisis/CrisisWallScreen.kt' },
        { label: 'Crisis Wall Controller (mirrors CrisisWallService)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/crisis/CrisisWallViewModel.kt' },
        { label: 'iOS Crisis Wall (contract source)', path: '../PulseCheck/PulseCheck/Views/CrisisWallView.swift' },
      ],
    },
    {
      id: 'pulsecheck-android-daily-curriculum',
      name: 'Today’s Training — Daily Curriculum Feed (M5.6)',
      persona: 'Athletes following a curriculum',
      outcome:
        'A read-only "Today’s training" card on the Today tab mirroring iOS DailyCurriculumReader: a live feed of the curriculum engine’s protocol/simulation assignments (pulsecheck-daily-assignments scoped to athleteId + today + assignedBy=curriculum-engine), surfacing the focus, why-this-today rationale, practice progress, and the "same by design" intent badge. Protocol/sim playback stays the iOS-only 3D runtime, so the Android surface is transparency-only.',
      entryPoints: ['Today tab — Today’s training card'],
      dependentServices: ['DailyCurriculumRepository', 'DailyCurriculumViewModel'],
      firestoreCollections: ['pulsecheck-daily-assignments'],
      integrations: ['Cloud Firestore'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Daily Curriculum Repository (mirrors DailyCurriculumReader)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/repository/DailyCurriculumRepository.kt' },
        { label: 'Today’s Training Card', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/chat/DailyTrainingCard.kt' },
        { label: 'Daily Curriculum Assignment Model', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/model/DailyCurriculumAssignment.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-profile-parity',
      name: 'Profile — UserProfileView Design Parity',
      persona: 'Athletes reviewing their mental-performance profile',
      outcome:
        'The full Profile tab rebuilt to match iOS UserProfileView via a screenshot-driven design loop — EVERY scroll card ported in iOS order over the purple/lime/green blob backdrop: topBar ("Profile" + ⋮ settings) → identity hero (teal-rimmed avatar, 30sp name, sport/level hero chips, "Update your story" pill) → "WHAT NORA SEES IN YOU" mental-performance card (Composure/Focus/Decision pillars) → "Nora is pulling health data from these sources" (Health Connect / Fitbit Air, live permission state) → responsiveness card (Readiness + Pressure-Sensitivity summary cards + Strongest/Growing/Steadiest spotlight tiles) → first-scroll question cards (Strongest / Needs Support / Over Time / Under Pressure / Consistency / Right Now) → "WHAT WE\'RE WORKING ON NOW" program-pathway card → "TRIAL MILESTONES" (Baseline/Midpoint/Endpoint/Retention) → "HOW YOUR TREND IS FORMING" → rhythm & access cards (My focus / My biggest mental challenge / Where I train my mind / My team and coaching — coaches row opens the coach screen, subscription from user.subscriptionType). All cards render the exact iOS no-baseline EMPTY STATE (pillars "—", "still forming" headlines, "Baseline pending", milestones Pending/Later) because the baseline / ProfileMetricsService pipeline that computes live values is not yet ported — identical to a fresh iOS athlete. Apple Watch / Oura / Polar device lanes + the Oura recovery card are iOS-only hardware paths; Android represents devices via the Health Connect sources card. Dedicated edit/detail sheets are the remaining deferred piece.',
      entryPoints: ['Profile tab'],
      dependentServices: ['AuthViewModel', 'DailyBriefingViewModel'],
      firestoreCollections: ['users', 'health-context-source-records'],
      integrations: ['Cloud Firestore', 'Health Connect'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Profile Screen (mirrors UserProfileView hero + mentalPerformanceCard + dataShapingCard)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/profile/ProfileScreen.kt' },
        { label: 'Profile Tab host (profile ↔ settings ↔ coach)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/profile/ProfileTab.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-today-dashboard',
      name: 'Today Dashboard — NoraDailyView Design Parity',
      persona: 'Athletes in active mental coaching',
      outcome:
        'The full Today surface rebuilt to match iOS NoraDailyView via a screenshot-driven design loop: greeting header → live metrics card → NORA check-in (exact readiness labels/emoji/colors) → 6-protocol COMPOSURE focus card (steps + Active toolkit grid) → post-check-in Nora coaching card (noraSaysCard parity — readiness-accent-tinted card, glowing green orb, "Nora" label, composeNoraMessage = acknowledgement + "Start with the {protocol} protocol first, then move on to the {sim} sim." + probe, "Reply to Nora" pill) → stats row (statsRow parity — Day Stack / MPR Score / Sessions, bolt-orange / trending-lime / check-green) → pinned Talk-to-Nora CTA. MPR Score shows the iOS "—" fallback (no mprScore on Android yet); the data-gated "FROM NORA" proactive panel is the remaining inline gap.',
      entryPoints: ['Today tab (post-check-in surface)'],
      dependentServices: ['DailyBriefingViewModel', 'DailyCurriculumViewModel', 'MentalTrainingViewModel'],
      firestoreCollections: ['pulsecheck-daily-assignments', 'mental-training-progress', 'health-context-source-records'],
      integrations: ['Cloud Firestore', 'Health Connect'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Nora Daily Screen (Today dashboard, mirrors NoraDailyView)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/chat/NoraDailyScreen.kt' },
        { label: 'ReadinessLevel (acknowledgement + probe copy)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/model/ReadinessLevel.kt' },
        { label: 'Mental Training ViewModel (streak → stats row)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/training/MentalTrainingViewModel.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-coach',
      name: 'Coach Connection + Messaging (M6)',
      persona: 'Athletes working with a coach',
      outcome:
        'From Profile → Your coach: connect to a coach by referral code (queries coaches, writes coachAthletes + users.connectedCoaches), then real-time messaging via coach-athlete-conversations / coach-athlete-messages (batch send updates the conversation summary + unread count). Mirrors iOS CoachService + CoachAthleteMessagingService. Session booking is iOS-local-only and not ported.',
      entryPoints: ['Profile → Your coach', 'Coach messaging thread'],
      dependentServices: ['CoachRepository', 'CoachViewModel'],
      firestoreCollections: ['coaches', 'coachAthletes', 'coach-athlete-conversations', 'coach-athlete-messages'],
      integrations: ['Cloud Firestore'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Coach Repository (mirrors CoachService + messaging)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/repository/CoachRepository.kt' },
        { label: 'Coach Connection + List', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/coach/CoachScreen.kt' },
        { label: 'Coach Messaging', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/coach/CoachMessagingScreen.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-team-onboarding',
      name: 'Team / Pilot Invite + Athlete Onboarding (M3.5)',
      persona: 'Team-invited athletes',
      outcome:
        'End-to-end athlete provisioning: a pulsecheck://invite/{token} deep link opens an invite preview, redeems via the shared server transaction (POST /api/pulsecheck/team-invite/redeem), then runs the team onboarding (name → required consents → research consent if pending → baseline) writing athleteOnboarding.* to the membership and flipping pulseCheckOnboardingComplete. A membership-driven gate in SignedInRoot preempts the regular Nora onboarding. Mirrors iOS PulseCheckPilotInviteEntryView + PulseCheckAthleteTeamOnboardingView.',
      entryPoints: ['pulsecheck://invite/{token} deep link', 'SignedInRoot team-onboarding gate'],
      dependentServices: ['ProvisioningRepository', 'SignedInGateViewModel', 'DeepLinkState', 'TeamOnboardingViewModel'],
      firestoreCollections: ['pulsecheck-invite-links', 'pulsecheck-team-memberships', 'users'],
      integrations: ['Cloud Firestore', 'Firebase Auth', 'team-invite redeem API'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Provisioning Repository (preview/redeem/onboarding writes)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/repository/ProvisioningRepository.kt' },
        { label: 'Invite Entry Screen (mirrors PilotInviteEntryView)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/onboarding/InviteEntryScreen.kt' },
        { label: 'Team Onboarding Screen (mirrors AthleteTeamOnboardingView)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/onboarding/TeamOnboardingScreen.kt' },
        { label: 'Redeem API (server transaction)', path: 'src/pages/api/pulsecheck/team-invite/redeem.ts' },
      ],
    },
    {
      id: 'pulsecheck-android-monetization-platform',
      name: 'Subscription + Push + Voice + Saved Chat (M7.5)',
      persona: 'All athletes',
      outcome:
        'Final platform pass: RevenueCat subscription (entitlement "plus") with a PaywallScreen + access gate (dev bypasses when unconfigured); FCM push (PulseCheckMessagingService — token sync to users.fcmToken, notification display + channel); system SpeechRecognizer voice input in the Nora chat composer; and the Today chat now resumes the latest saved conversation instead of starting fresh. Needs the PulseCheck RevenueCat key + offerings to show plans.',
      entryPoints: ['Paywall gate', 'Chat mic button', 'Push notifications', 'Today chat resume'],
      dependentServices: ['SubscriptionRepository', 'PulseCheckMessagingService', 'ConversationRepository', 'AuthViewModel (FCM token sync)'],
      firestoreCollections: ['users', 'conversations'],
      integrations: ['RevenueCat (Play Billing)', 'Firebase Cloud Messaging', 'Android SpeechRecognizer'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Subscription Repository (mirrors RevenueCatService)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/repository/SubscriptionRepository.kt' },
        { label: 'Paywall Screen', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/subscription/PaywallScreen.kt' },
        { label: 'FCM Messaging Service (mirrors NotificationService)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/service/PulseCheckMessagingService.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-remaining',
      name: 'Remaining (server-owned / iOS-only / needs-config)',
      persona: 'Tracking',
      outcome:
        'Resolved tail per the parity audit: action cards + protocol-practice playback + training-load + canonical snapshot read + readiness→morning-check-in are server-orchestrator-owned; proactive insights are iOS on-device-computed (needs the historical-health store ported); 3D sim / Noise-gate / Vision-Pro + admin/demo are iOS-only; AppsFlyer + local scheduled reminders + Nora TTS + coach session booking are config/polish. Each has a definitive status in IOS_PARITY_AUDIT.md.',
      entryPoints: ['n/a'],
      dependentServices: ['Server Nora orchestrator', 'Sports Intelligence layer'],
      firestoreCollections: [],
      integrations: ['AppsFlyer (deferred)', 'Android TextToSpeech (deferred)'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Planned',
      status: 'planned',
      sourceRefs: [
        { label: 'Parity Audit (definitive status per row)', path: '../PulseCheck-Android/docs/IOS_PARITY_AUDIT.md' },
      ],
    },
    {
      id: 'pulsecheck-android-health-connect',
      name: 'Health Connect / Fitbit Air read (M4)',
      persona: 'Athletes with a performance wearable',
      outcome:
        'On-device Health Connect read: HealthConnectReader aggregates today’s steps, active/total calories, exercise duration, distance, and sleep into a DailyHealthSnapshot for the Today daily briefing (the Fitbit Air syncs into Health Connect). Each metric aggregates independently so partial grants still return data. Permission set + onboarding request built in M3. (M4.5 writes health-context source records so the shared server assembler folds Android data into the canonical snapshots.)',
      entryPoints: ['Onboarding wearables step', 'Today daily briefing', 'Briefing connect-health row'],
      dependentServices: ['HealthConnectManager', 'HealthConnectReader', 'DailyBriefingViewModel'],
      firestoreCollections: [],
      integrations: ['Health Connect', 'Fitbit Air (via Health Connect)'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Health Connect Manager (perm set + availability)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/health/HealthConnectManager.kt' },
        { label: 'Health Connect Reader (daily aggregates)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/health/HealthConnectReader.kt' },
        { label: 'Snapshot Model Skeleton (M4.5 canonical target)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/model/AthleteHealthContextSnapshot.kt' },
      ],
    },
    {
      id: 'pulsecheck-android-daily-briefing',
      name: 'Today Daily Briefing + Readiness Check-In (M4)',
      persona: 'Athletes starting their day',
      outcome:
        'The Today tab now opens with a daily briefing: a readiness check-in (drained → locked-in, mirroring iOS ReadinessLevel) plus today’s Health Connect snapshot (steps, sleep, active calories, active minutes), or a connect-Health-Connect prompt when not yet granted. Pinned above the Nora chat. (Staging readiness into a server morning-check-in conversation is a later step.)',
      entryPoints: ['Today tab header', 'DailyBriefingCard'],
      dependentServices: ['DailyBriefingViewModel', 'HealthConnectReader', 'HealthConnectManager'],
      firestoreCollections: [],
      integrations: ['Health Connect'],
      owner: 'PulseCheck Team + Android Squad',
      releaseChannel: 'Internal dev (pre-release)',
      status: 'beta',
      sourceRefs: [
        { label: 'Daily Briefing Card (mirrors NoraDailyView header)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/chat/DailyBriefingCard.kt' },
        { label: 'Daily Briefing ViewModel', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/ui/chat/DailyBriefingViewModel.kt' },
        { label: 'Readiness Level (mirrors iOS ReadinessLevel)', path: '../PulseCheck-Android/app/src/main/java/com/fitwithpulse/pulsecheck/data/model/ReadinessLevel.kt' },
      ],
    },
  ],
};
