import type { ProductHandbook } from '../schema';

export const quickliftsWebHandbook: ProductHandbook = {
  id: 'quicklifts-web',
  name: 'QuickLifts Web',
  platform: 'Web (Next.js + Firebase + Netlify)',
  summary:
    'Growth, operations, creator tooling, and internal command center surfaces that orchestrate the broader Pulse ecosystem.',
  owner: 'Web Platform',
  repo: 'QuickLifts-Web',
  releaseChannel: 'Netlify deploys from main',
  status: 'active',
  keyOutcomes: [
    'Public growth and onboarding surfaces',
    'Internal operations and admin tooling',
    'Creator workflows and PulseCheck commercial provisioning',
  ],
  featureInventory: [
    {
      id: 'web-public-marketing',
      name: 'Public Marketing and Entry Surfaces',
      persona: 'Prospects, creators, coaches, and investors',
      outcome: 'Drive discovery and conversion into app and partnership funnels.',
      entryPoints: ['/', '/pricing', '/download', '/creator', '/coach'],
      dependentServices: ['Next.js pages', 'Meta/SEO layer'],
      firestoreCollections: [],
      integrations: ['Analytics'],
      owner: 'Growth + Web Platform',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Landing Page', path: 'src/pages/index.tsx' },
        { label: 'Pricing Page', path: 'src/pages/pricing.tsx' },
      ],
    },
    {
      id: 'web-auth-gating',
      name: 'Auth Wrapper and Route Gating',
      persona: 'All web users',
      outcome: 'Guard protected routes while allowing public funnels and creator landing pages.',
      entryPoints: ['Global app wrapper', 'protected pages'],
      dependentServices: ['Firebase Auth', 'Redux user state'],
      firestoreCollections: ['users'],
      integrations: ['Firebase Auth'],
      owner: 'Web Platform',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Auth Wrapper', path: 'src/components/AuthWrapper.tsx' },
        { label: 'Admin Route Guard', path: 'src/components/auth/AdminRouteGuard.tsx' },
      ],
    },
    {
      id: 'web-admin-hub',
      name: 'Admin Console Index',
      persona: 'Internal operators',
      outcome: 'Provide centralized entry into operations dashboards and tooling pages.',
      entryPoints: ['/admin'],
      dependentServices: ['Admin auth checks', 'route cards'],
      firestoreCollections: ['admin-users'],
      integrations: [],
      owner: 'Platform Ops',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Admin Index', path: 'src/pages/admin/index.tsx' },
        { label: 'Admin Methods', path: 'src/api/firebase/admin/methods.ts' },
      ],
    },
    {
      id: 'web-system-overview-handbook',
      name: 'System Overview Handbook',
      persona: 'Execs, engineers, and operators',
      outcome: 'Maintain a complete end-to-end system map and operating handbook in one page.',
      entryPoints: ['/admin/systemOverview'],
      dependentServices: ['Static content manifest', 'admin guard', 'passcode gate'],
      firestoreCollections: [],
      integrations: [],
      owner: 'Platform Ops',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'System Overview Page', path: 'src/pages/admin/systemOverview.tsx' },
        { label: 'System Overview Manifest', path: 'src/content/system-overview/manifest.ts' },
      ],
    },
    {
      id: 'web-virtual-office',
      name: 'Virtual Office Command Center',
      persona: 'Internal operator and agent supervisors',
      outcome: 'Monitor agent status, task progress, and intervention points in real time.',
      entryPoints: ['/admin/virtualOffice'],
      dependentServices: ['presenceService', 'kanban service', 'timeline service'],
      firestoreCollections: ['agent-presence', 'kanbanTasks', 'progress-timeline', 'meeting-minutes'],
      integrations: ['OpenClaw runtime'],
      owner: 'Agent Infrastructure Team',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Virtual Office Page', path: 'src/pages/admin/virtualOffice.tsx' },
        { label: 'Virtual Office Content', path: 'src/components/virtualOffice/VirtualOfficeContent.tsx' },
      ],
    },
    {
      id: 'web-mission-control',
      name: 'Mission Control and North Star Operations',
      persona: 'Founder and operator leadership',
      outcome: 'Set mission context, monitor objective proposals, and coordinate agent directives.',
      entryPoints: ['/admin/missionControl'],
      dependentServices: ['company-config documents', 'presenceService'],
      firestoreCollections: ['company-config/mission-status', 'company-config/north-star', 'kanbanTasks'],
      integrations: [],
      owner: 'Agent Infrastructure Team',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Mission Control', path: 'src/pages/admin/missionControl.tsx' },
        { label: 'Kickoff Mission API', path: 'src/pages/api/agent/kickoff-mission.ts' },
      ],
    },
    {
      id: 'web-creator-pages',
      name: 'Creator Landing Pages and Custom Paths',
      persona: 'Creators and invited athletes',
      outcome: 'Host creator-specific onboarding and conversion pages tied to custom route segments.',
      entryPoints: ['/[username]/[page]', '/creator-onboarding'],
      dependentServices: ['Creator pages service', 'AuthWrapper public path resolver'],
      firestoreCollections: ['creatorPages', 'waitlist entries'],
      integrations: ['Brevo'],
      owner: 'Creator Platform',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Dynamic Creator Page', path: 'src/pages/[username]/[page].tsx' },
        { label: 'Creator Onboarding', path: 'src/pages/creator-onboarding.tsx' },
      ],
    },
    {
      id: 'web-pulsecheck-organization-activation',
      name: 'PulseCheck Organization Provisioning and Admin Activation',
      persona: 'Operators, coach-led organizations, and external program admins',
      outcome:
        'Provision PulseCheck organizations and teams, hand off admin activation, and prepare the container for downstream staff and athlete invites.',
      entryPoints: [
        '/admin/pulsecheckProvisioning',
        '/admin/pulsecheckLegacyRosterMigration',
        '/PulseCheck/admin-activation/[token]',
        '/PulseCheck/team-invite/[token]',
        '/PulseCheck/team-workspace',
      ],
      dependentServices: [
        'PulseCheck provisioning service',
        'admin activation API',
        'team invite redemption API',
        'migration tooling',
      ],
      firestoreCollections: [
        'pulsecheck-organizations',
        'pulsecheck-teams',
        'pulsecheck-organization-memberships',
        'pulsecheck-team-memberships',
        'pulsecheck-invite-links',
        'pulsecheck-legacy-roster-migrations',
      ],
      integrations: ['Firebase Auth', 'Next.js API routes'],
      owner: 'PulseCheck Platform',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Provisioning Console', path: 'src/pages/admin/pulsecheckProvisioning.tsx' },
        { label: 'Legacy Roster Migration', path: 'src/pages/admin/pulsecheckLegacyRosterMigration.tsx' },
        { label: 'Admin Activation Page', path: 'src/pages/PulseCheck/admin-activation/[token].tsx' },
      ],
    },
    {
      id: 'web-subscription-checkout',
      name: 'Web Checkout and Subscription Recovery',
      persona: 'Users purchasing access',
      outcome: 'Convert web users to active subscriptions and handle success/error outcomes.',
      entryPoints: ['/subscribe', '/subscription-success', '/subscription-error'],
      dependentServices: ['checkout Netlify functions', 'subscription service'],
      firestoreCollections: ['users', 'subscriptionRecords'],
      integrations: ['Stripe', 'RevenueCat'],
      owner: 'Monetization Team',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Subscribe Page', path: 'src/pages/subscribe.tsx' },
        { label: 'Subscription Service', path: 'src/api/firebase/subscription/service.ts' },
      ],
    },
    {
      id: 'web-admin-user-ops',
      name: 'Admin User and Challenge Operations',
      persona: 'Support and operations teams',
      outcome: 'Manage user state, challenge health, notifications, and manual intervention tasks.',
      entryPoints: ['/admin/users', '/admin/challengestatus', '/admin/SendNotification', '/admin/inactivityCheck'],
      dependentServices: ['Firestore admin reads/writes', 'notification functions'],
      firestoreCollections: ['users', 'sweatlistCollections', 'notifications'],
      integrations: ['FCM', 'Netlify Functions'],
      owner: 'Platform Ops',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Admin Users', path: 'src/pages/admin/users.tsx' },
        { label: 'Challenge Status', path: 'src/pages/admin/challengestatus.tsx' },
      ],
    },
    {
      id: 'web-admin-metrics',
      name: 'Admin Metrics and Workout Summaries',
      persona: 'Operations and analytics teams',
      outcome: 'Inspect system usage and summary-level operational data for quality checks.',
      entryPoints: ['/admin/metrics', '/admin/workoutSummaries'],
      dependentServices: ['Firestore aggregation', 'callable functions'],
      firestoreCollections: ['workout-summaries', 'exerciseVideos', 'sweatlist-collection'],
      integrations: ['Firebase Functions'],
      owner: 'Platform Ops',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Admin Metrics', path: 'src/pages/admin/metrics.tsx' },
        { label: 'Workout Summaries', path: 'src/pages/admin/workoutSummaries.tsx' },
      ],
    },
    {
      id: 'web-creator-economics',
      name: 'Creator Wallet, Score, and Payout Operations',
      persona: 'Creators, finance ops, and support teams',
      outcome:
        'Expose creator earnings, payout eligibility, payout history, leaderboard score context, and monthly statement availability in one operating surface.',
      entryPoints: ['/[username]/earnings', '/admin/adminPayouts'],
      dependentServices: ['get-unified-earnings', 'initiate-unified-payout', 'sync-pending-payouts', 'get-monthly-statement'],
      firestoreCollections: ['users', 'payoutRecords', 'prizeRecords', 'leaderboards'],
      integrations: ['Stripe', 'Netlify Functions'],
      owner: 'Monetization Team + Creator Platform',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Unified Earnings Page', path: 'src/pages/[username]/earnings.tsx' },
        { label: 'Admin Payout Dashboard', path: 'src/pages/admin/adminPayouts.tsx' },
        { label: 'Get Unified Earnings Function', path: 'netlify/functions/get-unified-earnings.js' },
        { label: 'Initiate Unified Payout Function', path: 'netlify/functions/initiate-unified-payout.js' },
        { label: 'Monthly Statement Function', path: 'netlify/functions/get-monthly-statement.js' },
      ],
    },
    {
      id: 'web-press-and-investor',
      name: 'Press Kit and Investor Data Room',
      persona: 'External press and investor stakeholders',
      outcome: 'Provide controlled access to brand assets and investor narrative/data room content.',
      entryPoints: ['/press', '/investor', '/admin/investorAccess'],
      dependentServices: ['Press asset upload paths', 'access controls'],
      firestoreCollections: ['investorAccess', 'press_assets metadata'],
      integrations: ['Firebase Storage'],
      owner: 'Leadership Ops',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Press Index', path: 'src/pages/press/index.tsx' },
        { label: 'Investor Page', path: 'src/pages/investor/index.tsx' },
      ],
    },
    {
      id: 'web-deliverables-pipeline',
      name: 'Agent Deliverables Index and Retrieval',
      persona: 'Internal operators',
      outcome: 'Browse and retrieve generated agent deliverables from local and GitHub sources.',
      entryPoints: ['/admin/deliverables/[agent]'],
      dependentServices: ['Deliverables manifest resolver', 'filesystem/GitHub fallback fetch'],
      firestoreCollections: ['deliverables metadata (indirect)'],
      integrations: ['GitHub raw content'],
      owner: 'Agent Infrastructure Team',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Deliverables Page', path: 'src/pages/admin/deliverables/[agent].tsx' },
        { label: 'Deliverables Docs', path: 'docs/sage/deliverables/README.md' },
      ],
    },
    {
      id: 'web-api-layer',
      name: 'API Route Layer for Admin and Agent Workflows',
      persona: 'Web app, admin tools, and agent systems',
      outcome: 'Provide server-side actions for mission kickoff, extraction workflows, and utility operations.',
      entryPoints: ['Next API routes under /api'],
      dependentServices: ['Firebase Admin SDK', 'external model APIs'],
      firestoreCollections: ['kanbanTasks', 'company-config', 'prospect collections'],
      integrations: ['OpenAI', 'Firebase Admin'],
      owner: 'Web Platform',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Kickoff Mission API', path: 'src/pages/api/agent/kickoff-mission.ts' },
        { label: 'Creator Prospect Extract API', path: 'src/pages/api/admin/extract-creator-prospects.ts' },
      ],
    },
  ],
};
