import type { ProductHandbook } from '../schema';

export const quickliftsIosHandbook: ProductHandbook = {
  id: 'quicklifts-ios',
  name: 'QuickLifts iOS',
  platform: 'iOS (SwiftUI)',
  summary:
    'Flagship mobile product for workout execution, round participation, nutrition tracking, and social fitness loops.',
  owner: 'iOS Squad',
  repo: 'QuickLifts',
  releaseChannel: 'TestFlight weekly + App Store production',
  status: 'active',
  keyOutcomes: [
    'Daily workout completion and adherence',
    'Creator-led round engagement and retention',
    'Physical + nutrition behavior tracking',
  ],
  featureInventory: [
    {
      id: 'ios-workout-planning',
      name: 'Workout Planning and Builder',
      persona: 'Athletes and coaches',
      outcome: 'Build and customize reusable workouts with exercises, sets, reps, and sequencing.',
      entryPoints: ['Home > Create', 'Workout screens', 'Discover workout panel'],
      dependentServices: ['Firestore', 'WorkoutService', 'ExerciseService'],
      firestoreCollections: ['users/{uid}/workouts', 'exercises'],
      integrations: [],
      owner: 'iOS Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Create Workout', path: '../iOS/QuickLifts/QuickLifts/View/Screens/CreateWorkout/CreateWorkoutView.swift' },
        { label: 'Workout Service', path: '../iOS/QuickLifts/QuickLifts/Services/WorkoutService.swift' },
      ],
    },
    {
      id: 'ios-active-workout-session',
      name: 'Active Workout Session Engine',
      persona: 'Athletes',
      outcome: 'Run live workout sessions with progress tracking, timers, and completion states.',
      entryPoints: ['Home > Continue workout', 'Workout ready screens', 'Workout type launchers'],
      dependentServices: ['WorkoutSessionService', 'Firestore'],
      firestoreCollections: ['users/{uid}/completed-workouts', 'users/{uid}/exercise-logs'],
      integrations: ['Apple Watch'],
      owner: 'iOS Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Workout Overview', path: '../iOS/QuickLifts/QuickLifts/View/Screens/WorkoutInProgress/WorkoutOverview/WorkoutOverviewView.swift' },
        { label: 'Workout Session Service', path: '../iOS/QuickLifts/QuickLifts/Services/WorkoutSessionService.swift' },
      ],
    },
    {
      id: 'ios-round-creation-ai',
      name: 'AI Round Creation (Template + Custom)',
      persona: 'Creators and coaches',
      outcome: 'Generate and publish complete round plans with workout stacks over a date window.',
      entryPoints: ['Create Challenge flow', 'Round configuration modal'],
      dependentServices: ['TemplateGenerationService', 'WorkoutService', 'UserService'],
      firestoreCollections: ['sweatlistCollections', 'users/{uid}/workouts'],
      integrations: ['OpenAI'],
      owner: 'iOS Squad + AI Systems',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Create Challenge View', path: '../iOS/QuickLifts/QuickLifts/View/Challenge/ChallengeSetupView/CreateChallengeView.swift' },
        { label: 'Round Generation Flows Doc', path: '../iOS/docs/round-generation-flows.md' },
      ],
    },
    {
      id: 'ios-round-participation',
      name: 'Round Participation and Leaderboard',
      persona: 'Athletes in rounds',
      outcome: 'Join rounds, complete assigned workouts, and compete on leaderboards.',
      entryPoints: ['Rounds tab', 'Round invitation deep links', 'Round detail views'],
      dependentServices: ['WorkoutService', 'LeaderboardService', 'Firestore'],
      firestoreCollections: ['sweatlistCollections', 'sweatlistCollections/{id}/participants', 'sweatlistCollections/{id}/leaderboard-entries'],
      integrations: [],
      owner: 'iOS Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Round Detail', path: '../iOS/QuickLifts/QuickLifts/View/Challenge/ChallengeDetailView.swift' },
        { label: 'Run Round Detail', path: '../iOS/QuickLifts/QuickLifts/View/RunRound/RunRoundDetailView.swift' },
      ],
    },
    {
      id: 'ios-checkin-system',
      name: 'Check-in System and Reflection',
      persona: 'Athletes and coaches',
      outcome: 'Capture daily status and progress context for accountability and coaching follow-up.',
      entryPoints: ['Challenge check-in prompts', 'Profile check-in screens'],
      dependentServices: ['UserService', 'Firestore'],
      firestoreCollections: ['users/{uid}/check-ins', 'sweatlistCollections/{id}/participants'],
      integrations: ['Push Notifications'],
      owner: 'iOS Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Check-in Callout', path: '../iOS/QuickLifts/QuickLifts/View/Challenge/CheckinCalloutModalView.swift' },
        { label: 'Check-in System Doc', path: '../iOS/QuickLifts/QuickLifts/README-CHECKIN-SYSTEM.md' },
      ],
    },
    {
      id: 'ios-nutrition-tracking',
      name: 'Food Logging and Meal Tracking',
      persona: 'Athletes',
      outcome: 'Track meals, labels, and nutrition quality to support training goals.',
      entryPoints: ['Food tracker', 'Meal views', 'Label scan flows'],
      dependentServices: ['Nutrition services', 'Firestore', 'Storage'],
      firestoreCollections: ['users/{uid}/meals', 'users/{uid}/meal-plans'],
      integrations: ['Camera', 'AI nutrition scoring'],
      owner: 'iOS Squad + Nutrition Systems',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Scan Food View', path: '../iOS/QuickLifts/QuickLifts/View/Screens/FoodTrackerView/ScanFoodView.swift' },
        { label: 'Meal Planning Doc', path: '../iOS/QuickLifts/QuickLifts/MEAL_PLANNING_SYSTEM.md' },
      ],
    },
    {
      id: 'ios-social-messaging',
      name: 'Social Messaging and Community',
      persona: 'Athletes and creators',
      outcome: 'Message peers, comment, and maintain social accountability loops.',
      entryPoints: ['Messages screens', 'Round chat views', 'Profile interactions'],
      dependentServices: ['ChatService', 'Firestore'],
      firestoreCollections: ['conversations', 'messages'],
      integrations: ['Push Notifications'],
      owner: 'iOS Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Challenge Chat View', path: '../iOS/QuickLifts/QuickLifts/View/Challenge/ChallengeChatView.swift' },
        { label: 'Message Components', path: '../iOS/QuickLifts/QuickLifts/View/Components/MessageComponents.swift' },
      ],
    },
    {
      id: 'ios-creator-engagement-tracking',
      name: 'Creator Engagement Tracking (Usage, Likes, Bookmarks)',
      persona: 'Creators and creator operations',
      outcome: 'Track how creator videos are reached, liked, bookmarked, and used inside workouts with event-level fidelity.',
      entryPoints: ['Discover/feed video interactions', 'Workout exercise cards', 'Bookmark/like controls'],
      dependentServices: ['EngagementService', 'Exercise logging hooks', 'UserService favorite/like persistence'],
      firestoreCollections: ['engagement-events', 'exerciseVideos', 'users/{uid}/myFavoriteExercises', 'users/{uid}/myLikedExercises'],
      integrations: [],
      owner: 'Creator Platform + iOS Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Engagement Service', path: '../iOS/QuickLifts/QuickLifts/Services/EngagementService.swift' },
        { label: 'Exercise Event Hooks', path: '../iOS/QuickLifts/QuickLifts/Models/Exercise.swift' },
        { label: 'Engagement Metrics Model', path: '../iOS/QuickLifts/QuickLifts/Models/Analytics/EngagementMetrics.swift' },
        { label: 'User Like/Bookmark Storage', path: '../iOS/QuickLifts/QuickLifts/Services/UserService/UserService.swift' },
      ],
    },
    {
      id: 'ios-creator-score-leaderboard',
      name: 'Creator Score and Top Creators Leaderboard',
      persona: 'Creators, community teams, and leaderboard operators',
      outcome: 'Accumulate creator score in `categoryPoints.creator` and publish ranked creator leaderboards.',
      entryPoints: ['Workout completion scoring path', 'Global leaderboard > Top Creators tab'],
      dependentServices: ['HunterRankService', 'Leaderboard cache jobs', 'Global leaderboard view model'],
      firestoreCollections: ['users', 'leaderboards/topCreators', 'users/{uid}/workoutSummary'],
      integrations: [],
      owner: 'Creator Platform + iOS Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Hunter Rank Service', path: '../iOS/QuickLifts/QuickLifts/Services/HunterRankService.swift' },
        { label: 'Top Creators ViewModel', path: '../iOS/QuickLifts/QuickLifts/View/Screens/Leaderboard/GlobalLeaderboardViewModel.swift' },
        { label: 'Leaderboard Cache Script', path: 'scripts/cacheLeaderboardsOnce.js' },
        { label: 'Creator Score Backfill', path: 'scripts/backfillCreatorScore.js' },
      ],
    },
    {
      id: 'ios-healthkit-sync',
      name: 'HealthKit and Biometrics Sync',
      persona: 'Athletes using Apple ecosystem',
      outcome: 'Sync workouts, activity rings, and health context to improve insights.',
      entryPoints: ['Health permissions', 'Workout summaries', 'Health data stories'],
      dependentServices: ['HealthKitManager', 'Firestore'],
      firestoreCollections: ['users/{uid}/health-data', 'users/{uid}/completed-workouts'],
      integrations: ['HealthKit', 'Apple Watch'],
      owner: 'iOS Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Health Sync Settings', path: '../iOS/QuickLifts/QuickLifts/View/Components/HealthDataSyncSettingsView.swift' },
        { label: 'Architecture Guide', path: '../iOS/docs/pulse-app-guide.md' },
      ],
    },
    {
      id: 'ios-subscription-access',
      name: 'Subscription and Access Control',
      persona: 'Free and paid users',
      outcome: 'Gate premium features and route users into active subscription states.',
      entryPoints: ['Paywall screens', 'Programmatic redirects', 'Feature checks'],
      dependentServices: ['Firebase Auth', 'Subscription service'],
      firestoreCollections: ['users', 'subscriptionRecords'],
      integrations: ['RevenueCat', 'Stripe'],
      owner: 'Monetization Team',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Subscription Models', path: '../iOS/QuickLifts/QuickLifts/Models/Subscription.swift' },
        { label: 'Subscription Guide', path: 'docs/subscription-system.md' },
      ],
    },
    {
      id: 'ios-creator-content',
      name: 'Creator Content and Move Upload',
      persona: 'Creators and coaches',
      outcome: 'Upload moves/videos and manage creator-facing profile content.',
      entryPoints: ['Profile creator sections', 'Move upload flow'],
      dependentServices: ['Storage', 'Firestore', 'Video processing pipeline'],
      firestoreCollections: ['exercises', 'exerciseVideos', 'users/{uid}/creator-content'],
      integrations: ['Firebase Storage'],
      owner: 'Creator Platform',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Move Upload Screen', path: '../iOS/QuickLifts/QuickLifts/View/Screens/EditMoveDetailsView/EditMoveDetailsView.swift' },
        { label: 'Video Upload Flow', path: '../iOS/QuickLifts/QuickLifts/View/Screens/ExerciseCaptionView/ExerciseCaptionView.swift' },
      ],
    },
    {
      id: 'ios-run-fatburn-modes',
      name: 'Run and Fat Burn Modes',
      persona: 'Endurance and conditioning athletes',
      outcome: 'Execute modality-specific guided sessions with scoring and summaries.',
      entryPoints: ['Run configuration', 'Fat burn configuration', 'Home quick starts'],
      dependentServices: ['Workout generation services', 'Firestore'],
      firestoreCollections: ['users/{uid}/completed-workouts', 'sweatlistCollections'],
      integrations: ['HealthKit'],
      owner: 'iOS Squad',
      releaseChannel: 'Production',
      status: 'active',
      sourceRefs: [
        { label: 'Run Round Configuration', path: '../iOS/QuickLifts/QuickLifts/View/RunRound/RunRoundConfigurationView.swift' },
        { label: 'Fat Burn Configuration', path: '../iOS/QuickLifts/QuickLifts/View/FatBurnRound/FatBurnRoundConfigurationView.swift' },
      ],
    },
    {
      id: 'ios-admin-migration-tools',
      name: 'In-App Admin and Migration Utilities',
      persona: 'Internal operators',
      outcome: 'Enable migration checks and debug/admin controls within the app runtime.',
      entryPoints: ['Migration dashboard', 'Beta drawer', 'Debug flows'],
      dependentServices: ['Firestore', 'Internal admin APIs'],
      firestoreCollections: ['app-config', 'users'],
      integrations: [],
      owner: 'Platform Ops',
      releaseChannel: 'Internal',
      status: 'beta',
      sourceRefs: [
        { label: 'Migration Dashboard', path: '../iOS/QuickLifts/QuickLifts/View/Admin/MigrationDashboardView.swift' },
        { label: 'Beta Drawer', path: '../iOS/QuickLifts/QuickLifts/View/Screens/Beta/BetaDrawerView.swift' },
      ],
    },
  ],
};
