const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,f);
let records=new Map(),writes=[],providerCalls=0;
const snap=key=>({exists:records.has(key),data:()=>records.get(key)});
const ref=key=>({key,get:async()=>snap(key),collection:name=>collection(key+'/'+name)});
const collection=key=>({doc:id=>ref(key+'/'+id),orderBy:()=>({limit:()=>({get:async()=>({docs:records.has(key)?[{data:()=>records.get(key)}]:[]})})})});
const db={collection,runTransaction:async fn=>fn({get:async r=>snap(r.key),create:(r,value)=>{if(records.has(r.key))throw Error('exists');records.set(r.key,value);writes.push(value);}})};
const admin={auth:()=>({verifyIdToken:async token=>{if(token!=='valid')throw Error('bad token');return {uid:'athlete',email:'athlete@example.com'};}}),firestore:Object.assign(()=>db,{FieldValue:{serverTimestamp:()=> 'server-time'}})};
require.cache[path.resolve('src/lib/firebase-admin.ts')]={id:path.resolve('src/lib/firebase-admin.ts'),filename:path.resolve('src/lib/firebase-admin.ts'),loaded:true,exports:{__esModule:true,default:admin,getFirebaseAdminApp:()=>({})}};
const handler=require(path.resolve('src/pages/api/pulsecheck/questionnaire/cau-team-test.ts')).default;
function setup(){records=new Map();writes=[];providerCalls=0;process.env.CAU_TEAM_TEST_INVITE='test-invite';process.env.CAU_TEAM_TEST_CAMPAIGN='test-campaign';process.env.CAU_TEAM_TEST_EXPIRES_AT='2099-01-01T00:00:00Z';process.env.AUNTEDNA_PARTNER_TEST_KEY='ae_pk_test_fake';
 global.fetch=async(url,opts)=>{providerCalls++;const body=JSON.parse(opts.body);assert.equal(body.universityCode,'SANDBOX');assert.equal(body.identity.email.includes('athlete@'),false);assert.equal(Object.keys(body.fields).length,48);assert.equal(body.fields['cau-operational-35'],undefined);return Response.json({success:true,requestId:'request',data:{baselineId:'baseline',athleteId:'ae-athlete',externalId:url.split('/').at(-2),submissionId:body.submissionId,receivedAt:'2026-09-18T12:00:00Z',created:true}});};
}
async function call(method,body,invite='test-invite',token='valid'){let result={status:200};const res={setHeader(){},status(n){result.status=n;return this;},json(v){result.body=v;return this;},end(){return this;}};await handler({method,headers:{authorization:'Bearer '+token,'x-questionnaire-test':invite},body},res);return result;}
const body={name:'Fictional Athlete',email:'test@example.com',answers:{'cau-operational-26':'PRIVATE_SENTINEL'},completedSections:{performance:true,health:true},shareHealth:true,fictionalDataConfirmed:true};
test('team test requires invite, sign-in and fictional-data acknowledgment',async()=>{setup();assert.equal((await call('GET',null,'wrong')).status,403);assert.equal((await call('GET',null,'test-invite','wrong')).status,401);assert.equal((await call('POST',{...body,fictionalDataConfirmed:false})).status,400);assert.equal(providerCalls,0);});
test('sandbox routing, own receipt, reference-only persistence and duplicate prevention',async()=>{setup();const first=await call('POST',body);assert.equal(first.body.saved,true);assert.equal(first.body.receipt.baselineId,'baseline');assert.equal(JSON.stringify(writes).includes('PRIVATE_SENTINEL'),false);assert.equal(writes.some(r=>r.kind==='assignment'),false);assert.equal((await call('GET')).body.completed,true);assert.equal((await call('POST',body)).body.receipt.baselineId,'baseline');assert.equal(providerCalls,1);});
test('expired link and live key cannot activate sandbox',async()=>{setup();process.env.AUNTEDNA_PARTNER_TEST_KEY='ae_pk_live_wrong';assert.equal((await call('GET')).status,503);setup();process.env.CAU_TEAM_TEST_EXPIRES_AT='2020-01-01';assert.equal((await call('GET')).status,503);assert.equal(providerCalls,0);});
