const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true,target:ts.ScriptTarget.ES2022}}).outputText,f);
let records=new Map(),writes=[],providerCalls=0;
const snap=key=>({exists:records.has(key),data:()=>records.get(key)});
const ref=key=>({key,get:async()=>snap(key),collection:name=>collection(key+'/'+name)});
const collection=key=>({doc:id=>ref(key+'/'+id),orderBy:()=>({limit:()=>({get:async()=>({docs:records.has(key)?[{data:()=>records.get(key)}]:[]})})})});
const db={collection,runTransaction:async fn=>fn({get:async r=>snap(r.key),create:(r,value)=>{if(records.has(r.key))throw Error('exists');records.set(r.key,value);writes.push(value);}})};
const admin={auth:()=>({verifyIdToken:async token=>{if(token!=='valid')throw Error('bad token');return {uid:'athlete',email:'athlete@example.com'};}}),firestore:Object.assign(()=>db,{FieldValue:{serverTimestamp:()=> 'server-time'}})};
require.cache[path.resolve('src/lib/firebase-admin.ts')]={id:path.resolve('src/lib/firebase-admin.ts'),filename:path.resolve('src/lib/firebase-admin.ts'),loaded:true,exports:{__esModule:true,default:admin,getFirebaseAdminApp:()=>({})}};
const handler=require(path.resolve('src/pages/api/pulsecheck/questionnaire/cau.ts')).default;
const root='pulsecheck-restricted-questionnaire-submissions/';
function setup(){records=new Map();writes=[];providerCalls=0;process.env.CAU_QUESTIONNAIRE_COLLECTION_ENABLED='true';process.env.AUNTEDNA_PARTNER_TEST_KEY='ae_pk_test_fake';
 records.set(root+'assignment_athlete',{kind:'assignment',enabled:true,version:'cau-operational-web-v1',teamId:'team',submissionId:'sub-1',environment:'test',universityCode:'SANDBOX'});
 records.set('pulsecheck-team-memberships/team_athlete',{status:'active'});
 records.set('athlete-mental-progress/athlete',{mentalSkillsBaseline:{version:5}});
 global.fetch=async()=>{providerCalls++;return Response.json({success:true,requestId:'request',data:{baselineId:'baseline',athleteId:'ae-athlete',externalId:'athlete',submissionId:'sub-1',receivedAt:'2026-09-16T12:00:00Z',created:providerCalls===1}});};
}
async function call(method,body,token='valid'){let result={status:200};const res={setHeader(){},status(n){result.status=n;return this;},json(v){result.body=v;return this;},end(){return this;}};await handler({method,headers:{authorization:'Bearer '+token},body},res);return result;}
const body={name:'Fictional Athlete',email:'test@example.com',answers:{'cau-operational-26':'PRIVATE_SENTINEL'},completedSections:{performance:true,health:true},shareHealth:true};
test('status is authenticated and only active assigned accounts are required',async()=>{setup();assert.equal((await call('GET',null,'invalid')).status,401);assert.equal((await call('GET')).body.required,true);records.delete(root+'assignment_athlete');assert.equal((await call('GET')).body.required,false);});
test('no consent cannot transmit health; performance-only resolution does not store clinical values',async()=>{setup();assert.equal((await call('POST',body)).status,403);assert.equal(providerCalls,0);assert.equal((await call('POST',{...body,shareHealth:false})).body.saved,true);assert.equal(providerCalls,0);assert.equal(JSON.stringify(writes).includes('PRIVATE_SENTINEL'),false);assert.equal((await call('GET')).body.completed,true);});
test('signed current authorization sends health once and persists references only',async()=>{setup();const doc={id:'health',version:'v1',body:'Terms',category:'health_authorization'};const decisions={health:{decision:'accepted',version:'v1',document:doc,signedName:'Fictional Athlete'}};records.set('pulsecheck-teams/team',{requiredConsents:[doc]});records.set('pulsecheck-team-memberships/team_athlete',{status:'active',athleteOnboarding:{consentDecisions:decisions}});records.set('pulsecheck-team-memberships/team_athlete/consent-events',{actorUserId:'athlete',decisions});assert.equal((await call('POST',body)).body.saved,true);assert.equal(providerCalls,1);assert.equal(JSON.stringify(writes).includes('PRIVATE_SENTINEL'),false);assert.equal((await call('POST',body)).body.saved,true);assert.equal(providerCalls,1);assert.equal((await call('GET')).body.required,false);});
test('retired assignments and incomplete sections cannot submit',async()=>{setup();assert.equal((await call('POST',{...body,completedSections:{performance:true}})).status,400);records.set('pulsecheck-team-memberships/team_athlete',{status:'inactive'});assert.equal((await call('POST',body)).status,503);assert.equal(providerCalls,0);});
