import {mealNameFromMessage} from '../../../lib/nora-red-team/chatActions';
import React,{useState} from 'react';
import styles from './ChatSimulation.module.css';
export default function MealActionCard({description,onSaved,onDecline}:{description:string;onSaved:(summary:string)=>void;onDecline:()=>void}){
 const [open,setOpen]=useState(false),[id]=useState(()=>crypto.randomUUID()),[name,setName]=useState(()=>mealNameFromMessage(description)),[portion,setPortion]=useState(''),[image,setImage]=useState(''),[values,setValues]=useState<Record<string,string>>({calories:'',protein:'',carbs:'',fat:''}),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [estimating,setEstimating]=useState(false),[assumptions,setAssumptions]=useState('');
 async function estimate(){setEstimating(true);setError('');try{const r=await fetch('/api/admin/pulsecheck/nora-red-team/estimate-meal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({description:name||description,portion})});const x=await r.json();if(!r.ok)throw Error(x.error);setName(x.estimate.name);setPortion(x.estimate.servingSize);setValues(Object.fromEntries(['calories','protein','carbs','fat'].map(k=>[k,String(x.estimate[k])])));setAssumptions(x.estimate.assumptions);}catch(e){setError((e as Error).message)}finally{setEstimating(false)}}
 async function persist(){setBusy(true);setError('');try{const response=await fetch('/api/admin/pulsecheck/nora-red-team/local-meal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,name,servingSize:portion,image,confirmed:true,nutritionSource:assumptions?'ai_estimate':'user_entered',nutritionAssumptions:assumptions,...Object.fromEntries(Object.entries(values).map(([k,v])=>[k,Number(v)]))})});const data=await response.json();if(!response.ok)throw new Error(data.error);setSaved(true);setOpen(false);onSaved(`Meal saved: ${data.meal.name}; portion: ${data.meal.servingSize}.`);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className={styles.actionCard}><strong>{saved?'Logged in development':'Want to log that meal?'}</strong>{image?<img src={image} alt="Your meal" style={{width:160,height:110,objectFit:'cover',borderRadius:8}}/>:<p>🍽️ Your meal photo can go here.</p>}{saved&&!open?<><p>{name} · {portion}</p><button onClick={()=>setOpen(true)}>Edit meal or photo</button><button onClick={async()=>{const r=await fetch('/api/admin/pulsecheck/nora-red-team/local-meal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,operation:'read'})});const x=await r.json();setError(r.ok&&x.meal?'Saved record verified in Firebase.':'Could not verify saved record.');}}>Verify saved record</button></>:!open?<><button onClick={()=>{setOpen(true);void estimate()}}>Log meal</button><button onClick={onDecline}>Not now</button></>:<form onSubmit={e=>{e.preventDefault();void persist()}}><label>Meal<input disabled={estimating} required maxLength={500} value={name} onChange={e=>setName(e.target.value)}/></label><label>Portions<input disabled={estimating} required maxLength={200} value={portion} placeholder="For example: one bowl" onChange={e=>setPortion(e.target.value)}/></label><p>Estimated nutrition. Review the portions before saving.</p><p>{assumptions}</p><button type="button" disabled={estimating||busy} onClick={()=>void estimate()}>{estimating?'Estimating…':'Update estimate'}</button><div className={styles.nutrients}>{Object.keys(values).map(k=><label key={k}>{k==='calories'?'Calories':`${k} (g)`}<input type="number" required min={0} max={20000} step="any" value={values[k]} onChange={e=>setValues({...values,[k]:e.target.value})}/></label>)}</div><label>{image?'Change photo':'Add your photo'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>300000||!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Choose a JPEG, PNG or WebP photo under 300 KB.');return;}const reader=new FileReader();reader.onload=()=>setImage(String(reader.result));reader.readAsDataURL(file);}}/></label>{image&&<button type="button" onClick={()=>setImage('')}>Remove photo</button>}<button disabled={busy||estimating||!values.calories} type="submit">{busy?'Saving…':saved?'Save changes':'Confirm and save'}</button><button type="button" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button></form>}{error&&<p role="status">{error}</p>}</section>;
}
